- helmfile.d/nginx-ingress.yaml
This PR deploys [this](https://github.com/jenkins-infra/404/pull/3) changes
> Update default nginx backend container to fix healthcheck

- config/release/jenkins/values.yaml
This new job will package experimental jenkins version on the k8s cluster
> Add packaging pipeline to jenkins release environment

- config/grafana/secrets.yaml
- config/grafana/values.yaml
- config/loki/values.yaml
- config/prometheus/values.yaml
- config/promtail/values.yaml
- helmfile.d/00-repositories.yaml
- helmfile.d/grafana.yaml
- helmfile.d/loki.yaml
- helmfile.d/prometheus.yaml
Deploy Loki/Grafana/Prometheus in order to better understand cluster resource usages
> Enable Loki/Grafana/Prometheus

- config/release/jenkins/values.yaml
Those settings harm more than it helps
> Remove timeout settings

- config/release/jenkins/values.yaml
I am not sure to understand why ^ is needed but jscasc config seems to need it
> This time parameter should be working -_-

- config/release/jenkins/values.yaml
[Changelog](https://github.com/jenkinsci/docker-jnlp-slave/releases)
> Bump jnlp docker image tag

- CODEOWNERS
- charts/wiki2md/.helmignore
- charts/wiki2md/Chart.yaml
- charts/wiki2md/templates/NOTES.txt
- charts/wiki2md/templates/_helpers.tpl
- charts/wiki2md/templates/deployment.yaml
- charts/wiki2md/templates/ingress.yaml
- charts/wiki2md/templates/service.yaml
- charts/wiki2md/templates/tests/test-connection.yaml
- charts/wiki2md/values.yaml
- config/wiki2md/values.yaml
- helmfile.d/wiki2md.yaml
This PR deploy a new service named wiki2md.jenkins.io to help with [this](https://groups.google.com/d/msgid/jenkinsci-dev/CAG%3D_DutHHNZGM8r5UOcU26sQdSLy0-JGH26HNFCaLUwiqMkCtg%40mail.gmail.com?utm_medium=email&utm_source=footer)
> Create wiki2md helm chart

- charts/jenkins-wiki-exporter/values.yaml
> Update wiki exporter to 1.2.0

- charts/polls/.helmignore
- charts/polls/Chart.yaml
- charts/polls/templates/NOTES.txt
- charts/polls/templates/_helpers.tpl
- charts/polls/templates/admin-ingress.yaml
- charts/polls/templates/configmap.yaml
- charts/polls/templates/deployment-frontend.yaml
- charts/polls/templates/deployment-migration.yaml
- charts/polls/templates/deployment.yaml
- charts/polls/templates/frontend-service.yaml
- charts/polls/templates/ingress.yaml
- charts/polls/templates/secrets.yaml
- charts/polls/templates/service-frontend.yaml
- charts/polls/templates/service.yaml
- charts/polls/templates/tests/test-connection.yaml
- charts/polls/values.yaml
- config/dex/secrets.yaml
- config/dex/values.yaml
- config/oauth2-proxy/secrets.yaml
- config/oauth2-proxy/values.yaml
- config/polls/secrets.yaml
- config/polls/values.yaml
- helmfile.d/dex.yaml
- helmfile.d/oauth2-proxy.yaml
- helmfile.d/polls.yaml
This chart deploys a simple application to collect emails who want to participate to a specific 'poll'
In the current state, this PR is mainly here to bring visibility on this work, and collect any discussion/coment on this topic
> Create polls chart

- charts/jenkins-wiki-exporter/values.yaml
cc @timja for https://github.com/jenkins-infra/jenkins-wiki-exporter/pull/29
> Release jenkins-wiki-exporter

- charts/jenkins-wiki-exporter/values.yaml
> Release 1.3.1

- charts/jenkins/README.md
See https://issues.jenkins-ci.org/browse/INFRA-2348
CC @MarkEWaite @olblak
> [INFRA-2348] - Document the Helm chart for the Core Release Environment

- .sops.yaml
- CODEOWNERS
- charts/plugin-site/.gitignore
- charts/plugin-site/.helmignore
- charts/plugin-site/Chart.yaml
- charts/plugin-site/README.md
- charts/plugin-site/templates/NOTES.txt
- charts/plugin-site/templates/_helpers.tpl
- charts/plugin-site/templates/deployment.yaml
- charts/plugin-site/templates/ingress.yaml
- charts/plugin-site/templates/secret.yaml
- charts/plugin-site/templates/service.yaml
- charts/plugin-site/templates/tests/test-connection.yaml
- charts/plugin-site/values.yaml
- clusters/publick8s.yaml
- config/default/plugin-site.yaml
- helmfile.d/plugin-site.yaml
Needs secrets
Tested on minikube, had a couple of issues with DNS / service routing.
Also tested on an AKS cluster and it seemed to work fine there
Edit:
minikube issue was:
https://github.com/kubernetes/minikube/issues/1568
Let me know what you think
cc @olblak
> INFRA-2357 Add plugin site chart

- .gitignore
- charts/acme/README.md
- charts/acme/templates/clusterIssuer.yaml
- charts/acme/templates/secret.yaml
- charts/acme/values.yaml
- config/default/acme.yaml
So that we can add jenkins-ci.org to lets encrypt certs
Needs secret update
> INFRA-2374 Enhance ACME chart to allow multiple dns zones

- charts/chatbot/templates/_helpers.tpl
- charts/chatbot/templates/deployment.yaml
- charts/chatbot/templates/secret.yaml
> Add remaining jenkinsadmin to chatbot rename

- config/default/jenkinsio.yaml
Breaks accessing mirrors in browser
See https://github.com/kubernetes/ingress-nginx/issues/549
> Remove HSTS on jenkins.io

- charts/accountapp/values.yaml
https://hub.docker.com/layers/jenkinsciinfra/account-app/84-buildc612cb/images/sha256-acfd63bfe6d911c3820a748464deb084ab9a469634dc9687980c6af629c5c2f8
> Update accountapp tag

- charts/plugin-site/values.yaml
> Bump plugin-site-api

- config/default/jenkins-infra.yaml
* Add missing credentials
* Only build the master branch
> Add missing sops credentials

- PodTemplates.yaml
The current limit seems to be very limited
> Increase helmfile & updatecli cpu limit

- PodTemplates.yaml
- config/default/jenkins-infra.yaml
- config/default/jenkins.yaml
This credential is the same than `github-access-token`
> Remove duplicated github credential id

- PodTemplates.yaml
- config/default/jenkins.yaml
The helmfile keeps to get killed
> Re-increase podtemplite limit

- PodTemplates.yaml
- charts/jenkinsio/values.yaml
- updateCli.d/jenkins-wiki-exporter.yaml
- updateCli.d/jenkins.yaml
- updateCli.d/nginx.yaml
- updateCli.d/pluginsite.yaml
*  Pin down updatecli version
* Switch jenkinio nginx version from tag to digest
* Add updatecli rule for nginx container of jenkins.io 
*  Pin down nginx version for jenkins.io
> Update jenkins.io nginx image with updatecli using docker digest method

- config/default/jenkinsio.yaml
jenkinsio containers are killed by the OOM killer, I suggest to add more containers to reduce the load on each of them
> Add more jenkinsio nginx containers

- updateCli.d/nginx.yaml
> Fix jenkinsio directory inside updatecli configuration

- charts/mirrorbits/templates/deployment.files.yaml
> Only mount one file in mirrorbits configuration

- charts/chatbot/values.yaml
This has a fix for the hosting process (see issues.jenkins-ci.org/browse/INFRA-2545)
> Update to build with for for INFRA-2545

- config/default/jenkinsio.yaml
https://github.com/jenkins-infra/jenkins.io/issues/3115
> Enforce www.jenkins.io

- charts/accountapp/values.yaml
https://github.com/jenkins-infra/account-app/pull/127
> Update account app

- config/default/jenkins-release.yaml
This changes is needed as a workaround for https://github.com/olblak/updatecli/issues/40, in order to fix formating issue in this [PR](https://github.com/jenkins-infra/charts/pull/195)
> Remove comments from jenkins-release.yaml

- PodTemplates.yaml
New version to fix a regression in the tool
> Bump updatecli version

- docker/Dockerfile
> Bump various version tooling

- config/default/grafana.yaml
100000 was bit too much :trollface:
> Reduce grafana default maxlines to 30000

- helmfile.d/nginx-ingress.yaml
this podSecurityContext is not (anymore) valid based on helm v3 validation checks
> Bump Nginx ingress version

- charts/plugin-site/templates/deployment-backend.yaml
- charts/plugin-site/templates/secret.yaml
- charts/plugin-site/values.yaml
Bump to newest version of plugin-site-api
Add credentials from https://github.com/jenkins-infra/charts-secrets/pull/1
> Add jira credentails

- Jenkinsfile_k8s
> Don't run helm init

- PodTemplates.yaml
> Bump helmfile container tag

- PodTemplates.yaml
> Update helmfile docker image

- helmfile.d/cert-manager.yaml
- helmfile.d/datadog.yaml
- helmfile.d/dex.yaml
- helmfile.d/falco.yaml
- helmfile.d/grafana.yaml
- helmfile.d/loki.yaml
- helmfile.d/mirrorbits.yaml
- helmfile.d/nginx-ingress.yaml
- helmfile.d/prometheus.yaml
Signed-off-by: Gavin Mogan <git@gavinmogan.com>
> Add repositories for each helmfile as needed so it passes lint in a clean environment

- Jenkinsfile_k8s
Signed-off-by: Gavin Mogan <git@gavinmogan.com>
> Make sure all the helm directories exist before using them

- PodTemplates.yaml
Signed-off-by: Gavin Mogan <git@gavinmogan.com>
> Move home dir to /home/helm which exists and is the user being run

- Jenkinsfile_k8s
The wackamole continues
Signed-off-by: Gavin Mogan <git@gavinmogan.com>
> Remove a stage that I accidently commited (i wish i could test with replay instead of commit and wait)

- charts/accountapp/values.yaml
Picks up https://github.com/jenkins-infra/account-app/pull/132
> Update the account app

- .github/pull_request_template.md
- CONTRIBUTING.md
- README.md
- REVIEW_GUIDELINES.md
This documentation is heavily inspired by the Helm project [link](https://github.com/helm/charts/blob/master/CONTRIBUTING.md)
While most of this is common sense, I also propose to start using signed commits
> Add contributing documentation

- charts/chatbot/values.yaml
Updates the ircbot to the latest version with hosting checking
N/A
> [master/chatbot] Update to latest ircbot build

- updateCli/updateCli.d/charts/codecentric-keycloak.tpl
- updateCli/updateCli.d/charts/dex.tpl
- updateCli/updateCli.d/charts/grafana-loki.tpl
- updateCli/updateCli.d/charts/grafana-promtail.tpl
- updateCli/updateCli.d/charts/jetstack-certmanager.tpl
- updateCli/updateCli.d/charts/prometheus.tpl
- updateCli/updateCli.d/charts/stable-datadog.tpl
- updateCli/updateCli.d/charts/stable-falco.tpl
- updateCli/updateCli.d/charts/stable-jenkins.tpl
- updateCli/updateCli.d/charts/stable-mirrorbits-redis.tpl
- updateCli/updateCli.d/charts/stable-nginx-ingress.tpl
- updateCli/updateCli.d/charts/stable-oauth2-proxy.tpl
- updateCli/updateCli.d/jenkins-lts-jdk11.tpl
- updateCli/updateCli.d/jenkins-weekly-jdk11.tpl
- updateCli/updateCli.d/jenkins-wiki-exporter.tpl
- updateCli/updateCli.d/ldap-crond.tpl
- updateCli/updateCli.d/ldap-slapd.tpl
- updateCli/updateCli.d/nginx.tpl
- updateCli/updateCli.d/pluginsite.tpl
* Update updatecli target name
* updatcli config for dex update to the correct file
target name is used to generate commit message and PR title which makes it easier to review
> Update updatecli target name

- charts/chatbot/values.yaml
There are some small fixes needed for the hosting checker. There are detailed here: https://github.com/jenkins-infra/ircbot/pull/87
> [master/chatbot] Updates bot build to include small fixes

- updateCli/updateCli.d/charts/stable-nginx-ingress.tpl
> Update nginx-ingress message

- helmfile.d/falco.yaml
- updateCli/updateCli.d/charts/stable-falco.tpl
Signed-off-by: markyjackson-taulia <marky.r.jackson@gmail.com>
> Correct part for chart

- README.md
Improve README readability
Documentation change only.  No other checklist items required.
> Show code examples as code in README

- PodTemplates.yaml
Manually bumping the version as the version v0.0.15 is totally broken
> Manually update updatecli version to v0.0.16

- config/default/jenkins-release.yaml
Define 'jenkins.branch.NoTriggerBranchProperty'
> [INFRA-2674] Set notriggerbranchproperty for release.ci

- charts/plugin-site/Chart.yaml
- charts/plugin-site/values.yaml
Reverts jenkins-infra/charts#364
> Revert "[stable/plugins-site] Manual bump of plugin-site-api docker image since its not yet semver docker names"

- charts/reports/templates/nginx-configmap.yaml
> [stable/reports] Add CORS for www.jenkins.io 

- charts/jenkins-wiki-exporter/values.yaml
See https://groups.google.com/forum/#!topic/jenkins-infra/Fr-NLmVt_kE
> Double the ram allowed for the wiki exporter

- charts/mirrorbits/README.md
- charts/mirrorbits/templates/configmap.files.yaml
The purpose of this is to first see the last version instead of the newest
> Add  IndexOrderDefault Descending Name to mirrrobits

- charts/jenkins-wiki-exporter/templates/deployment.yaml
- charts/jenkins-wiki-exporter/templates/secret.yaml
- charts/jenkins-wiki-exporter/values.yaml
https://github.com/jenkins-infra/charts-secrets/pull/4
> Adds sentry dsn for jenkins-wiki-exporter

- charts/jenkins/values.yaml
- config/default/jenkins-infra.yaml
* install plugins for infra
* add jobdsl for building tags
> Add plugins

- config/default/jenkins-infra.yaml
Hopefully the proper jobdsl to make master and tags build
> Hopefully the proper jobdsl to make master and tags build

- charts/jenkins/values.yaml
- config/default/jenkins-infra.yaml
* Okay working and tested locally version of jobdsl that builds master and tags
* Add in basic-branch-build-strategies so we can target branches and tags
* Sort the plugin list
> [infra.ci.jenkins.io] - Nice jobdsl and fixes to build master and tags

- charts/custom-distribution-service/.helmignore
- charts/custom-distribution-service/Chart.yaml
- charts/custom-distribution-service/templates/NOTES.txt
- charts/custom-distribution-service/templates/_helpers.tpl
- charts/custom-distribution-service/templates/deployment.yaml
- charts/custom-distribution-service/templates/ingress.yaml
- charts/custom-distribution-service/templates/service.yaml
- charts/custom-distribution-service/templates/serviceaccount.yaml
- charts/custom-distribution-service/templates/tests/test-connection.yaml
- charts/custom-distribution-service/values.yaml
- config/default/custom-distribution-service.yml
- config/default/jenkins-infra.yaml
No Secrets
Codeowners isn't updated this PR, just want to make sure everything works
fixes # [INFRA-2700](https://issues.jenkins-ci.org/projects/INFRA/issues/INFRA-2700)
> Custom distribution service

- charts/custom-distribution-service/values.yaml
- config/default/custom-distribution-service.yaml
> bump version of custom distrubition service

- config/default/custom-distribution-service.yaml
> Remove rewrite target. Not sure why i added it in the first place

- .sops.yaml
- CODEOWNERS
- charts/incrementals-publisher/.helmignore
- charts/incrementals-publisher/Chart.yaml
- charts/incrementals-publisher/README.md
- charts/incrementals-publisher/templates/NOTES.txt
- charts/incrementals-publisher/templates/_helpers.tpl
- charts/incrementals-publisher/templates/deployment.yaml
- charts/incrementals-publisher/templates/ingress.yaml
- charts/incrementals-publisher/templates/secret.yaml
- charts/incrementals-publisher/templates/service.yaml
- charts/incrementals-publisher/templates/serviceaccount.yaml
- charts/incrementals-publisher/templates/tests/test-connection.yaml
- charts/incrementals-publisher/values.yaml
- config/default/incrementals-publisher.yaml
- helmfile.d/incrementals-publisher.yaml
> [incrementals-publisher] Add Incrementals.jenkins.io

- clusters/publick8s.yaml
> [incrementals-publisher] Add incrementals publisher to public cluster

- helmfile.d/cert-manager.yaml
Reverts jenkins-infra/charts#468
Fixed it
> Revert "Revert "[updatecli] Update jetstack/cert-manager Helm Chart version to v1.0.1""

- charts/acme/templates/clusterIssuer.yaml
- charts/ldap/templates/certificate.yaml
> Update cert-manager api versions

- updateCli/updateCli.d/custom-distribution-service.tpl
> Update template to be [custom-distribution-service] Update appVersion

- updateCli/updateCli.d/incrementals-publisher.tpl
> Fix template to be "[incrementals-publisher] Update appVersion"

- updateCli/updateCli.d/custom-distribution-service.tpl
- updateCli/updateCli.d/incrementals-publisher.tpl
Fixes 
09:04 <halkeye> error: refusing to create funny ref 'refs/heads/updatecli/[incrementals-publisher]UpdateappVersion/v1.2.0' remotely
09:04 <halkeye> command error on refs/heads/updatecli/[incrementals-publisher]UpdateappVersion/v1.2.0: funny refname
> Better template names for incrementals and customize

- charts/chatbot/values.yaml
This updates the IRC bot to have the latest fixes for hosting checking.
> [master/chatbot] Update to latest build with fixes for host checking

- updateCli/updateCli.d/charts/stable-jenkins.tpl
> Update updatecli source

- helmfile.d/prometheus.yaml
- updateCli/updateCli.d/charts/prometheus.tpl
- fixes # [INFRA-2746](https://issues.jenkins-ci.org/projects/INFRA/issues/INFRA-2746)
> [INFRA-2746] Update prometheus helm chart repository

- helmfile.d/grafana.yaml
- updateCli/updateCli.d/charts/grafana.tpl
- fixes # [INFRA-2750](https://issues.jenkins-ci.org/projects/INFRA/issues/INFRA-2750)
Same helm chart than https://github,com/helm/charrts
> [INFRA-2750] Update grafana helm chart repository

- helmfile.d/datadog.yaml
- updateCli/updateCli.d/charts/datadog.tpl
- fixes # [INFRA-2747](https://issues.jenkins-ci.org/projects/INFRA/issues/INFRA-2747)
> [INFRA-2747] Update datadog helm repository

- config/default/jenkins-infra.yaml
> chore: add docker-packer build

- config/default/ldap.yaml
Signed-off-by: Anton Baranov <abaranov@linuxfoundation.org>
> Authorize ldap from Linux Foundation production jira machine

- charts/chatbot/templates/deployment.yaml
Add checksum annotation to force a pod restart if the secret is modified
> Add secret checksum to chatbot deployment

- config/default/jenkins-infra.yaml
> chore: add the docker-datadog build

- config/default/datadog.yaml
> chore: use our own datadog agent image

- updateCli/updateCli.d/datadog.tpl
> Fix typo in updatecli datadog image name

- config/default/jenkins-infra.yaml
> chore: add the experiment-aws build

- config/default/jenkins-infra.yaml
> fix: bad indentation stopping server from starting

- config/default/jenkins-infra.yaml
> chore: rename experiment-aws to aws

- Jenkinsfile_k8s
- Makefile
- PodTemplates.yaml
- config/default/accountapp.yaml
- config/default/archives.yaml
- config/default/datadog.yaml
- config/default/falco.yaml
- config/default/grafana.yaml
- config/default/javadoc.yaml
- config/default/jenkins-infra.yaml
- config/default/jenkins-release.yaml
- config/default/jenkinsio.yaml
- config/default/ldap.yaml
- config/default/loki.yaml
- config/default/mirror.yaml
- config/default/mirrorbits.yaml
- config/default/oauth2-proxy.yaml
- config/default/pkg.yaml
- config/default/polls.yaml
- config/default/reports.yaml
- yamllint.config
next steps:
- enable a PR build for this repo
- ensure this is being validated for each build
- enable some extra checks e.g. indentation
> chore: yamllint configuration

- config/default/jenkins-infra.yaml
Add a new multibranch pipeline for repository jenkins-infra/docker-terraform
- step of [INFRA-2849](https://issues.jenkins-ci.org/projects/INFRA/issues/INFRA-2849)
Enable CI for https://github.com/jenkins-infra/docker-terraform.
> Add a new multibranch pipeline for repository jenkins-infra/docker-terraform

- config/default/jenkins-infra.yaml
> fix: correct ingress for jenkins-infra

- charts/chatbot/values.yaml
This updates the bot to include some fixes for hosting features like using GH issues instead of Jira if desired
> [stable/chatbot] Update to build with new hosting features

- config/default/jenkins-infra.yaml
> chore: on jenkins-infra/charts only build branches that are PRs

- config/default/jenkins-release.yaml
This PR configure release.ci to also build release candidates.
It requires this [PR](https://github.com/jenkins-infra/release/pull/118) to be merged first
> Add stable-rc job to release.ci

- config/default/jenkins-release.yaml
> Allow every branches for stable-rc job on release.ci

- charts/jenkins/values.yaml
This plugin will enable us to programatically comment on PRs.
> chore: add pipeline-github plugin to jenkins

- Jenkinsfile_k8s
This PR runs a number of extra checks during the PR phase of the pipeline. It will also comment back on the PR showing the diff that will be applied to the cluster.
> feat: enable more tests on PR builds

- charts/mirror/values.yaml
- updateCli/updateCli.d/mirror-rsyncd.tpl
Add updatecli configuration to automatically bump the docker image digest
> Add updatecli configuration rsyncd docker image

- updateCli/updateCli.d/mirror-rsyncd.tpl
Fix docker image name in updatecli config
> Fix updatecli config

- charts/jenkins/values.yaml
- config/default/jenkins-infra.yaml
this trait allows tags to be discovered correcly
> chore: change the scm filter trait to one that handles tags

- clusters/publick8s.yaml
- helmfile.d/promtail.yaml
I manually redeployed the service and loki is back to normal
> Reenable loki

- charts/mirrorbits/README.md
Add documentation to disable a mirror
> Documentation on how to disable a mirror

- charts/mirrorbits/README.md
Belgium represent!
This pull request had instruction to (re)enable Belnet to our Mirrorbits configuration
> Add belnet mirror instruction

- .sops.yaml
This sops file was used to generate https://github.com/jenkins-infra/charts-secrets/pull/15
> Add dduportal/mwaite/gevans to sops

- charts/chatbot/values.yaml
Updates to ircbot version with some fixes for RPU PRs
> Update ircbot version

- config/default/jenkins-infra.yaml
> Infra-CI: Fix File Credentials to use base64 encoding

- config/default/keycloak.yaml
This represent settings that I manually deployed according the changes coming from the keycloak helm chart.
Secrets format also changed.
> Update keycloak config according new helm chart settings

- clusters/publick8s.yaml
-_-
Considering the version bump from 10.* to 12.*, it will be safer to first test the upgrade
> Add keycloak to publick8s

- config/default/jenkins-infra.yaml
> Jenkins-Infra: add kubeconfig credential

- config/default/jenkins-infra.yaml
> [INFRA-2891] Infra.CI: Add EKS IAM credentials for eks_charter

- config/default/ldap.yaml
> Update trusted.ci VM IP to allow incoming LDAP connection

- charts/jenkins-kubernetes-agents/.helmignore
- charts/jenkins-kubernetes-agents/Chart.yaml
- charts/jenkins-kubernetes-agents/templates/serviceaccount.yaml
- clusters/cik8s.yaml
- helmfile.d/jenkins-agents.yaml
> [INFRA-2919] Feat: add a custom chart to define jenkins agent resources for cik8s

- Jenkinsfile_k8s
- PodTemplates.yaml
- config/default/jenkins-infra.yaml
The goal of this PR is to improve the pipeline of this repository on the following elements:
* Performance: Decrease the overall time of a full pipeline run
* Reliability: Avoid getting the errors `Timed out waiting for websocket connection. You should increase the value of system property org.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecDecorator.websocketConnectionTimeout currently set at 30 seconds`
and 
`wrapper script does not seem to be touching the log file in <...> (JENKINS-48300: if on an extremely laggy filesystem, consider -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=86400)
`
when a lot of pipeline runs are running simultaneously (ref. https://support.cloudbees.com/hc/en-us/articles/360054642231-Considerations-for-Kubernetes-Clients …
> Improve Pipeline Execution Performance 

- updateCli/updateCli.d/jenkins-weekly-jdk11.tpl
Couldn't work out why it wasn't updating!
> fix: typo in updatecli config

- config/default/jenkins-infra.yaml
> fix: switch infra-ci to full websockets for kubernetes agents

- config/default/jenkins-release.yaml
brings the config inline with changes made on the UI
> chore: switch release.ci over to use websocket config

- config/default/captain-hook.yaml
- config/default/jenkins-release.yaml
Just to pass the yamllint tests
> Fix various linting issues

- charts/chatbot/values.yaml
This updates to the latest build of the ircbot with some small fixes and changes.
> Update to latest version of ircbot with small fixes

- charts/plugin-site/templates/nginx-configmap.yaml
> Dont try and read / which since it cant auto index, will give 403

- config/default/jenkins-infra.yaml
I would like to start building jenkins.io docker image from this directory
> Add jenkins-infra/jenkins.io to infra.ci

- updateCli/updateCli.d/nginx.tpl
> Fix nginx updatecli configuration

- config/default/jenkins-infra.yaml
> [INFRA-2904] Jenkins Infra: add EC2 agents credentials

- PodTemplates.yaml
Reduce out of memory failures during www.jenkins.io deploy as seen in checks for master branch recently.
> 3x increase helmfile container memory request

- charts/mirrorbits/templates/deployment.yaml
> hotfix: disable temporarly the mirrorbit-cron container

- helmfile.d/nginx-ingress.tmp.yaml
> Hotfix: increase timeout of tmp-nginx-ingress to allow initial install

- config/default/jenkins-infra.yaml
This PR is a follow up of #1124 , to apply @olblak suggestions.
Only syntax refinement: no changes visible
> Chore: infra.ci JobDSL config refinement

- helmfile.d/nginx-ingress.yaml
> INFRA-2743: Upgrade nginx ingress (new chart + new version)

- charts/plugin-site/values.yaml
https://github.com/jenkins-infra/plugin-site-api/releases/tag/plugin-site-api-1.12.0
> Deploy new plugin-site-api - v1.12.0

- charts/chatbot/values.yaml
Discussed in https://groups.google.com/g/jenkinsci-dev/c/pEcun5ZSfgo/m/ztRg03VNAgAJ.
Deploys the changes from https://github.com/jenkins-infra/ircbot/pull/100 to production.
> feat: Switches ircbot to Libera Chat

- config/default/jenkins-infra.yaml
until https://…github.com/jenkinsci/workflow-basic-steps-plugin/pull/144 is merged
> feat: allow some methods on infra.ci to implement retryWithTimeout

- config/default/jenkins-infra.yaml
- config/default/jenkins-release.yaml
Ref. 
- https://github.com/jenkins-infra/docker-jenkins-weekly/pull/204
- https://support.cloudbees.com/hc/en-us/articles/216973327
> feat: ensure that weather is disabled on infra. and release.ci

- charts/plugin-site/values.yaml
https://github.com/jenkins-infra/plugin-site-api/pull/102
> update plugin-site-api version - 217-bbeca3

- config/default/keycloak.yaml
Update ingress path configuration structure.
This should fix the helmfile linting issues
> Update keycloak ingress path

- charts/plugin-site/values.yaml
Downstream of https://github.com/jenkins-infra/plugin-site-api/pull/103
> Update plugins site to latest

- config/default/loki.yaml
The Loki pod is running out of space.
I am not sure yet if it support live resizing
> Increase loki storage

- config/default/jenkinsio.yaml
> feat: define X-Frame-Options header for jenkins.io website [INFRA-2998]

- clusters/publick8s.yaml
> feat(release.ci.j) manage with helmfile again

- Jenkinsfile_k8s
- README.md
- REVIEW_GUIDELINES.md
- config/publick8s/grafana.yaml
- updatecli/values.yaml
> chore: replace branch 'master' with 'main'

- config/accountapp.yaml
The PR #1667  is responsible for #1676 which would break the installation:
<details><summary>Click to expand</summary>
```diff
Comparing release=accountapp, chart=jenkins-infra/accountapp
accountapp, accountapp, Deployment (apps) has changed:
apiVersion: apps/v1
kind: Deployment
metadata:
name: accountapp
labels: 
app.kubernetes.io/name: accountapp
-     helm.sh/chart: accountapp-0.0.1
+     helm.sh/chart: accountapp-0.1.0
app.kubernetes.io/instance: accountapp
-     app.kubernetes.io/version: "1.0"
app.kubernetes.io/managed-by: Helm
jenkins.io/maintainer: timja
spec:
replicas: 2
selector:
matchLabels:
app.kubernetes.io/name: accountapp
app.kubernetes.io/instance: accountapp
template:
metadata:
labels: 
app.kubernetes.io/name: accountapp
-         helm.sh/chart: accountapp-0.0.1
+ …
```
> fix(accountapp) specify the Docker image tag and pullpolicy to allow chart upgrade

- updatecli/updatecli.d/charts/acme.yaml
- updatecli/updatecli.d/charts/certmanager.yaml
- updatecli/updatecli.d/docker-images/custom-distribution-service.yaml
> chore(updatecli) manage acme and cert-manager chart updates

- config/chatbot.yaml
- updatecli/updatecli.d/charts/chatbot.yaml
Please note that the Docker image tag will be managed in #1681
> chore(updatecli) manage chatbot chart updates

- config/wiki.yaml
Once this is merged, I'll remove the DNS entries manually from Azure DNS.
> feat(wiki) Remove the "wiki-test.jenkins*" DNS entries

- CONTRIBUTING.md
Closes #1695 . Thanks @halkeye ❤️
> Update CONTRIBUTING.md for contributing channels

- PodTemplates.yaml
Reverts jenkins-infra/charts#1657
> Revert "[updatecli] Bump jenkins-infra helmfile docker image"

- clusters/publick8s.yaml
Ref. https://github.com/jenkinsci/helm-charts/pull/507
> feat: trying out new security context for jenkins helm chart before its release: https://github.com/jenkinsci/helm-charts/pull/507

- .sops.yaml
- CODEOWNERS
- clusters/publick8s.yaml
- config/plugin-site-issues.yaml
https://github.com/jenkins-infra/public-charts/pull/31
https://github.com/jenkins-infra/charts-secrets/pull/20
https://github.com/jenkins-infra/charts/pull/1790
> feat: add plugin-site-issues chart

- config/keycloak.yaml
- https://twitter.com/keycloak/status/1471815630655528968
- https://github.com/keycloak/keycloak/commit/d9d0bfb218865ed05011957cbcc926fd415bcefe
> feat(keycloak) force-bump image to 15.1.1 - 

- config/jenkins-infra.yaml
timja already added it to secrets in cc5519d
> Add NETLIFY_AUTH_TOKEN

- clusters/temp-privatek8s.yaml
- config/temp-privatek8s/private-nginx-ingress.yaml
- updatecli/updatecli.d/charts/nginx-ingress.yaml
- Installed manually first
- does not include cert-manager (yet)
- Routing is allowed on the (current) VPN VM https://github.com/jenkins-infra/jenkins-infra/commit/81bed457ae2a9eb8b4e6c42897c18311fdfd3d72
> feat(temp-privatek8s) add a private ingress controller

- clusters/prodpublick8s.yaml
- clusters/temp-privatek8s.yaml
- config/NOTES.txt
- updatecli/updatecli.d/pod-templates/helmfile.yaml
This PR also import code review feedback (https://github.com/jenkins-infra/kubernetes-management/pull/1890/files/98f345e35f7a4e35fc6c773a1eb131df377545a0#diff-b6df0d3f06b5802f9f8ce0ee5fda97a45e448ecf41b9f640ea129f96ef0a357d) and fix an updatecli manifest
The goal is to fix the build :)
> Fix: correct missing ext prefix

- .sops.yaml
The repo with secrets had also been updated (allowed my Public IP on Azure Vault, ran `for f in $(find ./secrets/config -type f ); do echo "==$f"; sops updatekeys "$f" -y;done` and committed changes).
> allow smerle33 to decrypt secrets

- config/ext_jenkins-infra.yaml
> Allow untrusted builds for jenkins.io and plugin site (which have safe pipelines)

- config/ext_jenkins-release.yaml
Closes https://github.com/jenkins-infra/helpdesk/issues/2746
> feat(infra.ci.jenkins.io) add agent VM templates for Linux and Windows as amazon ec2 instances

- config/ext_jenkins-infra.yaml
Part of https://github.com/jenkins-infra/helpdesk/issues/2651
Related to https://github.com/jenkins-infra/digitalocean/pull/1
> feat: add Digital Ocean job to infra.ci

- config/ext_jenkins-infra.yaml
Followup of https://github.com/jenkins-infra/charts-secrets/pull/23
Part of https://github.com/jenkins-infra/helpdesk/issues/2651
> feat: add Digital Ocean secrets

- Jenkinsfile_k8s
- updatecli/updatecli.d/charts/jenkins-agents-infra-release.yaml
cannot find the issue, but the aim is to automate update of AMI from the new images from packer-images
> (feat infra) adding the update of AMI images with updatecli from packer-images

- clusters/temp-privatek8s.yaml
- config/ext_jenkins-infra.yaml
- updatecli/updatecli.d/charts/jenkins.yaml
- Secrets are now managed by the jenkins/jenkins (instead of jenkins-additional)
- Bumped jenkins-additiona to 0.0.3
- Bumped the chart jenkins/jenkins to latest stable + track it with updatecli
> Fix(infra.ci) Correct secrets management

- config/ext_jenkins-infra.yaml
Ref.  https://github.com/jenkinsci/helm-charts/blob/4162f5a6aa39e5732f7fe89e8a7cba09179eccbe/charts/jenkins/README.md\#long-volume-attachmount-times
> feat(infra.ci) fine tune volume mount for azure

- config/ext_jenkins-infra.yaml
> chore: remove extra args

- .sops.yaml
- clusters/cik8s.yaml
- config/ext_autoscaler.yaml
> fix(autoscaler) use the updated node labels + bump jenkins-agent helm charts

- clusters/prodpublick8s.yaml
- updatecli/updatecli.d/charts/jenkins.yaml
Reverts jenkins-infra/kubernetes-management#2014
> Revert "disable release.ci auto-management for the sec release of 2022-02-15"

- config/ext_jenkins-infra.yaml
Part of jenkins-infra/helpdesk#2651
> chore: add KUBECONFIG_DOKS credential

- Jenkinsfile_k8s
- PodTemplates.yaml
- clusters/doks.yaml
- updatecli/updatecli.d/charts/jenkins-kubernetes-agent.yaml
Part of https://github.com/jenkins-infra/helpdesk/issues/2651
> feat: add helmfile for Digital Ocean cluster

- updatecli/updatecli.d/charts/jenkins-kubernetes-agent.yaml
> chore: restore commented out updatecli manifest for doks

- config/ext_jenkins-infra.yaml
> fix(infra.ci) correct datadog credential secret reference

- clusters/doks.yaml
- config/ext_doks-datadog.yaml
- updatecli/updatecli.d/charts/datadog.yaml
Part of https://github.com/jenkins-infra/helpdesk/issues/2651
> chore: add datadog to Digital Ocean cluster

- config/ext_jenkins-infra.yaml
https://github.com/jenkins-infra/helpdesk/issues/2803#issuecomment-1058272244
> debug(infra.ci) bisect cron trigger bug by rollbacking to a previous version (0.43.0-2.336)

- Jenkinsfile_k8s
- config/ext_jenkins-infra.yaml
Part of https://github.com/jenkins-infra/helpdesk/issues/2817
> feat: add jenkins-infra-updatecli Github App credential

- config/ext_jenkins-infra.yaml
add an azure Service Principal credential to use within packer (and the GC for azure)
> add an azure serviceprincipal for packer

- config/ext_jenkins-infra.yaml
> fix(infra.ci) use the correct ID for terraform-azure credentials

- config/ext_jenkins-infra.yaml
Part of https://github.com/jenkins-infra/helpdesk/issues/2820
> feat: add Fastly backend config file and API key secrets

- config/ext_jenkins-infra.yaml
Part of https://github.com/jenkins-infra/helpdesk/issues/2820
> feat: add Fastly job to infra.ci.jenkins.io

- config/ext_jenkins-infra.yaml
Part of https://github.com/jenkins-infra/helpdesk/issues/2852
> feat: add infracost API key secret

- config/ext_jenkins-infra.yaml
as per jenkins-infra/helpdesk#2837
> feat(infra.ci): new tokens for dockerhub push and pull infraci

- README.md
I am not sure for the wording but I feel that a little more explanation would save some time to other ....
> chore(readme): update proposal for readme

- config/ext_jenkins-infra.yaml
Interesting bits from https://github.com/jenkins-infra/kubernetes-management/pull/2161 for infra.ci.jenkins.io
> chore: java options as multilines and jenkins-infra-team mail

- config/ext_jenkins-infra-jobs.yaml
> fix(infra.ci) disable github checks for infra-reports jobs

- config/ext_jenkins-weekly.yaml
Ref: https://github.com/jenkins-infra/helpdesk/issues/2855#issuecomment-1090076100
> fix: add authenticated rights

- config/ext_jenkins-weekly.yaml
Ref: https://github.com/jenkins-infra/helpdesk/issues/2855#issuecomment-1090138994
Credits: @NotMyFault (thanks!)
Closes https://github.com/jenkins-infra/helpdesk/issues/2855
> fix: proper weekly.ci.jenkins.io description

- config/ext_jenkins-infra-jobs.yaml
> fix(infra.ci) correct required ghapp credentials for infra-reports

- .github/workflows/delete-unmerged-branch.yaml
From https://github.com/asaaki/gha-delete-unmerged-branches
> feat: GHA to delete unmerged branch

- Jenkinsfile_k8s
Related to https://github.com/jenkins-infra/helpdesk/issues/2866.
> feat(doks) enable DOKS cluster again

- README.md
- clusters/prodpublick8s.yaml
- config/rating.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/1627 
add a release for rating with corresponding secrets.yaml
> feat(rating): new release for rating

- clusters/prodpublick8s.yaml
- config/jenkinsisthewayio.yaml
as per : https://github.com/jenkins-infra/helpdesk/issues/2943
setting a redirection for jenkinsistheway.io to stories.jenkins.io
> feat(redirection): add jenkinsistheway.io redirection to stories.jenkins.io

- clusters/prodpublick8s.yaml
- config/jenkinsisthewayio.yaml
- updatecli/updatecli.d/charts/jenkinsisthewayio.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/2943
new chart with ingressClassName 
add updatecli yaml to bump the chart version
> fix(jenkinsistheway redirection): use new chart and add dependencie

- config/ext_jenkins-infra.yaml
Ref: https://github.com/jenkins-infra/helpdesk/issues/2873
> feat: use Jenkins Infra inbound-agent Windows Docker image

- config/ext_jenkins-infra.yaml
- Avoid scheduling on Windows (and trashing the PVC :'( ) 
- Fix the imagepullpolicy for faster restarts
> hotfix infra.ci

- config/ext_jenkins-release.yaml
Ref: https://github.com/jenkins-infra/helpdesk/issues/2873
Related:
- https://github.com/jenkins-infra/kubernetes-management/pull/2404
- https://github.com/jenkins-infra/kubernetes-management/pull/2434
> feat(release): use Jenkins Infra inbound-agent Windows Docker image

- clusters/cik8s.yaml
- clusters/doks.yaml
- clusters/prodpublick8s.yaml
Reverts jenkins-infra/kubernetes-management#2479
> Revert "[updatecli] Bump datadog helm chart"

- config/ext_jenkins-infra.yaml
- config/ext_jenkins-release.yaml
- config/ext_jenkins-weekly.yaml
Fixes https://github.com/jenkins-infra/helpdesk/issues/2990
> feat: enable timestamper on all pipelines

- clusters/prodpublick8s.yaml
- config/mirrorbits.yaml
https://github.com/Azure/AKS/issues/2871
Changes applied manually, tested with an helmfile diff: no changes as expected
> hotfix(ldap,mirrorbits) specify secretNamespace for PVs using azurefile

- clusters/prodpublick8s.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/3037
> hotfix(prodpublick8s) correct configuration shift due to manual operation for jenkins-infra/helpdesk#3037

- config/ext_jenkins-infra-jobs.yaml
Ref: https://github.com/jenkins-infra/helpdesk/issues/1323
Secret added in jenkins-infra/chart-secrets
> feat(datadog): add datadog-jenkinsuser-password credential

- config/ext_jenkins-infra-jobs.yaml
Needed for https://github.com/jenkins-infra/packer-images/pull/287
> chore: add jenkinsinfraadmin-dockerhub-push credential to packer-images jobs

- config/ldap.yaml
> fix(ldap) increase resource limits for LDAP pod + align request with limit - trying to avoid OOMs

- config/ext_jenkins-infra-jobs.yaml
Part of https://github.com/jenkins-infra/kubernetes-management/issues/1668
Context: https://github.com/jenkins-infra/account-app/pull/136#event-7205302072
> feat(infra.ci) build account-app docker image

- updatecli/updatecli.d/docker-images/accountapp.yaml
> chore: add account-app docker image updatecli manifest

- config/ext_jenkins-infra-jobs.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/3084
> fix(infra.ci) correct jobs configuration for the ATH docker image

- clusters/prodpublick8s.yaml
- config/nginx-proxy-azure.yaml
Note: I've added the "repo.azure" CNAME record pointing to public.aks.jenkins.io in Azure Portal.
> feat: nginx-proxy-azure in prodpublick8s

- clusters/cik8s.yaml
Reverts jenkins-infra/kubernetes-management#2751
Ref. https://github.com/jenkins-infra/helpdesk/issues/3110
> Revert "[updatecli] Bump autoscaler helm chart version"

- README.md
> doc(README) update helmfile project links to the new project home

- clusters/prodpublick8s.yaml
Reverts jenkins-infra/kubernetes-management#2772
> Revert "chore(nginx-proxy): try again with `deployment` (v0.2.2)"

- Jenkinsfile_k8s
> fixup: use a shell command to determine if a cluster definition has changed

- Jenkinsfile_k8s
- PodTemplates.yaml
- config/accountapp.yaml
- config/ext_jenkins-infra.yaml
- config/ext_jenkins-weekly.yaml
> chore(regroup-pr): update dependencies

- config/ext_public-nginx-ingress_doks.yaml
> chore: use external load balancer

- config/artifact-caching-proxy-azure.yaml
- config/artifact-caching-proxy-do.yaml
Keep only the basic auth, see https://github.com/jenkins-infra/helpdesk/issues/2752\#issuecomment-1246539366
> chore(artifact-caching-proxy): remove IP whitelisting

- config/ext_jenkins-infra-jobs.yaml
Ref: https://github.com/jenkins-infra/helpdesk/issues/3114
> feat: add plugin-health-scoring Docker build on infra.ci.jenkins.io

- config/ext_jenkins-infra-jobs.yaml
- updatecli/updatecli.d/charts/artifact-caching-proxy.yaml
- updatecli/updatecli.d/charts/nginx-ingress.yaml
Needed for https://github.com/jenkins-infra/kubernetes-management/pull/2905
> chore: add kubeconfig-doks-public credentials

- config/ext_jenkins-infra-jobs.yaml
Reverts jenkins-infra/kubernetes-management#2900
> Revert "Revert "fixup: correct Jenkinsfile path for plugin-health-scoring""

- clusters/prodpublick8s.yaml
- config/plugin-health-scoring.yaml
- updatecli/updatecli.d/charts/plugin-health-scoring.yaml
- updatecli/updatecli.d/docker-images/plugin-health-scoring.yaml
Ref: https://github.com/jenkins-infra/helpdesk/issues/3114
> feat: deploy plugin-health-scoring on prodpublick8s

- .github/workflows/pr-updater
Use https://github.com/maxkomarychev/pr-updater-action
> feat: add `pr-updater` GitHub Action to sync PRs on main push

- updatecli/updatecli.d/charts/jenkins-agents-infra.ci.jenkins.io.yaml
Fix https://github.com/jenkins-infra/kubernetes-management/pull/2951
> Revert from dependson to depends_on

- config/ext_jenkins-infra-jobs.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/3087
> feat(infra.ci) add jobs for backend-extension-indexer and pipeline-steps-doc-generator as part of jenkins-infra/helpdesk#3087

- clusters/eks-public.yaml
> feat(eks-public) use new cluster name: public-mint-ape

- clusters/eks-public.yaml
- config/ext_aws-node-termination-handler_eks-public.yaml
> fix(eks-public) correct remaining configs

- Jenkinsfile_k8s
Reverts jenkins-infra/kubernetes-management#3041
> Revert "chore: temporary disable kubernetes-management job on `eks-public` cluster"

- PodTemplates.yaml
- config/ext_jenkins-infra.yaml
> hotfix(infra.ci) nodepools

- config/ext_public-nginx-ingress_eks-public.yaml
> hotfix(eks-public) specify subnet and eip for the Nginx Ingress Public LB (to keep the same IP over time)

- config/ext_public-nginx-ingress_eks-public.yaml
Related to https://github.com/jenkins-infra/aws/pull/281
> hotfix(eks-public) use the 3 AZs for the ingress public LB

- clusters/prodpublick8s.yaml
- config/rss2twitter.yaml
- updatecli/updatecli.d/charts/rss2twitter.yaml
Configured in dry mode for now.
Ref: https://github.com/jenkins-infra/helpdesk/issues/3085
> feat: deploy `rss2twitter` service on `prodpublick8s`

- clusters/prodpublick8s.yaml
Follow-up of #3113 with https://github.com/jenkins-infra/helm-charts/pull/282
> fixup: bump `rss2twitter` to fixed version

- config/ext_datadog_publick8s.yaml
- config/ext_datadog_temp-privatek8s.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/3123#issuecomment-1304004166
> fix(datadog-AKS) disable tlsVerify to contact the kubelet

- config/ext_jenkins-infra.yaml
> fix(infra.ci): add command for new node agent

- config/ext_jenkins-infra-jobs.yaml
> feat: add privatek8s kubeconfig credentials in kubernetes-management job

- clusters/prodpublick8s.yaml
- clusters/temp-privatek8s.yaml
- config/ext_private-nginx-ingress__common.yaml
- config/ext_private-nginx-ingress_prodpublick8s.yaml
- config/ext_private-nginx-ingress_temp-privatek8s.yaml
- config/ext_public-nginx-ingress_prodpublick8s.yaml
- config/ext_public-nginx-ingress_temp-privatek8s.yaml
- updatecli/updatecli.d/docker-images/404.yaml
This pull request factorizes common values for the private and public nginx-ingress services running on all clusters.
Extracted from #3194
> chore: factorize nginx ingresses values

- config/ext_jenkins-infra.yaml
to be compliant with the label in ci.jenkins.io
> chore(infra/agent label): add highmem as a label

- config/ext_jenkins-infra-jobs.yaml
Ref: https://github.com/jenkins-infra/helpdesk/issues/2924
> feat(infra.ci): add `azure-net` job

- config/ext_jenkins-weekly.yaml
> fix(weekly.ci.jenkins.io) fix rbac: `anonymous` is a user, not a group

- CONTRIBUTING.md
- config/acme.yaml
Replace acme email address by the private jenkins infra one #2793
> feat(acme) change default email to `jenkins-infra-team@googlegroups.com`

- config/ext_jenkins-weekly.yaml
Follow-up of #3326
Ref: https://github.com/jenkins-infra/kubernetes-management/issues/3323#issuecomment-1353022203
> fix(weekly.jenkins.io): `anonymous` is a user not a group

- Jenkinsfile_k8s
- clusters/privatek8s.yaml
- clusters/temp-privatek8s.yaml
- config/ext_datadog_privatek8s.yaml
- config/ext_private-nginx-ingress_privatek8s.yaml
- config/ext_public-nginx-ingress_privatek8s.yaml
- updatecli/updatecli.d/charts/acme.yaml
- updatecli/updatecli.d/charts/cert-manager.yaml
- updatecli/updatecli.d/charts/datadog.yaml
- updatecli/updatecli.d/charts/nginx-ingress.yaml
Extracted from #3194, keeping Jenkins infra addition for another PR.
Follow-up of https://github.com/jenkins-infra/azure/pull/248
> feat: add `privatek8s` cluster

- config/ext_jenkins-infra-jobs.yaml
Ref: https://github.com/jenkins-infra/helpdesk/issues/3340
> feat: add jenkins-io-components job

- config/ldap.yaml
> chore(ldap): allow inbound connections from privatek8s

- clusters/prodpublick8s.yaml
> Bump plugin-health-scoring

- config/ext_jenkins-infra__common.yaml
see https://github.com/jenkins-infra/helpdesk/issues/3345 epic
> Upgrade jenkinsinfra builder to latest image

- config/ext_jenkins-infra-jobs.yaml
> feat: add publick8s kubeconfig credentials

- Jenkinsfile_k8s
- clusters/prodpublick8s.yaml
- clusters/publick8s.yaml
- config/ext_datadog_prodpublick8s.yaml
- updatecli/updatecli.d/charts/datadog.yaml
> feat: add `publick8s` cluster (starting with `datadog` chart)

- clusters/publick8s.yaml
- updatecli/updatecli.d/charts/acme.yaml
- updatecli/updatecli.d/charts/cert-manager.yaml
> feat(publick8s): add `cert-manager` and `acme` charts

- clusters/publick8s.yaml
- config/ext_public-nginx-ingress__common.yaml
- config/ext_public-nginx-ingress_publick8s.yaml
- updatecli/updatecli.d/charts/nginx-ingress.yaml
> feat(publick8s): add `public-nginx-ingress`

- clusters/publick8s.yaml
- config/ext_private-nginx-ingress_publick8s.yaml
> feat(publick8s): add `private-nginx-ingress`

- clusters/publick8s.yaml
> feat(publick8s): add `falco`

- clusters/publick8s.yaml
- config/ext_private-nginx-ingress_publick8s.yaml
> fixup(publick8s): correct values for `private-nginx-ingress`

- updatecli/updatecli.d/charts/falco.yaml
> chore(publick8s): track `falco` chart version

- clusters/prodpublick8s.yaml
- clusters/publick8s.yaml
- config/artifact-caching-proxy_azure.yaml
- updatecli/updatecli.d/charts/artifact-caching-proxy.yaml
> feat(publick8s): add `artifact-caching-proxy`

- config/artifact-caching-proxy__common.yaml
> feat(artifact-caching-proxy): set two replicas on every provider

- config/ext_jenkins-infra.yaml
- config/ext_jenkins-release.yaml
- config/ext_jenkins-weekly.yaml
This PR fixes the yamllint-detected indentation issues.
Ping @olblak for info, the 0.44.x line of updatecli breaks the indentation :'(
> chore: fix broken indentation

- config/ext_jenkins-infra-jobs.yaml
https://github.com/jenkins-infra/helpdesk/issues/3435
> Add `gatsby-plugin-jenkins-layout` job to infra.ci.jenkins.io

- updatecli/updatecli.d/charts/github-comment-ops.yaml
- updatecli/updatecli.d/charts/ircbot.yaml
- updatecli/updatecli.d/charts/rss2twitter.yaml
Fixup of https://github.com/jenkins-infra/kubernetes-management/pull/3666
> chore(updatecli) disable temporarly the ircbot, rss2twitter and github-comment-ops manifests

- config/jenkins-kubernetes-agents_cik8s.yaml
Twin of https://github.com/jenkins-infra/jenkins-infra/pull/2704
Related to https://github.com/jenkins-infra/helpdesk/issues/3421#issuecomment-1477559811
>  feat(ci.jenkins.io) decrease the cik8s agent capacity

- clusters/privatek8s.yaml
- updatecli/updatecli.d/charts/env-jenkins-release.yaml
> chore(privatek8s): add env-jenkins-release

- updatecli/updatecli.d/charts/kubernetes-pods-quotas.yaml
Fixup of https://github.com/jenkins-infra/kubernetes-management/pull/3719 where some file where renamed leading to updatecli errors.
> chore(updatecli) fix kubernetes agents quota manifest

- config/ext_jenkins-infra.yaml
start to define azure vm for jenkins-infra, will be completed (for storage account and vm definition)
> feat(azure): add credentials to implement vm in azure from infra.ci

- config/ext_jenkins-infra.yaml
> fix(infra): azure service principal reformat credential jcasc

- config/ext_jenkins-infra.yaml
> feat(infra.ci): ensure azure vm can be spawn

- config/ext_jenkins-infra.yaml
adding the same set of VM to azure than from AWS. 
labels are set as testing purpose for now, will update on another PR
> feat(infra.ci): add AMD64 for ubuntu and windows 2019 VMs

- config/ext_jenkins-infra.yaml
> feat(infra.ci): Azure VM use private IP

- config/ext_jenkins-infra.yaml
- updatecli/updatecli.d/charts/jenkins-agents-infra.ci.jenkins.io.yaml
Ref: https://github.com/jenkins-infra/helpdesk/issues/2982
> feat(infra.ci) bump VM agent Linux images to Ubuntu 22.04

- config/ext_jenkins-release.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3323
> feat(credentials) for gpg and signing cert for 2023 versions

- config/jenkins_infra.ci.jenkins.io.yaml
Ref: https://github.com/jenkins-infra/helpdesk/issues/3501
> chore(acp): add exception for `org.zowe.sdk` Maven repository

- config/jenkins_infra.ci.jenkins.io.yaml
as per #https://github.com/jenkins-infra/helpdesk/issues/3471 and https://github.com/jenkins-infra/packer-images/issues/604
create lockable resources as code.
> feat(infra.ci): add lockable resources for packer

- updatecli/updatecli.d/charts/kubernetes-pods-quotas.yaml
Follow-up of https://github.com/jenkins-infra/jenkins-infra/pull/2770/
Ref: https://github.com/jenkins-infra/helpdesk/issues/3521
> chore(updatecli): add cik8s-bom to kubernetes-pods-quotas.yaml

- updatecli/updatecli.d/charts/kubernetes-pods-quotas.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3521
Follow up of #3888 and https://github.com/jenkins-infra/jenkins-infra/pull/2805
> chore(updatecli) track cik8s-experiments pods quota

- config/jenkins_infra.ci.jenkins.io.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3471
add a ARM64 agent on infra.ci.jenkins.io based on the packer image built https://github.com/jenkins-infra/packer-images/pull/575
> feat(infra.ci): add ARM64 agent as code

- config/jenkins_infra.ci.jenkins.io.yaml
- updatecli/updatecli.d/charts/jenkins-agents-infra.ci.jenkins.io.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3471
removing AWS arm64 vm
> cleanup(infra.ci): remove AWS arm64 vm replaced by azure ones

- config/jenkins_weekly.ci.jenkins.io.yaml
Folllow up to https://github.com/jenkins-infra/kubernetes-management/pull/3933#issuecomment-1546667333
The markup formatter is now configured too. Additionally, I added a failing pipeline and one with a couple of demo steps.
> Add a failing pipeline and configure markupFormatter

- clusters/prodpublick8s.yaml
- clusters/publick8s.yaml
- updatecli/updatecli.d/charts/jenkinsisthewayio.yaml
> chore(jenkinsistheway): migrate from `prodpublick8s` to `publick8s`

- updatecli/updatecli.d/charts/codecentric-keycloak.yaml
Follow up of #3983 (separate PR to keep checks all green)
> chore(updatecli) fix keycloak chart manifest

- Jenkinsfile_updatecli
- updatecli/updatecli.d/charts/jenkins-agents-infra.ci.jenkins.io.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3471
add condition on updating azure gallery
> chore(updatecli): add conditions for azure gallery

- config/jenkins_weekly.ci.jenkins.io.yaml
Displays different headers based on the page you are at.
> Enable context aware headers on weekly.ci

- config/plugin-health-scoring.yaml
This reverts commit ea7a257612c7143322f52076dba13c55868bdb65.
> Revert "hotfix(plugin-health-scoring) update cron patterns for testing init"

- Jenkinsfile_updatecli
as per https://github.com/jenkins-infra/helpdesk/issues/3471 cleaning all AWS EC2 remants
> chore(updatecli): remove AWS environment variables

- clusters/prodpublick8s.yaml
- clusters/publick8s.yaml
- updatecli/updatecli.d/charts/incrementals-publisher.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1564632990
Please note this PR embeds the `updatecli` manifest update: it means the "Check Configuration Update" check will fail until merged
> feat(publick8s) migrate increemental publisher

- config/jenkins_weekly.ci.jenkins.io.yaml
Reverts jenkins-infra/kubernetes-management#3996
> Revert "Revert "Enable context aware headers on weekly.ci""

- clusters/prodpublick8s.yaml
- clusters/publick8s.yaml
- updatecli/updatecli.d/charts/uplink.yaml
> feat(publick8s) migrate uplink.jenkins.io

- config/ldap.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3613
> fix(ldap) update the puppet.jenkins.io IP

- clusters/prodpublick8s.yaml
- clusters/publick8s.yaml
- config/accountapp.yaml
- updatecli/updatecli.d/charts/accountapp.yaml
In draft until 13:00 UTC (cf https://github.com/jenkins-infra/status/pull/301)
> chore(accountapp): migrate from `prodpublick8s` to `publick8s`

- config/javadoc.yaml
wait for https://github.com/jenkins-infra/azure/pull/390 and then merge to move javadoc to arm
> chore(publick8s): move javadoc to arm node pool

- Jenkinsfile_k8s
https://github.com/jenkins-infra/helpdesk/issues/3582
> feat: disable management of cik8s and eks-public

- Jenkinsfile_k8s
Reverts jenkins-infra/kubernetes-management#4135
Ref. https://github.com/jenkins-infra/helpdesk/issues/3582#issuecomment-1603056198
> Revert "feat: disable management of cik8s and eks-public"

- Jenkinsfile_k8s
https://github.com/jenkins-infra/helpdesk/issues/3582#issuecomment-1625011472
> disable AKS management for 1.25 upgrades

- Jenkinsfile_k8s
Reverts jenkins-infra/kubernetes-management#4149
> Revert "disable AKS management for 1.25 upgrades"

- updatecli/updatecli.d/charts/kubernetes-pods-quotas.yaml
Follow-up of https://github.com/jenkins-infra/jenkins-infra/pull/2950
> chore(updatecli): correct `conditions.spec.file` in kubernetes-pods-quotas.yaml

- config/jenkinsio.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3619#issue-1745920424
> feat(jenkins.io): migrate to arm64 nodepool

- clusters/publick8s.yaml
- config/uc-r2.yaml
- config/updates.jenkins.io.yaml
This PR adds an experimental `updates-jenkins-io` service on publick8s cluster
Ref: https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-1660258021
> feat: add `updates-jenkins-io` service to `publick8s` cluster

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
More leftovers caught while working on https://github.com/jenkins-infra/helpdesk/issues/3679
> cleanup(infra.ci.jenkins.io) remove unused credentials

- config/jenkins_infra.ci.jenkins.io.yaml
- config/jenkins_release.ci.jenkins.io.yaml
- config/jenkins_weekly.ci.jenkins.io.yaml
see https://plugins.jenkins.io/matrix-auth/releases/
> feat(infra.ci, weekly.ci, release.ci): matrix-auth update conf for breaking change

- config/jenkins_infra.ci.jenkins.io.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3599#issuecomment-1701151279
Twin of https://github.com/jenkins-infra/jenkins-infra/pull/3041
> feat(infra.jenkins.io) add a custom Maven profile in ACP settings to handle plugin repositories

- updatecli/updatecli.d/pod-templates/helmfile.yaml
Ref: https://github.com/jenkins-infra/kubernetes-management/pull/4320#issuecomment-1713183980
> chore(updatecli): fix `helmfile` manifest warning

- config/jenkins_infra.ci.jenkins.io.yaml
- config/jenkins_weekly.ci.jenkins.io.yaml
as per https://github.com/jenkinsci/azure-vm-agents-plugin/releases/tag/883.v63c930b_025dc
⚠️ need to be sync with plugin `azure-vm-agents-plugin` upgrade  ⚠️
> fix(AzureVM): fix breaking change from azure-vm-agents-plugin

- config/wiki.yaml
following https://github.com/jenkins-infra/kubernetes-management/pull/4334
correct the selector
> fix(wiki): change key selector for wiki antiaffinity

- clusters/privatek8s.yaml
- config/jenkins-jobs_infra.ci.jenkins.io.yaml
Requires https://github.com/jenkins-infra/helm-charts/pull/797 to be merged and released
> feat(infra.ci.jenkins.io) disable git tag discovery and build for the updatecli jobs

- config/datadog_confd_checksd.yaml
ref. https://github.com/jenkins-infra/helpdesk/issues/3136\#issuecomment-1733415030
> cleanup(datadog) remove disabled and deleted mirrors (serverion, aliyun and esuni)

- config/javadoc.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3719#issuecomment-1734939980
> feat(javadoc): add antiaffinity rule

- config/uplink.yaml
> feat(uplink): add antiaffinity rule

- config/reports.yaml
> feat(reports): add antiaffinity rule

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3761
> cleanup(infra.ci.jenkins.io) remove Oracle Cloud credentials 

- config/artifact-caching-proxy__common.yaml
> feat(artifact-caching-proxy): add antiaffinity rule

- clusters/publick8s.yaml
- config/jenkinsio.yaml
> feat(jenkinsio): add antiaffinity rule

- config/mirrorbits.yaml
⚠️ NEED TO BE UPDATE FOR https://github.com/jenkins-infra/helm-charts/pull/815
> feat(mirrorbits): add antiaffinity rule

- config/private-nginx-ingress_publick8s.yaml
> feat(private-nginx-ingress_publick8s): add antiaffinity rule

- config/public-nginx-ingress_publick8s.yaml
> feat(public-nginx-ingress_publick8s.yaml): add antiaffinity rule

- config/plugin-health-scoring.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3619#issuecomment-1713522131
> feat(PluginHealthScoring): migrate to arm

- config/updates.jenkins.io.yaml
> feat(updates-jenkins-io) use an umbrella PVC and Ingress

- clusters/privatek8s.yaml
- clusters/publick8s.yaml
Reverts jenkins-infra/kubernetes-management#4516
> Revert "Bump `jenkins` helm chart version to 4.7.0"

- config/rating.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3619
> feat(rating): migrate to arm64

- config/private-nginx-ingress_publick8s.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3619
> feat(publick8s) migrate private-nginx-ingress to arm64 - controller and defaultBackend

- config/incrementals-publisher.yaml
> feat(publick8s): migrate `incremental-publisher` to arm64

- config/mirrorbits.yaml
> feat(publick8s): migrate `mirrorbits` to arm64

- Jenkinsfile_k8s
Ref. https://github.com/jenkins-infra/helpdesk/issues/3683#issuecomment-1780857936
> feat(doks, doks-public) disable clusters management

- config/uplink.yaml
Announcement: https://github.com/jenkins-infra/status/pull/402
> feat(publick8s): migrate `uplink` to arm64

- Jenkinsfile_k8s
for https://github.com/jenkins-infra/helpdesk/issues/3683%5C#issuecomment-1794913444
> disable AWS EKS clusters management

- clusters/publick8s.yaml
- config/cert-manager_publick8s.yaml
> feat(publick8s): migrate `cert-manager` to arm64

- Jenkinsfile_k8s
Ref. https://github.com/jenkins-infra/helpdesk/issues/3683#issuecomment-1797928819
> Disable privatek8s

- Jenkinsfile_k8s
Reverts jenkins-infra/kubernetes-management#4640
Ref. https://github.com/jenkins-infra/helpdesk/issues/3683#issuecomment-1797928819
> Revert "Disable privatek8s"

- Jenkinsfile_k8s
Related to https://github.com/jenkins-infra/helpdesk/issues/3683
> disable-publick8s

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
Ref: https://github.com/jenkins-infra/helpdesk/issues/3619#issuecomment-1805437441
> feat: add `plugin-site-api` to the Docker jobs on `infra.ci.jenkins.io`

- config/plugin-site-issues.yaml
- config/plugin-site.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3619#issuecomment-1810363708
migrate pluginsite and pluginsite-issues to arm64 (including the API)
> feat(pluginsite/issues): migrate to arm64

- clusters/publick8s.yaml
following #4683 to correct chart version
> update charts versions

- config/jenkins_weekly.ci.jenkins.io.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3619#issuecomment-1816831551
> feat(publick8s): migrate weekly.ci.jenkins.io to arm64

- config/jenkins_weekly.ci.jenkins.io.yaml
Reverts jenkins-infra/kubernetes-management#4694
as
> Revert "feat(publick8s): migrate weekly.ci.jenkins.io to arm64"

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3809#issuecomment-1822357561
> chore: add `contributor-spotlight` job to infra.ci.jenkins.io

- config/jenkins_infra.ci.jenkins.io.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3823
> feat(infra.ci): rename arm64 agent pod container to jnlp and change the image to allinone

- config/artifact-caching-proxy_azure.yaml
- config/keycloak.yaml
- config/ldap.yaml
- config/mirrorbits.yaml
- config/updates.jenkins.io.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3827
> feat(publick8s): relaxing node selection to amd64 instead of specific nodepool

- config/jenkins_infra.ci.jenkins.io.yaml
> feat(infra.ci): add label to agents kubernetes

- config/jenkins_infra.ci.jenkins.io.yaml
path from https://github.com/jenkins-infra/packer-images/blob/1b0f119e8458058cf7dc1dde0c2ef667fe892b77/provisioning/ubuntu-provision.sh#L312C27-L312C38
closes #4773
> fixup(infra.ci): update java path with the correct one from packer-images

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
Reverts jenkins-infra/kubernetes-management#4750
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3867#issuecomment-1859079361
> Revert "chore: unique Jenkinsfile for plugin-site"

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
Reverts jenkins-infra/kubernetes-management#4777
> Revert "Revert "chore: unique Jenkinsfile for plugin-site""

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
- config/jenkins_infra.ci.jenkins.io.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3818#issuecomment-1862531092
create new credential for sponsored subscription
credential added in secrets here https://github.com/jenkins-infra/charts-secrets/commit/32d018e134b6daa0ffe7d49bc354fa893535429d
> feat(privatek8s): add a new credential for the packer images on infra.ci

- updatecli/updatecli.d/charts/jenkins-agents-infra.ci.jenkins.io.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3823
> chore(updatecli): add the arm64 agent version for allinone

- README.md
Just a minor proposal to improve the README.md to make it more perfect
> doc: Improve the README document

- config/jenkins_infra.ci.jenkins.io.yaml
https://infra.ci.jenkins.io/job/kubernetes-jobs/job/kubernetes-management/view/change-requests/job/PR-4824/7/consoleFull 
```
Exit Code: 137, Reason: OOMKilled
```
as per https://github.com/jenkins-infra/helpdesk/issues/3823
> feat(infra.ci): increase memory limit for arm64 agent

- updatecli/updatecli.d/charts/jenkins-agents-infra.ci.jenkins.io.yaml
> chore(updatecli/hotfix): missing double quote

- config/get-jenkins-io.yaml
> chore(get.jenkins.io): fix `yamllint` warnings

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3823#issuecomment-1873857618
> feat(infra.ci): remove job for docker-helmfile

- config/jenkins_infra.ci.jenkins.io.yaml
- config/jenkins_release.ci.jenkins.io.yaml
- config/jenkins_weekly.ci.jenkins.io.yaml
Reverts jenkins-infra/kubernetes-management#4889
I checked on the instances affected that the option set is present this time :)
> Revert "Revert "Add a pipeline overview to the build page""

- clusters/publick8s.yaml
- config/get-jenkins-io.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/3917
Follow up of manual tests done in #4909 
This PR **needs** the secrets to be updated. As such, the deployment will be run manually.
> feat(get.jenkins.io) Migrate to the new premium storage account

- Jenkinsfile_k8s
as per https://github.com/jenkins-infra/helpdesk/issues/3948#issuecomment-1938993039
> feat(doks/doks-public) re-enable digital ocean on kubernetes-management

- config/uplink.yaml
https://github.com/jenkins-infra/helpdesk/issues/3883
> fix(uplink) changing replicaCount to 1 as it's not able to use multiple pods

- Jenkinsfile_k8s
as per https://github.com/jenkins-infra/helpdesk/issues/3948#issuecomment-1976757473
> feat: disable AWS EKS clusters management

- Jenkinsfile_k8s
as per https://github.com/jenkins-infra/helpdesk/issues/3948
> feat(cik8s): re-enabling cik8s in kubernetes-management

- Jenkinsfile_k8s
as per https://github.com/jenkins-infra/helpdesk/issues/3948
> feat(eks-public): re-enabling eks-public in kubernetes-management

- config/jenkins_infra.ci.jenkins.io.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3823#issuecomment-1961400721
> feat(infra.ci) add the same label as on ci.j.io for the ARM64 VM

- Jenkinsfile_k8s
as per https://github.com/jenkins-infra/helpdesk/issues/3948#issuecomment-1991181964
> feat(publick8s) disable clusters management

- Jenkinsfile_k8s
Reverts jenkins-infra/kubernetes-management#5068
> Revert "feat(publick8s) disable clusters management"

- config/jenkins_release.ci.jenkins.io.yaml
Reverts jenkins-infra/kubernetes-management#5140
> Revert "chore(release.ci): migrate to arm64"

- updatecli/updatecli.d/charts/plugin-health-scoring.yaml
This PR prepends a ping to @alecharp to Plugin Health Scoring pull request description.
@alecharp: WDYT?
> updatecli(plugin-health-scoring): add a ping to @alecharp

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3885#issuecomment-2090052823
> chore: add `docs.jenkins.io` job to infra.ci.jenkins.io

- clusters/publick8s.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/2649\#issuecomment-2090967319
- Credentials updated in (private) https://github.com/jenkins-infra/charts-secrets/commit/4a209b26d9bd98044c0ac91566a6bed2c331cf02
> feat(publick8s/updates.jenkins.io) install with premium storage

- updatecli/updatecli.d/jenkins-controllers/kubernetes-pods-quotas.yaml
Fixup of https://github.com/jenkins-infra/kubernetes-management/pull/5243
> chore(updatecli) add manifest to track ci.jenkins.io Kubernetes agents pod_quotas

- Jenkinsfile_k8s
- clusters/infracijioagents1.yaml
- config/datadog_infracijioagents1.yaml
- config/jenkins-jobs_infra.ci.jenkins.io.yaml
- config/jenkins-kubernetes-agents_infra.ci.jenkins.io.yaml
as per 
- https://github.com/jenkins-infra/helpdesk/issues/3923
adding the new cluster in the kubernetes-management with the secrets in charts-secrets for infra.ci -- commit [2fcc66d]
need 
- #5313
> feat(infracijioagents1): add new cluster in kubernetes-management

- config/jenkins_infra.ci.jenkins.io.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3923
add a new credential for the Service Account Token for the new cluster `infracijenkinsio-agents-1` 
follow commit on `private` repo for secrets : [ea24002](https://github.com/jenkins-infra/charts-secrets/commit/ea24002595e0fc36f8207e95fc62532a589fad8a)
> feat(infra.ci.jenkins.io) add a new SA token for `infracijenkinsio-agents-1` 

- config/jenkins_infra.ci.jenkins.io.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3923
(hot)fix certificate
> fix(privatek8s/infra.ci): decode base64 certificate for kubernetes cloud

- config/jenkins_infra.ci.jenkins.io.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/4044
migrating to terraform managed disk/pv/pvc in standard ZRS
⚠️ do not merge, need a last moment sync for the migration
> feat(privatek8s/infra.ci): migrate volume/pv/pvc to standard ZRS

- config/get-jenkins-io.yaml
- config/keycloak.yaml
- config/updates.jenkins.io.yaml
- config/updates.jenkins.io_httpd.yaml
Same as #5394 but for x86 services
> feat(publick8s) decrease resource requests to pack more pods on x86 machines

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
> feat(privatek8s/infra.ci.jenkins.io) split repository docker-jenkins-weekly job into 2 distinct ones. Ref. jenkins-infra/helpdesk#4171

- config/jenkins_infra.ci.jenkins.io.yaml
> fix(privatek8s/infra.ci) remove CPU limit to avoid throttling and increase memory limit for usual pods

- clusters/publick8s.yaml
- config/updates.jenkins.io.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/2649\#issuecomment-2284762944
Blocked by https://github.com/jenkins-infra/helm-charts/pull/1262
> fix(publick8s/updates.jio) only send file URL to mirrorbits or rewrite to index listing

- config/artifact-caching-proxy_azure-aks.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4241
> feat(ci.jio-agents-1) Increase ACP resources

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4165#issuecomment-2302520444
Requires secret (https://github.com/jenkins-infra/charts-secrets/commit/a6497c611f8d7071778cd9fd25334ef04bc12b2e)
> feat(privatek8s/infra.ci) set up Docker Jobs to use a new folder-scoped GHA

- Jenkinsfile_k8s
Reverts jenkins-infra/kubernetes-management#5598
Ref. https://github.com/jenkins-infra/helpdesk/issues/4161#issuecomment-2304434455
> Revert "chore(infracijioagents1): removing temporarily from management to upgrade to kubernetes 1.29"

- Jenkinsfile_k8s
Related to https://github.com/jenkins-infra/helpdesk/issues/4161#issuecomment-2304516597
> chore: disable cijioagents1 management

- Jenkinsfile_k8s
Reverts jenkins-infra/kubernetes-management#5609
Related to https://github.com/jenkins-infra/helpdesk/issues/4161#issuecomment-2304516597
> Revert "chore: disable cijioagents1 management"

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
Ref. https://github.com/jenkins-infra/helm-charts/pull/1308
> chore(privatek8s/infra.ci) simplify Docker and Terraform Jobs configuration

- clusters/privatek8s.yaml
Reverts jenkins-infra/kubernetes-management#5633
> Revert "Bump `jenkins-jobs` helm chart version to 2.1.1"

- clusters/publick8s.yaml
> fix(publick8s) ensure all httpd restarts are created with a valid name

- config/updates.jenkins.io-content-unsecured.yaml
Fixup of #5752 , #5755 (I messed up my branches)
> fix(publick8s/mirrors.updates.jenkins) correct ingress rewrite

- config/updates.jenkins.io-content-secured.yaml
- config/updates.jenkins.io-content-unsecured.yaml
- config/updates.jenkins.io_httpd-secured.yaml
- config/updates.jenkins.io_httpd-unsecured.yaml
Follows https://docs.datadoghq.com/logs/log_configuration/attributes_naming_convention/ and https://docs.datadoghq.com/containers/kubernetes/log/?tab=helm
> feat(publick8s/updates.jenkins.io) enable datadog logs annotation with custom tags

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
> hotfix(infra.ci) remove quotes killing jcasc

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/4278#issuecomment-2434697809
add the new repository to the docker folder in infra.ci and prepare the updatecli one
> feat(infra.ci) adding docker-geoipupdate

- updatecli/updatecli.d/ldap-restricted-ips.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4315#issuecomment-2483687965
> chore(updatecli) track aws.ci.jenkins.io public IP to keep LDAP configuration up to date

- config/updates.jenkins.io-content-secured.yaml
- config/updates.jenkins.io-content-unsecured.yaml
- config/updates.jenkins.io_httpd-secured.yaml
- config/updates.jenkins.io_httpd-unsecured.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/2649
> fix(publick8s/updates.jio) disable ingrerss rewrite logs as it is resources hungry

- config/geoipdata.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/4278
testing on staging
> feat(publick8s): testing maxmind geoip update on staging with personnal account

- config/geoipdata.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/4436
new cron for the cronjob to follow maxmind recommendation of updating once every 3 days
PS: wait a few days before merging
> chore(publick8s): geoipupdate remove unused parameter

- clusters/publick8s.yaml
using https://github.com/jenkins-infra/helm-charts/releases/tag/geoipupdates-2.4.0 to fix json existence
as per https://github.com/jenkins-infra/helpdesk/issues/4441
> feat( publick8s): bump geoipupdater to 2.4.0

- clusters/privatek8s.yaml
- clusters/publick8s.yaml
Reverts jenkins-infra/kubernetes-management#6057
> Revert "Bump `nginx-ingress` helm chart version to 4.12.0"

- config/artifact-caching-proxy_azure-aks.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4442#issuecomment-2618579627
> fix(ci.jio-agents-1/ACP) Pass SNI to upstreams

- config/jenkins-kubernetes-agents_ci.jenkins.io_cijioagents2-bom.yaml
Reverts jenkins-infra/kubernetes-management#6228
> Revert "hotfix(cijioagents2) increase BOM pods quota from `300` to `400`"

- Jenkinsfile_k8s
as per https://github.com/jenkins-infra/helpdesk/issues/4258#issuecomment-2666362598
remove cijioagent2 from kubernetes management
> feat(cijioagents2) upgrade to kubernetes 1.30.9

- Jenkinsfile_k8s
as per https://github.com/jenkins-infra/helpdesk/issues/4258#issuecomment-2666362598
> feat(pipeline): re enable cijioagents2 after kub 1.30 upgrade

- Jenkinsfile_k8s
as per https://github.com/jenkins-infra/helpdesk/issues/4258#issuecomment-2663185312
> feat(pipeline): remove infracijuiagents1 for kub 1.30 upgrade

- Jenkinsfile_k8s
Reverts jenkins-infra/kubernetes-management#6252
re-enable cluster
> Revert "feat(pipeline): remove infracijioagents1 for kub 1.30 upgrade"

- Jenkinsfile_k8s
as per https://github.com/jenkins-infra/helpdesk/issues/4258#issuecomment-2668175339
> feat(pipeline): remove privatek8s for kub 1.30 upgrade

- Jenkinsfile_k8s
Reverts jenkins-infra/kubernetes-management#6254
re-enable `privatek8s`
> Revert "feat(pipeline): remove privatek8s for kub 1.30 upgrade"

- config/ldap.yaml
- updatecli/updatecli.d/pvc-updates-jenkins-io-httpd.yaml
- updatecli/updatecli.d/pvc-updates-jenkins-io-mirrorbits.yaml
Minor fixes on updatecli (naming and visual)
> chore(updatecli) fixups on updates.jenkins.io PVCs tracking

- Jenkinsfile_k8s
as per https://github.com/jenkins-infra/helpdesk/issues/4258#issuecomment-2663553626
> feat(pipeline): remove publick8s for kub 1.30 upgrade

- Jenkinsfile_k8s
Reverts jenkins-infra/kubernetes-management#6262
re-enable publick8s
> Revert "feat(pipeline): remove publick8s for kub 1.30 upgrade"

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
> chore(docker-hub/credential) remove unused credential, migrate to terraform-aws-sponsored

- config/artifact-caching-proxy_aws-cijenkinsio-agents-2.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4545#issuecomment-2722304359
> feat(ci.jio-agents-2) scale down ACP to 1 replica

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
- config/ldap.yaml
- updatecli/updatecli.d/charts/artifact-caching-proxy.yaml
- updatecli/updatecli.d/charts/datadog.yaml
- updatecli/updatecli.d/jenkins-controllers/kubernetes-pods-quotas.yaml
- updatecli/updatecli.d/ldap-restricted-ips.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4313
Fixup of https://github.com/jenkins-infra/kubernetes-management/pull/6318 as it broke many updatecli manifests here
> chore(updatecli) finish cleanup of leftovers from azure.ci.jenkins.io

- clusters/cijioagents2.yaml
- config/cijioagents2-maven-cacher.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4525
> feat(ci.jio-agents-2) add a maven-cacher helm release

- config/private-nginx-ingress__common.yaml
- config/public-nginx-ingress__common.yaml
Ref. https://kubernetes.io/blog/2025/03/24/ingress-nginx-cve-2025-1974/\#your-next-steps and https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx
Big shoutout to @lemeurherveCB and @olblak
> feat: disable admission webhook on all ingress-nginx controllers - 

- clusters/cijioagents1.yaml
- clusters/cijioagents2.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4619
This PR creates the required resource for the 2 Jenkins Agents namespaces
> feat(cijenkinsio-agents-1) install jenkins agent namespaces

- Jenkinsfile_k8s
as per https://github.com/jenkins-infra/helpdesk/issues/4546#issuecomment-2674539441
> feat(pipeline): remove infracijioagents1 from jenkinsfile for kub 1.31.6 upgrade

- Jenkinsfile_k8s
Reverts jenkins-infra/kubernetes-management#6411
> Revert "feat(pipeline): remove infracijioagents1 from jenkinsfile for kub 1.31.6 upgrade"

- config/ldap.yaml
- updatecli/updatecli.d/configs/ldap-restricted-ips.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4620#issuecomment-2778047717
Note: updatecli is already broken on the main branch.
> feat(publick8s/ldap) allow azure.ci.jenkins.io

- config/jenkins_weekly.ci.jenkins.io.yaml
Ref. https://github.com/jenkinsci/customizable-header-plugin/pull/194/files#r2054468199
> fix(publick8s/weekly.ci) remove deprecated parameter for the custom-header plugin

- Jenkinsfile_k8s
as per https://github.com/jenkins-infra/helpdesk/issues/4546#issuecomment-2674551720
upgrade to kubernetes 1.31
> feat(privatek8s): remove privatek8s from pipeline for kub 1.31 upgrade

- Jenkinsfile_k8s
Reverts jenkins-infra/kubernetes-management#6474
> Revert "feat(privatek8s): remove privatek8s from pipeline for kub 1.31 upgrade"

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
Requires https://github.com/jenkins-infra/charts-secrets/commit/b813639b1e4935d24c4ea14feb322553ca7c0d7c
> feat(privatek8s/infra.ci) add credential for the new privatek8s_sponsorship cluster

- Jenkinsfile_k8s
see https://github.com/jenkins-infra/helpdesk/issues/4546#issuecomment-2674545933
remove publick8s from pipeline during upgrade
> feat(publick8s): remove publick8s from pipeline for kub 1.31 upgrade

- Jenkinsfile_k8s
Reverts jenkins-infra/kubernetes-management#6483
> Revert "feat(publick8s): remove publick8s from pipeline for kub 1.31 upgrade"

- clusters/privatek8s-sponsorship.yaml
Note: we restricted the ACME secret to only jenkins.io. Requires https://github.com/jenkins-infra/charts-secrets/commit/a71e4ae46501d6b02c4862805e96bf68124cbaaf
> feat(privatek8s-sponsorship) add cert-manager release and resources

- clusters/privatek8s-sponsorship.yaml
> feat(privatek8s-sponsorship) add jenkins-jobs release

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/4645
remove ircbot jobs from infra.ci
> feat(infra.ci): remove ircbot builds

- clusters/privatek8s-sponsorship.yaml
Reverts jenkins-infra/kubernetes-management#6520
Ref. https://github.com/jenkins-infra/azure/pull/1020#issuecomment-2835578632
> Revert "feat(privatek8s-sponsorship) add core-package PV/PVCs"

- clusters/privatek8s-sponsorship.yaml
- clusters/privatek8s.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4250#issuecomment-2838032516
> feat(privatek8s-sponsorship) migrate release.ci.jenkins.io 

- clusters/privatek8s-sponsorship.yaml
- config/jenkins_infra.ci.jenkins.io.yaml
- config/jenkins_release.ci.jenkins.io.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4250#issuecomment-2838032516
Note: will be applied manually
> feat(privatek8s-sponsorship) migrate infra.ci

- config/ldap.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3837#issuecomment-2211697420
> feat(publick8s) migrate LDAP to arm64

- clusters/infracijioagents2.yaml
- config/jenkins-infra-agents-infracijioagents2.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/4689#issuecomment-2961894408
adding the release for jenkins-agents for the new cluster: infracijioagents2
> feat(infracijioagents2): add jenkins infra agents release

- clusters/publick8s.yaml
- config/keycloak.yaml
> feat(publick8s) add pod annotations for datadog logs collection on admin.account.jenkins.io (keycloak)

- clusters/publick8s.yaml
- config/plugin-site-issues.yaml
> feat(publick8s) add pod annotations for datadog logs collection on plugin-site-issues.jenkins.io

- clusters/publick8s.yaml
- config/jenkinsio.yaml
> feat(publick8s) add pod annotations for datadog logs collection on www.jenkins.io

- config/updates.jenkins.io_httpd-secured.yaml
- config/updates.jenkins.io_httpd-unsecured.yaml
Ref. https://docs.datadoghq.com/integrations/apache/?tab=host
> fix(publick8s/updates.jenkins.io) use the proper datadog logs parser for httpd

- config/wiki.yaml
> feat(publick8s) add pod annotations for datadog logs collection on wiki.jenkins.io

- config/jenkins_infra.ci.jenkins.io.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4696
> feat(privatek8s/infra.ci) specify User Assigned Identity for Azure VM agents

- clusters/cijioagents2.yaml
- config/jenkins-kubernetes-agents_ci.jenkins.io_cijioagents2-bom.yaml
- config/jenkins-kubernetes-agents_ci.jenkins.io_cijioagents2.yaml
> feat(cijenkinsagents2) install jenkins-agents namespaces

- clusters/cijioagents2.yaml
- config/cijioagents2-maven-cacher.yaml
Note: updated the image version
> feat(cijenkinsagents2) install maven-cacher system

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
Requires https://github.com/jenkins-infra/charts-secrets/commit/a753cbdeff8ebfd5bc01f7dddc7ae981e90505a6
> feat(privatek8s/infra.ci) specify fastly api token credential for 4 production websites

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/4701
let's create credentials to access the primary subscription also called CDF
> feat(infra.ci): add credential for packer on CDF subscription

- clusters/cijioagents2.yaml
- config/cijioagents2-maven-cacher.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4752
> feat(cijenkinsioagents2/maven-cacher) fix cache generation by adding script fix and increase resources

- config/updates.jenkins.io-content.yaml
- config/updates.jenkins.io-rsyncd-data.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4758
Applied manually for https://github.com/jenkins-infra/azure/pull/1151
> feat(publick8s/updates.jenkins.io) unify private link services

- clusters/publick8s.yaml
- config/get-jenkins-io.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4691#issuecomment-3177968385
Note: requires https://github.com/jenkins-infra/charts-secrets/commit/1cb067ef3510ab22142c9c9a84b532703d00718d
> feat(publick8s/get.jenkins.io) migrate to self hosted Redis instance

- updatecli/updatecli.d/configs/pvc-updates-jenkins-io-mirrorbits.yaml
Following https://github.com/jenkins-infra/azure/pull/1159
> chore(updatecli) fix JSON path to geoipdata volume 

- updatecli/updatecli.d/docker-images/jenkins-weekly_infra.ci.jenkins.io.yaml
- updatecli/updatecli.d/docker-images/keycloak-theme.yaml
- updatecli/updatecli.d/jenkins-controllers/jenkins-agents-infra.ci.jenkins.io.yaml
- updatecli/updatecli.d/jenkins-controllers/tools-maven.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4769
> chore(updatecli) fix manifests to track ACR images when needed

- config/jenkins_release.ci.jenkins.io.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/4776
need the plugin to be installed in the docker image for the release (lts version) see: https://github.com/jenkins-infra/docker-jenkins-lts/pull/1023
> feat(release.ci) add csp plugin configuration

- config/ldap.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4615
> hotfix(publick8s/ldap) allow VPN new public IP instead of old one

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
Requires https://github.com/jenkins-infra/charts-secrets/commit/d1c47a9a01241cfa734483cea4864597c9d4003a
Blocks #7059
> feat(publick8s/infra.ci) rename publick8s kubeconfig

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/4617#issuecomment-3295780800
Requires https://github.com/jenkins-infra/charts-secrets/commit/6a3d24cf81e64c1c960d6934e3893cd5b367bf8d
> feat(privatek8s/infra.ci) add kubeconfig for the new `publick8s` cluster

- clusters/publick8s-endless-ghoul.yaml
- clusters/publick8s.yaml
- config/publick8s_contributors.jenkins.io.yaml
- config/publick8s_docs.jenkins.io.yaml
- config/publick8s_plugins-jenkins-io.yaml
- config/publick8s_reports-jenkins-io.yaml
- config/publick8s_stats.jenkins.io.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4617
> feat(publick8s) add static websites releases with new naming (NS/files)

- clusters/publick8s.yaml
- config/publick8s_ldap.yaml
- config/publick8s_weekly-ci-jenkins-io.yaml
This PR adds LDAP and weekly.ci releases, in "duplicated" mode (e.g. not impacting the current production). 
The goal is to ensure that all services are running properly in this new cluster without impacting current production, so we can do a blue/green migration.
Requires https://github.com/jenkins-infra/azure/pull/1203, https://github.com/jenkins-infra/azure/pull/1204, https://github.com/jenkins-infra/azure/pull/1205 and https://github.com/jenkins-infra/azure/pull/1206 to ensure all PV and PVCs are set up
Migration done with the pod definition shared in https://github.com/jenkins-infra/azure/pull/1206
<details>
<summary>Click to see migration commands and their results</summary>
`ldap.jenkins.io`:
```
apk update && apk add …
```
> feat(publick8s) add weekly and ldap

- config/publick8s_reports-jenkins-io.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4821#issuecomment-3366313708
This PR requires the new storage to be filled at least once.
Once merged and deployed successfully, https://github.com/jenkins-infra/pipeline-library/pull/963 shall be merged switfly to avoid discrepancies in reports.
(edit) Initial volume filling with the following Pod:
```
kind: Pod
apiVersion: v1
metadata:
name: data-migration-reports
namespace: reports-jenkins-io
spec:
nodeSelector:
kubernetes.io/arch: arm64
tolerations:
- key: "kubernetes.io/arch"
operator: "Equal"
value: "arm64"
effect: "NoSchedule"
containers:
- image: alpine
name: migration
command:
- "sleep"
- "10000"
volumeMounts:
- name: orig-data
mountPath: "/data/src"
readOnly: true
- name: data
mountPath: "/data/dest"
readOnly: false
volumes: …
```
> feat(publick8s/reports.jenkins.io) switch to the new V2 Storage account / file share
