jenkins-infra/kubernetes-management

- config/release/jenkins/values.yaml
This id value is now required by jobdsl as explained [here](https://github.com/jenkinsci/job-dsl-plugin/blob/master/docs/Migration.md#migrating-to-175)
> Add id source context github jobs

- helmfile.d/datadog.yaml
- helmfile.d/loki.yaml
- helmfile.d/nginx-ingress.yaml
This PR is needed in order to work with the latest helm version
> ==> Linting /tmp/204077806/datadog/1.24.0/stable/datadog/datadog
> [ERROR] Chart.yaml: apiVersion is required
>
> Bump datadog/nginx-ingress/loki helm chart

- config/default/plugin-site.yaml
I am re-increasing the limit  of the pluginsite as, according the monitoring, it's way too low, and containers don't start
> Re-increase plugin-site limit

- config/default/jenkinsio.yaml
should't cause any harm, noticed while looking to see why jenkins.io wasn't deploying to AKS
> Fix typo - remove duplicate yaml

- config/default/plugin-site.yaml
Need to be able to hit the API from front end, and easier than running my own fork.
> Enable CORS for plugin site

- config/default/grafana.yaml
Update the grafana service running on publick8s to use the correct DNS [record](https://github.com/jenkins-infra/azure/blob/7fa3fda31020879e5453fc76a44e3effce4ee6df/plans/dns_jenkinsio.tf#L69)
> Use grafana.publick8s.jenkins.io grafana.jenkins.io

- charts/plugin-site/templates/deployment-frontend.yaml
- charts/plugin-site/templates/nginx-configmap.yaml
- charts/plugin-site/values.yaml
From what I can see online (https://www.ruby-forum.com/t/nginx-0-7-59-open-file-cache-and-nfs/169930/6 and other pages)
the open file cache messes with network filesystems a bit, so disable
that performance fix
---
@olblak I can't reproduce the problem locally, so giving you two options.
This one just goes back to regular nginx
> Switch to the nginx for serving plugin site content

- charts/plugin-site/templates/deployment-backend.yaml
as far as I can tell from https://github.com/jenkins-infra/plugin-site-api/blob/master/src/main/java/io/jenkins/plugins/services/impl/GithubExtractor.java#L40 the env variable should be GITHUB_SECRET
> [plugin-site] rename env variable to GITHUB_SECRET to match code

- charts/jenkins-wiki-exporter/values.yaml
When exporting heavy wiki pages or lots in a short time the current CPU limit is not enough
> Increase wiki exporter CPU limits

- CODEOWNERS
I propose to use a [team](https://github.com/orgs/jenkins-infra/teams/kubernetes/discussions) named 'kubernetes' as default codeowner.
> Use jenkins-infra/kubernetes team as default CODEOWNERS

- charts/jenkins-wiki-exporter/templates/deployment.yaml
- charts/jenkins-wiki-exporter/templates/secret.yaml
This PR configure a GitHub token for the Jenkins wiki exporter as needed from this [PR](https://github.com/jenkins-infra/jenkins-wiki-exporter/pull/64)
> Add Github_token env variable to jenkins-wiki-exporter

- helmfile.d/grafana.lock
- helmfile.d/grafana.yaml
This reverts commit 09d0e49b0db95141a16d97bc33a5cc9185f9b78c.
Grafana is not a critical service for us so I prefer to always install the latest version and fix issues when they occur than locking to  a specific version and then taking the risk to run outdated version.
> Revert "Lock grafana (#134)"

- charts/mirrorbits/.helmignore
- charts/mirrorbits/Chart.yaml
- charts/mirrorbits/README.md
- charts/mirrorbits/templates/NOTES.txt
- charts/mirrorbits/templates/_helpers.tpl
- charts/mirrorbits/templates/configmap.files.yaml
- charts/mirrorbits/templates/deployment.files.yaml
- charts/mirrorbits/templates/deployment.yaml
- charts/mirrorbits/templates/ingress.yaml
- charts/mirrorbits/templates/persistentVolume.yaml
- charts/mirrorbits/templates/persistentVolumeClaim.yaml
- charts/mirrorbits/templates/secret.yaml
- charts/mirrorbits/templates/service.files.yaml
- charts/mirrorbits/templates/service.yaml
- charts/mirrorbits/templates/serviceaccount.yaml
- charts/mirrorbits/templates/tests/test-connection.yaml
- charts/mirrorbits/values.yaml
- clusters/publick8s.yaml
- config/default/mirrorbits-database.yaml
- config/default/mirrorbits.yaml
- helmfile.d/mirrorbits.yaml
This Pull request deploys [mirrorbits](https://github.com/etix/mirrorbits) and a Redis database on Kubernetes.
In order to consider this PR as a full replacement of mirrors.jenkins.io, we still need to validate the following things
Currently, this service is accessible from the VPN but empty at the moment
Update /etc/hosts with [release.mirrors.jenkins.io](https://release.mirrors.jenkins.io/?mirrorstats ) set to `10.0.2.5`
Example: https://release.mirrors.jenkins.io/debian/jenkins_2.218_all.deb?mirrorlist
or https://release.mirrors.jenkins.io/debian/jenkins_2.218_all.deb?mirrorstats
https://release.mirrors.jenkins.io/debian/jenkins_2.218_all.deb?stats
> Deploy Mirrorbits

- PodTemplates.yaml
The Jenkins job is failing systematically with the following error 
```
wrapper script does not seem to be touching the log file in /home/jenkins/agent/workspace/k8smgmt_master@tmp/durable-9062856f
(JENKINS-48300: if on an extremely laggy filesystem, consider -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=86400)
```
According the grafana dashboard, cpu limit is directly reached, and we still have plenty of memory so this pull request is an attempt to fix it.
> Adjust Podtemplate limits

- Jenkinsfile_k8s
I recently changed targets schema for SCM configuration and environment variables need to be updated accordingly. I'll try to work on some form of templating in order to only have to define the github token once
> Update updatecli environment variable according new name

- PodTemplates.yaml
Version[ 0.0.6](https://github.com/olblak/updatecli/releases/tag/v0.0.6) doesn't open empty PR
> Bump updatecli version

- charts/mirror/.helmignore
- charts/mirror/Chart.yaml
- charts/mirror/README.md
- charts/mirror/templates/NOTES.txt
- charts/mirror/templates/_helpers.tpl
- charts/mirror/templates/configmap.yaml
- charts/mirror/templates/deployment.yaml
- charts/mirror/templates/ingress.yaml
- charts/mirror/templates/persistentVolume.yaml
- charts/mirror/templates/persistentVolumeClaim.yaml
- charts/mirror/templates/secret.yaml
- charts/mirror/templates/service.yaml
- charts/mirror/templates/tests/test-connection.yaml
- charts/mirror/values.yaml
- clusters/publick8s.yaml
- config/default/archives.yaml
- config/default/mirror.yaml
- helmfile.d/archives.yaml
- helmfile.d/mirror.yaml
This pull request defines a Helm chart that can be used to deploy a HTTP/HTTPS mirror using RSYNC for synchronization.
The purpose of it is to move http://archives.jenkins-ci.org from Rackspace on our k8s cluster and also providing HTTPS.
Remarks:
1) Instead of pushing updates from pkg.jenkins.io to archives.jenkins-ci.org as defined [here](https://github.com/jenkins-infra/jenkins-infra/blob/fd567f7c295a700fac5ea30fa4e5f8cc675487d1/dist/profile/files/mirrorbrain/sync.sh#L48), this approach pulls data few times per hours from a public repository and so makes it totally independent of the release process or the Jenkins infrastructure itself.
Anybody can install this chart and then ask to add the new mirror to mirrors.jenkins.io
2) The mirror deployed on publick8s uses azure disk volume as …
> [INFRA-2466] Deploy archives.jenkins-ci.org on publick8s

- config/default/jenkins-release.yaml
- config/default/jenkins.yaml
- helmfile.d/jenkins-release.yaml
- updateCli.d/jenkins-release.yaml
* Switch release.ci.jenkins.io to lts version and automate its upgrade when a new docker image is available based on digest
* Rename jenkins.yaml configuration file to jenkins-release.yaml to be more explicit on the content
* Fix release.ci.jenkins.io packaging job to use jenkins-infra/release instead of olblak/release
> Release environment must use jenkins-infra repository

- config/default/jenkins-release.yaml
A new ssh key used to push artifacts generated by the release environment to pkg.jenkins.io
> Release env, add ssh key to upload artifacts on pkj.j.io

- charts/mirror/templates/configmap.yaml
- charts/mirrorbits/templates/configmap.files.yaml
- charts/mirrorbits/templates/deployment.files.yaml
- charts/mirrorbits/values.yaml
We'll generate htlm files that can be display before and after directory listing as decscribe [here](https://github.com/jenkinsci/packaging/pull/159)
Following configuration ne3ed to be updated
> Add FooterName and HeaderName to mirror httpd

- charts/env-jenkins-release/templates/core-packages.yaml
Current those persistentVolumeClaim are not bind to the correct PV
> Add persistentVolumeClaim matchlabel for jenkins release env

- charts/env-jenkins-release/templates/core-packages.yaml
I rollback this change as using selector implies being dynamic storage which is not our need.
For some reason, now the pvc matches the correct pv 
Ps: I am manually made the change as manipulate pvc implies deleting them
> Remove pvc selector for env-jenkins-release

- charts/env-jenkins-release/templates/core-packages.yaml
Those two volumes are used to upload core packages on an azure file storage, until now the pvc used the wrong volume, instead of using the one specified here, it was using dynamically created volumes.
This pull request aligns with local changes
> Fix release core persistentVolume

- charts/jenkinsio/templates/nginx-configmap.yaml
- charts/jenkinsio/templates/zh-configmap.yaml
- config/default/jenkinsio.yaml
I propose to switch jenkins.io website from apex domain to www.jenkins.io.
The main motivation is to be able to proxy www.jenkins.io using a CNAME record from www to dualstack.d.sni.global.fastly.net. (which also support IPV6)
https://docs.fastly.com/en/guides/using-fastly-with-apex-domains
> Redirect jenkins.io to www.jenkins.io

- charts/ldap/templates/certificate.yaml
- charts/ldap/templates/secret.yaml
- charts/ldap/templates/statefulset.yaml
- charts/ldap/values.yaml
This pull request has already been tested and deployed, I took two shortcuts here
* The ldap container won't detect a certificate change so this is something that need to implemented
* The secret generated by the certificate doesn't add any value to ca.crt, so I did it manually
> Switch ldap certificate to letsencrypt

- Jenkinsfile_k8s
- PodTemplates.yaml
- updateCli/updateCli.d/jenkins-lts-jdk11.tpl
- updateCli/updateCli.d/jenkins-weekly-jdk11.tpl
- updateCli/updateCli.d/jenkins-wiki-exporter.tpl
- updateCli/updateCli.d/nginx.tpl
- updateCli/updateCli.d/pluginsite.tpl
- updateCli/values.yaml
Update configuration to work with release [v0.0.7](https://github.com/olblak/updatecli/releases/tag/v0.0.7), we can now use go template instead of yaml which simplifies the management of multiple configurations,  and it also support three new commands 
```
updatecli diff --config .. --values
updatecli show --config ... --values ...
updatecli apply --config ... --values ...
```
> Update updatecli configuration to v0.0.7

- updateCli/updateCli.d/jenkins-wiki-exporter.tpl
GITHUB_TOKEN env variable is not available from the Jenkinsfile
> Fix github token env variable used by updatecli

- charts/ldap/templates/statefulset.yaml
- charts/ldap/values.yaml
- updateCli/updateCli.d/ldap-crond.tpl
- updateCli/updateCli.d/ldap-slapd.tpl
1. Fix docker image tag used for the cron daemon
2. Automate both slapd and crond docker image tag by using digest
> Fix ldap cron image tag

- charts/accountapp/templates/ingress.yaml
- charts/javadoc/templates/ingress.yaml
- charts/jenkins-wiki-exporter/templates/ingress.yaml
- charts/jenkinsio/templates/ingress.yaml
- charts/mirror/templates/ingress.yaml
- charts/mirrorbits/templates/ingress.yaml
- charts/pkg/templates/ingress.yaml
- charts/plugin-site/templates/ingress.yaml
- charts/polls/templates/admin-ingress.yaml
- charts/polls/templates/ingress.yaml
- charts/reports/templates/ingress.yaml
- charts/uplink/templates/ingress.yaml
Ingress resources will no longer be served from extensions/v1beta1 in v1.19. Migrate use to the networking.k8s.io/v1beta1 API, available since v1.14. Existing persisted data can be retrieved via the networking.k8s.io/v1beta1 API.
[Link](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.15.md#urgent-upgrade-notes)
> Update ingress api to networking.k8s.io/v1beta1

- charts/jenkinsio/templates/nginx-configmap.yaml
This change is discussed in the jenkins.io issue in https://github.com/jenkins-infra/jenkins.io/issues/3336 
Added the Vary header `Vary: Accept-Language` to nginx so that Fastly can keep separate cache for the languages.
Works in conjunction with the changes done by @olblak in Fastly (https://github.com/jenkins-infra/jenkins.io/issues/3336#issuecomment-635889745)
> Add Vary header Accept-Language to nginx to allow separate cache per language

- charts/keycloak/.helmignore
- charts/keycloak/Chart.yaml
- charts/keycloak/templates/NOTES.txt
- charts/keycloak/templates/_helpers.tpl
- charts/keycloak/templates/ingress.yaml
- charts/keycloak/templates/service.yaml
- charts/keycloak/templates/tests/test-connection.yaml
- charts/keycloak/values.yaml
- config/default/keycloak-public.yaml
- config/default/keycloak.yaml
- helmfile.d/keycloak.yaml
This pull request is an expirement to use something more robust than accounts.jenkins.io
It has already been deployed manually  && configured on the cluster and is available for [user](https://admin.accounts.jenkins.io/auth/realms/jenkins/account), or [administrator](https://admin.accounts.jenkins.io/auth/admin)
User are allowed to use existing ldap account (same than accounts.jenkins.io) or to delete/register new one.
If this experimentation is a success, I propose to redirect accounts.jenkins.io to https://admin.accounts.jenkins.io/auth/realms/jenkins/account[
[Screenshot](https://usercontent.irccloud-cdn.com/file/LsYpQZF2/image.png)
> Deploy keycloak

- config/default/jenkins-release.yaml
As of today, 2020-06-19, network policy is not supported for windows node https://docs.microsoft.com/en-us/azure/aks/windows-node-limitations#are-all-features-supported-with-windows-nodes
This is a blocker for the release environment as in the current state windows containers are not allowed to connect on main Jenkins. 
I disable it for now
> Disable networkPolicy for release environment

- helmfile.d/dex.yaml
```
Flag --recreate-pods has been deprecated, functionality will no longer be updated. Consult the documentation for other methods to recreate pods
```
> Remove deprecated helm option - recreatePod

- config/default/jenkins-release.yaml
Update default windows inbound agent from "jenkins4eval/jnlp-agent:latest-windows" to "jenkins/inbound-agent:windowsservercore-1809"
> Update windows inbound agent used by release environment

- config/default/jenkins-release.yaml
[INFRA-2660](https://issues.jenkins-ci.org/browse/INFRA-2660)
This pull request will update release.ci.jenkins.io configuration to allow release job to use different branch than master for:
* Stable release
* Security release
* Generic core release
* Generic core packaging
This pull request is required for this [one](https://github.com/jenkins-infra/release/pull/81) to work
> [INFRA-2660] Allow triggering release job using different branches

- helmfile.d/loki.yaml
It needed re-installing probably due to a chart version update.
And it wouldn't install in the 100 second timeout that was set due to slow volume attach.
It took about 200 seconds on my machine, but bumped it to 300 to be safe
> [loki] Increase loki install timeout

- updateCli/updateCli.d/charts/codecentric-keycloak.tpl
- updateCli/updateCli.d/charts/dex.tpl
- updateCli/updateCli.d/charts/grafana-loki.tpl
- updateCli/updateCli.d/charts/grafana-promtail.tpl
- updateCli/updateCli.d/charts/jetstack-certmanager.tpl
- updateCli/updateCli.d/charts/prometheus.tpl
- updateCli/updateCli.d/charts/stable-datadog.tpl
- updateCli/updateCli.d/charts/stable-falco.tpl
- updateCli/updateCli.d/charts/stable-jenkins.tpl
- updateCli/updateCli.d/charts/stable-nginx-ingress.tpl
- updateCli/updateCli.d/charts/stable-oauth2-proxy.tpl
- updateCli/updateCli.d/updateCliPodTemplate.tpl
- updateCli/values.yaml
Depends on #307 
This pull request improves the way we automate version by:
* Adding updatecli configuration to automate updatecli version used in the PodTemplate
* Adding condition check for every updatecli configuration that update key/value based on array position, in order to make it more robust in case that position change for some reason.
* Fix keycloak configuration from keycloack to keycloak 
* Use template for scm configuration
This PR can easily be tested by running following commands:
```
export  UPDATECLI_GITHUB_TOKEN=<your_github_token>
sed 's/username: "olblak"/username: "<your_github_handle>"/' updateCli/values.yaml
docker run -i -t -e UPDATECLI_GITHUB_TOKEN=$UPDATECLI_GITHUB_TOKEN -v $PWD/updateCli:/updateCli --workdir /updateCli olblak/updatecli:v0.0.13 diff --config …
```
> Improve updatecli configuration

- helmfile.d/falco.yaml
- updateCli/updateCli.d/charts/falco.tpl
Fix Falco repository url
```
olblak@winterfell  ~/Project/Jenkins-infra/charts  master ? ⍟18  helm show chart falco/falco               ✔  10029  15:54:40 
apiVersion: v1
appVersion: 0.23.0
description: Falco
home: https://falco.org
icon: https://falco.org/images/logos/falco-logo.png
keywords:
- monitoring
- security
- alerting
- metric
- troubleshooting
- run-time
maintainers:
- email: cncf-falco-dev@lists.cncf.io
name: The Falco Authors
name: falco
sources:
- https://github.com/falcosecurity/falco
version: 1.1.10
```
> Update falco repository url

- charts/jenkinsio/templates/nginx-configmap.yaml
This PR sets explicit cache time for all XML and JSON files returned by jenkins.io. Specifically, it should fix problem with 20day caching of Changelog RSS files and badges, but I thought it would not hurt to apply it globally
> Set cache time to 1h for Changelog RSS and badge JSONs

- config/default/jenkins-release.yaml
While INFRA-2674 is not done otherwise each I manually update the job configuration, my manual change is reverted
> Disable release.ci config autoreload

- config/default/jenkins-release.yaml
As we are not planning to use the security release job, I propose to remove to avoid any kind of confusion.
> Remove security release job from release.ci

- config/default/prometheus.yaml
- helmfile.d/prometheus.yaml
Recent prometheus update was blocked because a volume was already attached the exist container, switch alertmanager to a statefulset better handle such usecases
> Use statefulset for prometheus alertmanager

- charts/plugin-site/Chart.yaml
- charts/plugin-site/values.yaml
Updates to https://github.com/jenkins-infra/plugin-site-api/releases/tag/plugin-site-api-1.11.1
mainly fixes links for issues mentioned in github releases and switches accessing urls with client_id in queryy string to using basic auth
see https://github.com/jenkins-infra/plugin-site-api/releases/tag/plugin-site-api-1.11.1
> [stable/plugins-site] Manual bump of plugin-site-api docker image since its not yet semver docker names

- config/default/jenkins-release.yaml
This PR had fastly credentials to release.ci in order to be used by 
https://github.com/jenkins-infra/release/pull/95
> Add Fastly credentials to release.ci

- charts/plugin-site/Chart.yaml
- charts/plugin-site/README.md
- charts/plugin-site/templates/deployment-backend.yaml
- charts/plugin-site/templates/secret.yaml
- charts/plugin-site/values.yaml
Uses github app credentails for all api requests
- fixes # [INFRA-2691](https://issues.jenkins-ci.org/projects/INFRA/issues/INFRA-2691)
> [stable/plugin-site] Switch to newer plugin-site-api that uses github apps for api requests

- config/default/jenkins-infra.yaml
Add docker credentials to infra.ci
The secrets looks like 
```
secrets:
DOCKER_HUB: |
{
"auths": {
"https://index.docker.io/v1/": {
"auth": "XXX"
}
},
}
```
> Add .docker/config.json to infra.ci

- config/default/jenkins-infra.yaml
the dockerhub credentials need to be copied over
https://github.com/jenkins-infra/pipeline-library/blob/c88ea135745ba7f3cd45f2a5a3590d7dccfb1606/vars/infra.groovy#L14
I *think* the default jenkins file will still  work since it should auto find a node since there are none with linux && high mem, but we will see
Might also need to setup a dind setup like i did or something
https://github.com/halkeye-docker/docker-jenkins/blob/master/jenkins.yaml#L52
> Add more projects to infra ci

- .sops.yaml
This means that now by default when we create a new sops file then we also use timja publick GPG key on top of olblak and azure key vault
> Add timja to every sops file

- config/default/jenkins-infra.yaml
Right now there's no way for someone who doesn't have vpn access to make a release of wiki exporter or custom war package
Polling every 2 hours will let them do a normal git release process, which will create docker images for tags
> poll the docker builder jobs every 2 hours

- charts/mirrorbits/templates/deployment.yaml
- charts/mirrorbits/templates/secret.yaml
- charts/mirrorbits/values.yaml
Uses https://hub.docker.com/r/maxmindinc/geoipupdate
I've tested this in the mirrorbits2 namespace in the cluster (now deleted), data is updated
> Add autoupdate of geoip data

- charts/mirrorbits/templates/secret.yaml
For some reason I don't quite understand the document separator was getting stripped out with the secrets the other way, moved it around and it works
> Fix mirrorbits chart

- charts/custom-distribution-service/values.yaml
This provides the 0.1-alpha-1 release of the custom distribution manager.
It has bug fixes for many of initial untagged release.
> custom distribution manager 0.1-alpha-1 release

- helmfile.d/cert-manager.yaml
Reverts jenkins-infra/charts#463
it broke cert-manager and looks like fun to fix, tried for last 30 mins...
> Revert "[updatecli] Update jetstack/cert-manager Helm Chart version to v1.0.1"

- CODEOWNERS
- charts/custom-distribution-service/Chart.yaml
- charts/custom-distribution-service/templates/deployment.yaml
- charts/custom-distribution-service/values.yaml
- charts/incrementals-publisher/Chart.yaml
- charts/incrementals-publisher/templates/deployment.yaml
- charts/incrementals-publisher/values.yaml
- updateCli/updateCli.d/custom-distribution-service.tpl
- updateCli/updateCli.d/incrementals-publisher.tpl
Hopefully I did this all right.
Updatecli should trigger a dependabot style PR whenever a new dockerhub tag and github release goes out.
Code owners should allow those people related to it to approve the release.
CC  @martinda @kwhetstone @sladyn98 @slide
> Codeowners and updatecli for incrementals and customize

- charts/mirrorbits/templates/deployment.yaml
Geoip data must exist before mirrorbits starts up
> Fix geoipdata race condition

- charts/jenkins/README.md
- charts/jenkins/requirements.lock
- charts/jenkins/requirements.yaml
- charts/jenkins/values.yaml
- config/default/jenkins-infra.yaml
- helmfile.d/jenkins-infra.yaml
- updateCli/updateCli.d/charts/stable-jenkins.tpl
I'm afraid its going to force upgrades and break releases at the same time
So maybe a dry run somehow?
needs: https://github.com/jenkins-infra/azure/pull/160
> Switch to jenkinci/ helm charts and add webhook ingress

- charts/ldap/templates/statefulset.yaml
- charts/ldap/values.yaml
When we switched to Letsencrypt certifificate managed by certmanager, we lost the ability to use ca.crt as it's not generate. 
By now I just hotfix by manually updating the secret with the valid ca.crt but my fix will be override next time certmanager generate renew the certificate.
In order to merge this, I have to be sure that we don't try to set ca.crt from jenkins-infra/ldap
Pull request coming
The current pull request solves 
```Warning  FailedMount             2s (x23 over 30m)     kubelet, aks-agentpool-34540872-vmss000000  MountVolume.SetUp failed for volume "tls" : references non-existent secret key: ca.crt```
> [ldap] Remove ca.crt from statefulset volume

- config/default/ldap.yaml
This is needed by Linux Foundation to authorize ldap connections from the new Jira location
> Authorize ldap connections from Linux Foundation

- charts/chatbot/values.yaml
Includes a fix for hosting process checking for GitHub usernames. See https://github.com/jenkins-infra/ircbot/pull/91
> [stable/chatbot] Update to latest ircbot tag

- config/default/jenkins-infra.yaml
mirrorbits is still build and publish on my own dockerhub organisation.
I just transfered this git repository -> https://github.com/jenkins-infra/docker-mirrorbits
> Add docker-mirrorbits to infra.ci

- updateCli/updateCli.d/jenkins-weekly-jdk11.tpl
Currently `updatecli` use the Jenkins maven repository to detect when a new version is available.
Unfortunately this method doesn't allow us to detect changelog automatically which Github Release does.
The downside of this is that Github release is usual late compared to the maven repository.
A run would look like this, with the changelog section displayed in the pull request.
```
########################
########################
SOURCE:
=======
✔ 'latest' github release version founded: jenkins-2.263
CHANGELOG:
==========
Release published on the 2020-10-20 14:33:17 +0000 UTC at the url https://github.com/jenkinsci/jenkins/releases/tag/jenkins-2.263
**Disclaimer**: This is an automatically generated changelog draft for Jenkins weekly …
```
> Switch updatecli jenkins weekly update definition from maven to github release

- updateCli/updateCli.d/jenkins-weekly-jdk11.tpl
Reverts jenkins-infra/charts#575 as the jenkinsci/jenkins changelog is not the source of truth which delays our jenkins update
> Revert "Switch updatecli jenkins weekly update definition from maven to github release"

- config/default/jenkins-infra.yaml
Currently, we are using a Mirrorbits docker image build and published to "olblak/mirrorbits" and the goal of this PR is to build and publish to jenkinsciinfra/mirrorbits from infra.ci
> Add docker-mirrorbits to infra.ci to build jenkinsciinfra docker images

- charts/chatbot/values.yaml
https://github.com/jenkins-infra/ircbot/pull/92 updated the Jira URL in the ircbot post Jira migration to Linux FDN infrastructure. This provisions the bot with the correct tag to include the updated URL in the default bot configuration
> [stable/chatbot] Update to ircbot with Jira URL update

- clusters/publick8s.yaml
For some reasons loki can't be updated, it complains about volume timeout issues but I couldn't anything wrong.
Considering that this service is not critical to the project, I prefer to temporarily disable it so we don't block other updates
```
Unable to attach or mount volumes: unmounted volumes=[storage], unattached volumes=[storage loki-token-jqdgx config]: timed out waiting for the condition
```
> Disable temporary loki management

- charts/mirrorbits/README.md
Match the other mirrors use of HTTPS.   The mirror in China is the only mirror using HTTP rather than HTTPS.
Confirmed that https://mirrors.tuna.tsinghua.edu.cn/jenkins/ is valid
https://groups.google.com/g/jenkins-infra/c/vm3FRYcsLA4/m/KIbM3HkbAgAJ reports that an attempt to redirect from https to http is denied.  Protocol downgrade is generally not allowed for redirects.
- fixes failure to install Debian package using the mirror in China
> README: Use HTTPS for mirror in China

- charts/chatbot/values.yaml
Updates the ircbot to the latest build with capability of opening the PR for repository-permissions-updater during hosting process.
- fixes # [INFRA-904](https://issues.jenkins.io/browse/INFRA-904)
> [stable/chatbot] Update to latest ircbot build

- PodTemplates.yaml
- updateCli/updateCli.d/updateCliPodTemplate.tpl
I moved olblak/updatecli docker image from dockerhub to ghcr.io to not be affected by Dockerhub rate limit
> Use updatecli docker image from ghcr.io instead of dockerhub

- config/default/mirrorbits.yaml
- helmfile.d/mirrorbits-database.yaml
- helmfile.d/mirrorbits.yaml
- updateCli/updateCli.d/charts/redis.tpl
We recently deploy a managed Redis database for get.jenkins.io so we don't need this Redis application running on publick8s cluster but it remains useful for local development so I am keeping the Helmfile configuration but I remove it from the cluster.
I am also increasing the size of the Mirrorbits database to 500GB as the current situation uses +-350GB
> Remove mirrorbits-database from default mirrorbits installation

- config/default/datadog.yaml
The default behavior for Datadog helm chart is to check the docker image tag used which IMHO is a very good idea but I need a little bit more time to build a custom docker image with an appropriate tag 
```
==> Linting /tmp/253114755/datadog/2.5.4/datadog/datadog/datadog
[ERROR] templates/: template: datadog/templates/_helpers.tpl:16:12: executing "check-version" at <semverCompare "^6.19.0-0 || ^7.19.0-0" $version>: error calling semverCompare: Invalid Semantic Version
```
> Do not check datadog docker image tag

- charts/jenkins/requirements.lock
- charts/jenkins/requirements.yaml
This is the latest 2.x chart before jumping to the 3.x release.  This
may also aid some of the issues updating jcasc config on infra/releases.
> chore(deps): bump jenkins chart from 2.7.1 to 2.19.0

- config/default/jenkins-infra.yaml
- config/default/jenkins-release.yaml
Attempt to fix, this PR hasn't been tested yet
```
2020-12-11 14:41:47.473+0000 [id=28]	WARNING	o.j.p.m.i.c.MatrixAuthorizationStrategyConfigurator#setPermissionsDeprecated: Loading deprecated attribute 'grantedPermissions' for instance of 'hudson.security.GlobalMatrixAuthorizationStrategy'. Use 'permissions' instead.
```
> Update jenkins jcasc permission

- config/default/jenkins-infra.yaml
Reverts jenkins-infra/charts#692
> revert: on jenkins-infra/charts only build branches that are PRs

- config/default/jenkins-infra.yaml
Add a new multibranch pipeline for repository jenkins-infra/docker-builder
- step of [INFRA-2860](https://issues.jenkins-ci.org/projects/INFRA/issues/INFRA-2860)
Enable CI for https://github.com/jenkins-infra/docker-terraform.
> Add a new multibranch job for jenkins-infra/docker-builder repo

- charts/nexus/requirements.lock
- charts/nexus/requirements.yaml
- helmfile.d/00-repositories.yaml
- helmfile.d/dex.yaml
- helmfile.d/nginx-ingress.yaml
- updateCli/updateCli.d/charts/dex.tpl
- updateCli/updateCli.d/charts/stable-nginx-ingress.tpl
- updateCli/updateCli.d/charts/stable-oauth2-proxy.tpl
This PR updates the URL location of the Helm stable repository, as per <https://helm.sh/blog/new-location-stable-incubator-charts/>.
It fixes the following CI error thrown by the "Lint" stage (<https://infra.ci.jenkins.io/blue/organizations/jenkins/k8smgmt/detail/master/8761/pipeline>):
```text
Adding repo stable https://kubernetes-charts.storage.googleapis.com
in clusters/publick8s.yaml: in .helmfiles[2]: in ../helmfile.d/nginx-ingress.yaml: the following cmd exited with status 1:
/usr/local/bin/helm helm repo add stable https://kubernetes-charts.storage.googleapis.com
Error: looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden
script …
```
> Update Helm Stable's repository URL to the new location

- charts/jenkins/values.yaml
- config/default/jenkins-infra.yaml
this will also exclude PRs labels as 'on-hold' to stop building some of
the older PRs for that repository.
Currently all branches (&PRs) for jenkins-infra/charts are being built.
This PR limits them to be master/main & PRs only.  PRs with the label
`on-hold` are also excluded.
> chore: for jenkins-infra/charts build only master and PRs

- config/default/jenkins-infra.yaml
Common work with @olblak and @garethjevans around discovering, building and triggering jobs based on GitHub tags for the "docker-*" repositories of the infra.ci.jenkins.io instance.
It allows this instruction to work as expected: https://github.com/jenkins-infra/pipeline-library/blob/510aaa9f9d228fc29a1097b6086ff9038ba695d3/vars/buildDockerAndPublishImage.groovy#L156
N/A
N/A
> Infra Instance: Add github tag discovery and build strategy for docker-* jobs

- charts/mirror/values.yaml
- config/default/mirror.yaml
Make mirror.azure.jenkins.io  reachable from the internet but only allow connection from get.jenkins.io and pkg.jenkins.io
> Add public IP to mirror.azure.jenkins.io

- charts/mirror/values.yaml
- updateCli/updateCli.d/mirror-rsyncd.tpl
We are working to use git tag for docker image name but at least for the moment, I am going to switch to image digest so we keep the rsync image up to date.
> Switch rsyncd to digest and add updatecli config

- updateCli/updateCli.d/jenkins-weekly-jdk11.tpl
Detect jenkins version update using github releases instead of maven releases, the purpose is have access to changelog information. Output looks like 
```
+++++++++++
+ PREPARE +
+++++++++++
Cloning git repository: https://github.com/jenkins-infra/charts.git in /tmp/updatecli/jenkins-infra/charts
Enumerating objects: 23, done.
Counting objects: 100% (23/23), done.
Compressing objects: 100% (21/21), done.
Total 5787 (delta 8), reused 8 (delta 2), pack-reused 5764
Fetching remote branches
+++++++
+ RUN +
+++++++
########################
########################
SOURCE:
=======
✔ 'latest' github release version founded: jenkins-2.274
CHANGELOG:
==========
Release published on the 2021-01-05 18:41:56 +0000 UTC at the url https://github.com/jenkinsci/jenkins/releases/tag/jenkins-2.274 …
```
> Detect jenkins version update using github releases

- config/default/jenkins-infra.yaml
Allow tag builds (as tag discovery is working correctly since #740 ) for the `docker-*` builds.
Filtering out by names within the repository was implicitly filtering out the tag names.
N/A
> Bugfix 🐛: Stop filtering branch names when scanning docker-* repos 

- charts/mirrorbits/README.md
Based on the recent work done on adding a read-only rsync server to our mirror chart.
azure.mirror.jenkins.io is now ready to be added to get.jenkins.io.
This PR is here to document that manual step that I run.
> Azure mirror

- updateCli/updateCli.d/jenkins-weekly-jdk11.tpl
It's not possible to automatically differentiate a weekly and a stable release from the latest GitHub release.
While it was useful to get the GitHub release changelog, switching back to the maven repository is more reliable
-> https://github.com/jenkinsci/jenkins/releases
> Use maven repository to get latest jenkins weekly release

- charts/mirrorbits/README.md
We don't really need the public endpoint
> Use private rsync url

- config/default/jenkins-infra.yaml
The PR #740 introduces a build strategy setup to allow tag triggered build (and not only "tag discovery").
But we forgot to add the "normal branch" and "trusted PRs" branch as part of this build strategy, which resulted in Jenkins picking up the changes, but not starting any build, with the message `No automatic build triggered for xxx` in the Multi-Branch Scanning logs.
> Fix build strategy to allow branch and trusted PRs for Docker Builds'GH org scanning for infra.ci

- config/default/jenkins-infra.yaml
Co-Authored with @olblak 
Switch GitHub operations from token to Github App
Please note that the SOPS credentials `GITHUB_APP_ID`and `GITHUB_APP_PRIVATE_KEY` (cc @olblak )
- fixes [INFRA-2877(https://issues.jenkins-ci.org/projects/INFRA/issues/INFRA-2877)
> Switch Jenkins Infra's GitHub operation to a GitHub App (INFRA-2877)

- charts/jenkins/values.yaml
With the latest helm chart update, the k8s secret is not mounted anymore.
This configure ensure that secrets are available in the directory /var/jenkins_secrets
This pull request affects two services
1. release.ci.jenkins.io
2. infra.ci.jenkins.io
.
> Specify jenkins_secrets

- charts/jenkinsio/templates/nginx-configmap.yaml
https://infosec.mozilla.org/guidelines/web_security#x-frame-options
Although the site doesn't use iframes or have accounts, various security scanners and their associated operators continue to complain about this.
Adds the X-Frame-Options: DENY header by default to nginx pages. Various script kiddies continue to spam the Jenkins Security Team about this, and it's harmless to enable.
@daniel-beck
> Add X-Frame-Options DENY to stop the pestering

- Jenkinsfile_k8s
As per https://www.jenkins.io/doc/book/pipeline/syntax/#when, the goal is to NOT fail the pipeline when we need to apply configuration from helmfile/values to the cluster.
The idea of this PR is to make sure that updateCli only runs on the daily routine.
> ✨ Execute the updateCli's pipeline steps only when the pipeline is triggered by the daily cron routine

- updateCli/updateCli.d/docker-mirrorbits.tpl
In the current state it checks for the image jenkinsciinfra/mirrorbits:latest instead of jenkinsciinfra/mirrorbits:<version_retrieved_from_source>
> Fix updatecli mirrorbits configuration

- README.md
- REVIEW_GUIDELINES.md
- config/default/jenkins-infra.yaml
- Add 4 new credentials to the Jenkins controller at <https://infra.ci.jenkins.io> to provide AWS API keys for terraform usage
- A bit of documentation update along the way
> [INFRA-2891] Add the Terraform's AWS API keys credentials to infra.ci.jenkins.io

- updateCli/updateCli.d/datadog.tpl
The Datadog configuration file path has been changed in this PR #891 but I forgot to update the updatecli configuration that bump the docker image digest 
> Fix updatelci datadog config path

- config/default/jenkins-infra.yaml
The goal of this PR is leverage the HTTP/504 error on infra.ci, during the user loggin phase, that are reported as "read timeout while connecting to LDAP".
These settings come from the following pages:
- https://support.cloudbees.com/hc/en-us/articles/235438387-Cannot-make-my-LDAP-configuration-to-work
- https://downey.io/blog/kubernetes-ephemeral-debug-container-tcpdump/
> Fine tune the LDAP plugins connection's pooling 

- config/default/datadog/conf_http_mirror.yaml
The mirror configuration is not loaded in datadog because of this typo
> Insert space between yaml key-value

- helmfile.d/traefik.yaml
This PR follows up https://github.com/jenkins-infra/charts/pull/867.
The goal is to finish the Traefik Ingress installation for the public part. Some steps are run manually to escape the "feedback loop hell", but the goal is to have the charts and its setup ready to go once boostraped.
It introduces the following changes:
* Each traefik ingress is now installed in its own namespace instead of `kube-system` (why: improve isolation)
* Fix on the public load balancer setup to specify the correct IP
> Fix/traefik: public ingress + private ingress

- Jenkinsfile_k8s
Reference: https://github.com/jenkins-infra/charts/pull/882#issuecomment-784291726  (and idea from @jglick)
This PR makes the comment, from the bot showing the helmfile diffs in PRs, collapsed by default.
> Chore: make the bot comment about diff to be collapsed to ease reviews

- charts/jenkins/values.yaml
- config/default/jenkins-infra.yaml
* Install the plugin [CloudBees Health Advisor](https://plugins.jenkins.io/cloudbees-jenkins-advisor/)
* Configure the plugin on Infra.ci to obtain feedback on the instance configuration
* Disable the administrative monitor  of the plugin, to avoid annoying message if it is not configured
The rationale behind using the plugin is to start analysis of the JVM configuration for infra.ci, in relation to the LDAP issues.
> Infra-ci: Enable CloudBees Health Advisor plugin

- helmfile.d/traefik.yaml
This PR follows up #903 and #867 .
The service annotations used for the traefik ingresses (both private and public) were invalid: if a string is not used for `service.beta.kubernetes.io/azure-load-balancer-internal` (we were using a boolean), then all the other annotations of kind `service.beta.kubernetes.io/azure-load-balancer-*` are ignored.
It resulted in:
- The Public IP for the `public-traefik` LB service was not associated to the correct resource group (was: `mc_prodpublick
8s_prodpublick8s_eastus2` while it should be `publick8s`)
- The LB service for `private-traefik` is not in the expected tiers, neither it is private
> Fix traefik ingresses services annotations

- Jenkinsfile_k8s
- config/default/jenkins-infra.yaml
The goal of this PR is to improve the resources usage and performance of infra.ci:
- After #908 , we received a first report from Health Advisor that points to <https://support.cloudbees.com/hc/en-us/articles/204859670-Java-Heap-settings-best-practice>. This PR adds the proposed java opts flags adapted for the JDK 11
- Set the initial resources requested for Jenkins to the same as the limit to ensure that the JVM has enough resources at startup to ensure a fast and efficient startup. The goal is to start from there and then improve monitoring of the JVM usage to ensure that we can add jobs efficiently, restart the instance fast, and diagnose the "LDAP" timeout issues.
- After #908 where an administrative monitor is dismissed as code, this PRs adds a new system config to dismiss another …
> Tune JVM for infra.ci: resources and JAVA_OPTS

- config/default/jenkins-infra.yaml
Scope: states for aws (ci and production accounts).
Requires https://github.com/jenkins-infra/charts-secrets/pull/17 to be merged to allow accessing the secrets
> [INFRA-2891] Infra CI: add S3 terraform backend configs for aws as credentials 

- config/default/jenkins-infra.yaml
> Infra CI: Windows pods should use the same image as release.ci

- config/default/jenkins-infra.yaml
This PR fixes the infra.ci issues when using LDAP authentication.
- Define a search base explictely to ensure that the LDAP requests emitted when authenticating are not HUGE. This settings comes from ci.jenkins.io's JCasc export.
- Switches the RBAC setting from the group `all` to the group `authenticated` to avoid HUGE requests on the LDAP
- Nice to have: fine tune the headdump in JAVA_OPTS
> [NFRA-2903] Hotfix: fix infra.ci LDAP settings

- config/default/jenkins-release.yaml
This PR cherry-picks the recents changes applied to infra.ci, into release.ci:
* Fix LDAP settings: https://github.com/jenkins-infra/charts/pull/968
* Java Opts and resources: #911 
* Advisor activation: #908
> Cherry-pick changes from infra.ci to release.ci to fix LDAP issues

- config/default/jenkins-infra.yaml
It looks like that in #993 , I failed to specify the option `org.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecDecorator.websocketConnectionTimeout` in the correct location for infra.ci.
It was underlined by recent builds which where complaining about the value being set to the default of `30`.
The goal of this PR is to decrease the amount of failure due to this error.
> fix: set the websocketConnectionTimeout option on the correct key for infra.ci

- charts/jenkins/values.yaml
- config/default/jenkins-infra.yaml
- updateCli/updateCli.d/jenkins-weekly-jdk11.tpl
This PR switches infra.ci to use the prebuilt docker image for jenkins (including all plugins) that is defined at: https://github.com/jenkins-infra/docker-jenkins-weekly
> chore: switch infra.ci to use jenkinsciinfra/jenkins-weekly image

- config/default/jenkins-infra.yaml
This is to allow the kubernetes-credential-provider plugin to read the secrets from kubernetes
> chore: allow infra.ci to read secrets

- config/default/jenkins-infra.yaml
- config/default/jenkins-release.yaml
This is to remove the plugin conflicts when copying plugins from the shared volume
> chore: enable overwrite plugins on release/infra

- config/default/jenkins-release.yaml
Using the default value set to 30 leads to connection tieout errors on infra.ci
> Increase websocketConnectionTimeout for release.ci

- updateCli/updateCli.d/charts/captain-hook.tpl
Fix updatecli configuration for captain hook to remove warning about deprecating fields
> Fix updatecli configuration for captain hook 

- charts/jenkinsio/templates/deployment.yaml
- charts/jenkinsio/templates/zh-deployment.yaml
- charts/jenkinsio/values.yaml
- updateCli/updateCli.d/nginx.tpl
This pull request split the jenkins.io nginx configuration in two, the goal is to prepare the land for this pull request https://github.com/jenkins-infra/jenkins.io/pull/4233 so we can update the English and Chinese docker image separately.
> Split jenkins nginx configuration per website

- charts/jenkinsio/templates/deployment.yaml
- charts/jenkinsio/templates/nginx-configmap.yaml
- charts/jenkinsio/values.yaml
- config/default/jenkinsio.yaml
- updateCli/updateCli.d/nginx.tpl
Need to delay the use of the docker image until we have the automation running that will apply the change to the helm chart and push that change to the central repository.
Proposal to revert has been approved by olblak in a private channel.
This reverts commit 5e8aaeaff71c39e9008332d705dbdf5648bebf4f.
> Revert "jenkinsio helm chart used a self-contain docker image for the default website (#1070)"

- config/default/jenkins-infra.yaml
A breaking change was introduced by the 1.57 ec2-plugin update:
https://github.com/jenkinsci/ec2-plugin/pull/492#pullrequestreview-605360930
> fix: remove a deprecated configuration directive in jenkins infra.ci

- config/default/jenkins-infra.yaml
The goal of this PR is to ensure that we do not keep the "orphan children" for multibranch pipeline jobs on infra.ci.
These childrens are GitHub branches, tags and PRs, and the current config marks them immediatly as "unused" when removed on GitHub (for instance: when a PR is merged), but the jobs are still kept and stored on the underlying filesystem.
> feat: improve infra.ci jobs children cleanup

- config/default/jenkins-infra.yaml
This PR add the following changes to infra.ci.jenkins.io, as part of https://issues.jenkins.io/browse/INFRA-2921:
* Add a new GH organization scanning "Terraform Builds" to manage both `aws` and `datadog` pipelines
* Remove the standalone multibranch project `aws`
* Switch as much Job-DSL directives as possible of "Terraform Builds" and "Docker Builds" from "XML raw traits" to native Job-DSL (yeah, its not on all but the 2 are read/write by this PR so treating it right now)
* Add the 3 datadog secrets
> [INFRA-2921] Migrate datadog's infra as code to infra.ci

- config/default/mirrorbits.yaml
While reviewing mirrorbits resource usage on publickk8s, I saw that the third containers were at their max capacity, because of the IO constraint on the azure file storage below, I would like to first increase the CPU/memory instead of adding more mirrorbits containers.
> Double mirrorbits container usage limit

- config/default/jenkins-infra.yaml
Service infra.ci.jenkins.io
- Fight against alert fatigue
- Performances
- Security
- Alert fatigue: Avoid polluting logs with "SEVERE" error message which are not sever 
- Performances: ensure we don't persist data in `JENKINS_HOME` when not needed to allow faster restart of the service and less I/O usage (cost and perf)
- Security: ensure that we control "who" can execute a pipeline on infra.ci and that the configuration are state of the art and well managed to avoid config. shift
This PR introduces the following changes (can be reviewed by commit):
* Switch trigger  for multibranch  from pollSCM to periodicFolderTrigger (no more SEVERE, same interval). The errors where caused by the fact that pollSCM does not apply to multibranch kind.
* Add an ID for multibranch each job to avoid …
> Cleanup infra.ci's configuration

- config/default/jenkins-infra.yaml
This PR is a follow up of #1123 (read it for context) and introduces the following breaking change on infra.ci's configuration:
- Factorize all multibranch jobs on a single loop-based configuration
- Factorize all gh-org scanning jobs on a single loop-based configuration (keeping 2 separated even if the same organization)
Please note that the "K8S management" job is gonna be re-created under a new URL, which is the breaking change. The older one has been renamed and disabled, and should be deleted only after 1 week (to allow rollback if required)
> (breaking) Finish infra.ci's DSL cleanup

- clusters/publick8s.yaml
- helmfile.d/nginx-ingress.tmp.yaml
The goal of this pull request is to deploy two temporary nginx ingress controllers using the new helm chart location.
More details in this [document](https://hackmd.io/cH4rbENeSOGLHD3rAgnXqQ)
> Deploy temporary nginx controller

- config/default/jenkins-infra.yaml
The build on infra.ci of the `jenkins.io` is a tentative for a new "way" of doing it (by building Docker images).
But alas, we had to rollback this "new" way time to fix the failing steps.
This commit remove the job as we are not currently working on it and because it generates false positive Github checks for contributors.
cc @daniel-beck
> fix: Disable jenkins.io job in infra.ci as we rollbacked the deployment process

- helmfile.d/nginx-ingress.tmp.yaml
Context: https://hackmd.io/cH4rbENeSOGLHD3rAgnXqQ
* Enable high availability by ensuring 2 replicas. Even with a well defined Kube deployment system which ensures a proper migration from 1 pod to another (always 1 up), there can be "hard failures", so we set the replicas to 2.
** Impact: it adds a new resource "PodDisruptionBudget" for each of the 2 controllers
* Define the same "ingressclass" for the 2 new (tmp)ingress-nginx controllers for a seamless migration
> Feat: prepare migration from (legacy)nginx-ingress to (tmp)ingress-nginx

- config/default/jenkins-infra.yaml
The changes from #1133 were overriden by #1126 . Still not sure how this could have happened (but since we work with squash merged PR, the conflict management behavior can be the culprit here)
> fix: revert infra.ci config to remove jenkins.io builds

- Jenkinsfile_k8s
- helmfile.d/00-repositories.yaml
- helmfile.d/nginx-ingress.tmp.yaml
- helmfile.d/nginx-ingress.yaml
After #1137 , the "lint" step failed for the new nginx ingress, because of the repository name which was still `stable`.
> Bugfix: factorize nginx helm repo to fix main build

- config/default/jenkins-infra.yaml
- Secure the initial SSH connection to ARM Linux agents by checking the SSH fingerprint against the EC2 console (slower agent startup but protect ANY kind of MitM)
- Override the expected tmp dir on Windows agents (ref. https://issues.jenkins.io/browse/JENKINS-50308) so it does not hangs when trying to search for the directory `/tmp`, because EC2-plugin thinks that SSHD=Unix
- Allocation settings
> fix: configuration of EC2 agents on infra-ci to have windows agent working as in ci.jenkins.io

- config/default/ldap.yaml
Please note that this new public IP is an elastic IP so we can reboot trusted.ci whenever we need
> fix: update public IP of trusted to allow incoming ldap access

- config/default/jenkins-infra.yaml
- config/default/jenkins-release.yaml
Following the weekly release 2.295 which failed with Windows agents, the default pod configuration for the windows Kubernetes agents had to be fixed.
It's a follow up of the 2 following changes on the release specific Pod Templates:
- https://github.com/jenkins-infra/release/commit/2d1f11145a1490e116f323fa7fdd19877e6917bc
- https://github.com/jenkins-infra/release/commit/92dde3d7af5f869a31644a0ea65d27fe0333eacd
> Fix: configuration of Windows Kubernetes agents for infra.ci and release.ci

- config/default/jenkins-infra.yaml
The PR #1217 introduced a syntax error, because the key `security` has to be part of the content (not only the name).
> Fix: missing security top-level key syntax error on JCasc configuration for infra.ci

- charts/mirrorbits/README.md
After some testing with @MarkEWaite , it appears that a score of -1 slightly favor xmission over archives.jenkins.io which is not what we want.
What we want is to be redirected to be redirected to archives.jenkins.io only if no other mirrors are available.
> Update mirrorbits documentation for archives.jenkins.io

- helmfile.d/falco.yaml
The principal branch fails with the following error:
```
Upgrading release=falco, chart=falco/falco
FAILED RELEASES:
NAME
falco
in clusters/publick8s.yaml: in .helmfiles[6]: in ../helmfile.d/falco.yaml: failed processing release falco: command "/usr/local/bin/helm" exited with non-zero status:
PATH:
/usr/local/bin/helm
ARGS:
0: helm (4 bytes)
1: upgrade (7 bytes)
2: --install (9 bytes)
3: --reset-values (14 bytes)
4: falco (5 bytes)
5: falco/falco (11 bytes)
6: --version (9 bytes)
7: 1.13.1 (6 bytes)
8: --wait (6 bytes)
9: --timeout (9 bytes)
10: 100s (4 bytes)
11: --atomic (8 bytes)
12: --create-namespace (18 bytes)
13: --namespace (11 bytes)
14: falco (5 bytes)
15: --values (8 bytes)
16: /tmp/helmfile839262083/falco-falco-values-598dfcb845 (52 bytes)
17: --history-max (13 bytes)
18: 10 …
```
> fix: increase falco timeout

- config/default/ldap.yaml
Those two IPs were shared from Jfrog and are currently working.
I need confirmation from Jfrog ops team that we don't need other IPs.
Once this PR is merged, we can re-enabled the job on infra.ci
> Update JFrog allowed IP

- config/default/datadog/datadog.yaml
This PR requires the [AKS Upgrade to 1.19.x](https://hackmd.io/EDpvZx9ZS2GWgHHqWFRDfQ).
Unlike falco, the support of both docker engine and containerd does not work (the agent always fall back to containerd when both settings `dockerSocketPath` and `criSocketPath` are specified ) (ref. https://github.com/helm/charts/tree/master/stable/datadog#cri-integration).
So let's assume the following scenario: 
- Applying this change just before the upgrade, datadog agents will fail
- Start the upgrade
- After the upgrade, agents should start successfully without any human intervention
Hence the "on hold" for now
> breaking: switch datadog agents to ContainerD instead of Docker

- config/default/datadog/datadog.yaml
Main references that helped me for this:
* https://github.com/DataDog/integrations-core/issues/2582#issuecomment-656610443
* https://github.com/DataDog/helm-charts/blob/master/charts/datadog/README.md
> fix: configure datadog agent to use TLS for dialing with kubelet

- config/default/datadog/datadog.yaml.gotmpl
- config/publick8s/datadog.yaml
- helmfile.d/datadog.yaml
The principal branch is broken since the AKS 1.19 upgrade, because of #1258 and #1265 .
The main reason is that the values specified in an element of `helmfiles` are not merged into the values of a given release.
As such, the attributes `clusterName` defined in `config/publick8s/datadog.yaml` and `config/cik8s/datadog.yaml` was not used in the deployments.
This "template/merging" hell as been consequential in #1265 because it applied the publick8s' (AKS) specific settings for the kubelet (path of the cacert + hostname used instead of IP) to cik8s (EKS), making the deployment failing on cik8s.
This PR tries to hack around by defining the "default values" at release level as a go template, so it can dynamically retrieve the values from higher level.
Helmfile seems to provide a bunch of …
> fix: use templating for datadog to allow cluster-values to be used.

- clusters/cik8s.yaml
- config/cik8s/autoscaler.yaml
- helmfile.d/autoscaler.yaml
- updatecli/updatecli.d/charts/autoscaler.tpl.disable
This PR installs the official cluster autoscaler chart on `cik8s` , our EKS cluster for ci.jenkins.io.
It's part of INFRA-2918 to ensure that are enough resources provided to ci.jenkins.io.
Please note that
- The installation has been done manually one time for boostrap. it means that the initial helm diff might be empty (or almost empty).
- The updateCLI config is disabled to avoid failing the initial build (has it would fail to find the YAML files). Expect a PR next week to enable updateCLI fully.
> feat: install autoscaler to cik8s + add updatecli config but disabled [INFRA-2918]

- config/default/jenkinsio.yaml
This PR introduces a new Header `X-Content-Type-Options` set to the value `nosniff` for all the ingress rules on the cluster `publick8s` (AKS), including jenkins.io, as per INFRA-2998.
> feat: [jenkins.io] Set header "X-Content-Type-Options" to nosniff [INFRA-2998]

- helmfile.d/00-repositories.yaml
- helmfile.d/grafana.yaml
- helmfile.d/loki.yaml
- helmfile.d/promtail.yaml
- updatecli/updatecli.d/charts/grafana-loki.tpl
- updatecli/updatecli.d/charts/grafana-promtail.tpl
When applying the charts for promtail and loki, helmfile reports a warning that the charts are deprecated.
It appears that the chart repository have been moved since 12/2020 (as per the admonition on https://grafana.com/docs/loki/latest/installation/helm/).
This PR ensures that the correct chart repository is defined once so that both promtail and loki are using it.
Please note that it's the same repository as grafana.
This change made mandatory to bump the 2 charts for loki and promtail as the "old" versions we were using does not exist on the new repository.
Please note that the diff for promtail isconsequent as the bump is huge.
> feat: Bump loki and promtail to latest version + move the central grafana chart repository 

- charts/uplink/values.yaml
- config/default/accountapp.yaml
- config/default/captain-hook.yaml
- config/default/custom-distribution-service.yaml
- config/default/incrementals-publisher.yaml
- config/default/javadoc.yaml
- config/default/jenkins-infra.yaml
- config/default/jenkinsio.yaml
- config/default/mirrorbits.yaml
- config/default/plugin-site.yaml
- config/default/reports.yaml
- config/default/uplink.yaml
- helmfile.d/nginx-ingress.yaml
This PR comes from INFRA-2998 and aims at enabling HSTS globally on the public ingress of the cluster `publick8s` by default, unless disabled per ingress rules.
It reverts the content of https://github.com/jenkins-infra/charts/pull/98 as tipped by @timja , now that we have HTTPS mirrors (and that the charts allows disabling HSTS per ingress rule).
The HSTS values are the default recommended per https://hstspreload.org/.
⚠️ Please note that this PR, once merged and deployed, might break some usages (clictracking, stats, cross sites). It is a non easy topics, so if we breaks usages, we'll have to avoid disabling it and instead fine tune (per website, or header values).
=> It means that a torough reveiw is required
> feat: enable HSTS by default on all the publick8s cluster

- config/default/jenkinsio.yaml
> fix: correct custom HTTP header syntax for jenkins.io [INFRA-2998]

- config/default/promtail.yaml
Loki client configuration key changed in the recent version of the promtail helm chart.
As defined [here](https://github.com/grafana/helm-charts/blob/e13e3b4971c5f2f9da908c0cb8db22bcc818f0ba/charts/promtail/values.yaml#L235) the URL doesn't match our Loki configuration.
I manually applied the change to the production server and we can now look at the data on our Grafana instance
> Update promtail loki configuration

- helmfile.d/keycloak.yaml
Apparently, 5 minutes is not enough for keycloak to be ready.
> Increase timeout when deploying keycloak

- config/default/ldap.yaml
* Allow ldap connections from the new public8s IP range
* Allow inbound connections from the *temporary* confluence backup machine
> Add allowed IP to ldap service firewall

- config/default/jenkins-infra.yaml
Related to https://github.com/jenkins-infra/packer-images/pull/85
Tests shows that the secrets + jobs are created with the expected properties.
AWS builds are successful, for Azure I'll have to fine tune the credential part, but that would take place either at the secret level or at service principal level: the PR here is ready to be merged.
> feat: migrate the packer-image project to infra.ci

- config/default/jenkins-infra.yaml
I mixed up (in #1444) the "secret ID" and "client ID" for the Service Principal account `packer`. This PR fixes the setup (and the secret has been updated in the private repo).
Build https://infra.ci.jenkins.io/blue/organizations/jenkins/packer-images/detail/PR-85/5/pipeline/193 was triggered manually to test the "new" credential value, to ensure that it works.
> fix: update the packer azure SP client_id credential setup for infra.ci

- charts/accountapp/values.yaml
It appears that we didn't update this image for a while but it's needed for https://github.com/jenkins-infra/account-app/pull/133
> Update accountapp docker image to the latest one

- charts/accountapp/values.yaml
Well, I forgot this one
This PR is another attempt to fix
> Update jira url used by accountapp

- config/default/keycloak.yaml
* Add connection affinity to avoid authentication being broken when redirected to the second pod
* Increase cpu allocated to keycloak, according to grafana memory doesn't seem to be an issue
> Add keycloak affinity based on cookies

- config/default/datadog/datadog.yaml.gotmpl
- helmfile.d/datadog.yaml
This PR introduces the following non functional changes:
- Update a deprecated directive for datadog chart (see commit message for details)
- increase chart timeout to avoid erroring when cik8s is heavily scaling
> chore [datadog] refinements and deprecation

- config/default/wiki.yaml
- helmfile.d/wiki.yaml
> fix(wiki) bump chart to allow /status monitoring + set to 2 replicas

- clusters/cik8s.yaml
- config/cik8s/autoscaler.yaml
- config/cik8s/aws-node-termination-handler.yaml
- helmfile.d/aws-node-termination-handler.yaml
- The autoscaler charts is "forced" to the tiny instances that are small, cheap and always available (ondemand pool only for such use cases)
- A new charts is installed to cleanly react on spot de-allocation
> feat(cik8s) ensure that spot instance are autoscaled and cleaned up safely (INFRA-3104)

- config/jenkins-infra-additional.yaml
- config/jenkins-infra.yaml
- helmfile.d/jenkins-infra.yaml
- helmfile.d/jenkins-release.yaml
Note: needed manual modification of the 'meta.helm.sh/release-name' annotation from 'jenkins-infra' to 'jenkins-infra-additional' to pass the 'helmfile diff' for these existing resources:
- ServiceAccount
- Secret (empty)
- ClusterRoleBinding
Followup of https://github.com/jenkins-infra/charts/pull/1685
> feat: use official jenkins chart for jenkins-infra too

- clusters/publick8s.yaml
ingress.kubernetes.io/configuration-snippet annotation
https://github.com/kubernetes/ingress-nginx/issues/7837#issuecomment-969750366
> fix(jenkinsio) use last chart version to get rid of nginx's

- config/jenkins-infra.yaml
This PR applies the tips from @vlatombe (❤️ ) and is the outcome of a mob programming session with @lemeurherve @jmMeessen @pilere
> Fix(infra.ci.jenkins.io) ensure that the default pod templates can be inherited

- updatecli/updatecli.d/charts/jenkins-kubernetes-agent.yaml
Fixes the error noticed in [updatecli logs](https://infra.ci.jenkins.io/blue/organizations/jenkins/charts/detail/main/1478/pipeline/117#step-118-log-941):
```
updateChartVersion
------------------
ERROR: Something went wrong in target "updateChartVersion" :
ERROR: No line matched in the file "/tmp/updatecli/jenkins-infra/charts/clusters/publick8s.yaml" for the pattern "chart: jenkins-infra\\/jenkins-kubernetes-agents((\\r\\n|\\r|\\n)(\\s+))version: .*"
```
> fix: correct helmfile target for jenkins-kubernetes-agent updatecli manifest

- config/keycloak.yaml
We're scaling down Keycloak because the session sharing isn't working as intended.
> fix: scaledown keycloak from 2 to 1 replica

- clusters/publick8s.yaml
Reverts jenkins-infra/charts#1798 until this PR is merged: https://github.com/codecentric/helm-charts/pull/514
> Revert "[updatecli] Bump keycloak helm chart version"

- config/jenkins-infra.yaml
I didn't know if it should be added to the docker images folder, but err'd with the general list thingie.
Mostly to support https://github.com/jenkins-infra/jenkins.io/pull/4782
> Add jenkins.io to infra.ci

- clusters/prodpublick8s.yaml
This PR fixes #1862 by adding the following changes:
- Enable automatic management of the service "plugin-site-issues" again (in `prodpublick8s`)
- Ensures that secrets had been updated with the correct YAML keys:
- https://github.com/jenkins-infra/kubernetes-management/issues/1862#issuecomment-1003029019
- https://github.com/jenkins-infra/charts-secrets/commit/f42a9e08212b40f7cbc73dc5d7270a4cd89912f5 (private repository)
> fix(plugin-site-issues) enable (again) plugin-site-issues management

- config/jenkins-infra.yaml
This PR ensures that:
- Github checks are generating correct links
- That no UI redirects are failing to redirect user
- That pipeline_library can deploy docker images under the `jenkinciinfra` instead of `jenkins4eval`
> fix(infra.ci) use the correct Jenkins URL

- clusters/temp-privatek8s.yaml
- Follows up #1867 to ensure that ACME TLS certificates are generated for ingresses
- Installed manually at first
- Validated with infra.ci
> feat(temp-privatek8s) add a cert-manager / acme service to generate certificates

- clusters/temp-privatek8s.yaml
- config/public-nginx-ingress.yaml
- config/temp-privatek8s/public-nginx-ingress.yaml
- Ingress controller installed manually one time:
- Created a "Public IP" in Azure, and a DNS record pointing to this IP
- Defined the `loadBalancerIP` of the ingress's config to this predefined IP
- Installed the controller
Please note that there is also a cleanup of the prodpublick8s annotations
> Feat: add a public nginx ingress to temp-privatek8s

- updatecli/updatecli.d/charts/accountapp.yaml
- updatecli/updatecli.d/charts/acme.yaml
- updatecli/updatecli.d/charts/certmanager.yaml
- updatecli/updatecli.d/charts/chatbot.yaml
- updatecli/updatecli.d/charts/codecentric-keycloak.yaml
- updatecli/updatecli.d/charts/custom-distribution-service.yaml
- updatecli/updatecli.d/charts/datadog.yaml
- updatecli/updatecli.d/charts/env-jenkins-release.yaml
- updatecli/updatecli.d/charts/falco.yaml
- updatecli/updatecli.d/charts/grafana-loki.yaml
- updatecli/updatecli.d/charts/grafana-promtail.yaml
- updatecli/updatecli.d/charts/grafana.yaml
- updatecli/updatecli.d/charts/incrementals-publisher.yaml
- updatecli/updatecli.d/charts/javadoc.yaml
- updatecli/updatecli.d/charts/jenkins-additional.yaml
- updatecli/updatecli.d/charts/jenkins-infra-keycloak.yaml
- updatecli/updatecli.d/charts/jenkins-wiki-exporter.yaml
- updatecli/updatecli.d/charts/jenkins.yaml
- updatecli/updatecli.d/charts/jenkinsio.yaml
- updatecli/updatecli.d/charts/ldap.yaml
- updatecli/updatecli.d/charts/mirrorbits.yaml
- updatecli/updatecli.d/charts/nginx-ingress.yaml
- updatecli/updatecli.d/charts/plugin-site-issues.yaml
- updatecli/updatecli.d/charts/plugin-site.yaml
- updatecli/updatecli.d/charts/prometheus.yaml
- updatecli/updatecli.d/charts/reports.yaml
- updatecli/updatecli.d/charts/traefik.yaml
- updatecli/updatecli.d/charts/uplink.yaml
- updatecli/updatecli.d/charts/wiki.yaml
- updatecli/updatecli.d/docker-images/404.yaml
This PR aims at fixing updatecli process after the 2 major changes:
- Renaming `clusters/publick8s.yaml` to `clusters/temp-privatek8s`
- Adding `cluster/temp-privatek8s`
> Fix: updatecli for temp-privatek8s + existing

- config/incrementals-publisher.yaml
It explains why the 1.4.2 of hte incremental publisher webapp wasn't released despite the helm-chart 0.4.4 correctly deployed.
It's a remnant of a cleanup of the repository, and we to apply the same change (e.g. removing from the helm'fils values) on all of our images
> feat(incremental) Delegate Docker image version to the charts's default value

- config/ext_jenkins-infra.yaml
Follows up #1907 
Tested in "live" production by editing the configmap
> fix(infra.ci) correct JobDSL to allow jenkins.io to deploy to netlify

- config/ext_jenkins-infra.yaml
Adding a template for a amd86 vm with docker
This will close : https://github.com/jenkins-infra/helpdesk/issues/13
> feat(infra.ci) add agent VM template for amd64 (to provide Docker Engine)

- config/ext_jenkins-infra.yaml
fix the crashloopbackoff caused by #1920 
jenkins infra.ci pod logs 
```console
while parsing a block mapping
in /var/jenkins_home/casc_configs/agent-settings.yaml, line 67, column 11:
- ami: "ami-07096113cf2ec6768" # h ... 
^
expected <block end>, but found '<block mapping start>'
in /var/jenkins_home/casc_configs/agent-settings.yaml, line 68, column 13:
amiOwners: "200564066411"
```
> infra.ci: fix indentation of agent-settings in jenkins config as code

- updatecli/updatecli.d/docker-images/nginx.yaml
This change is allowed because of the release of https://github.com/updatecli/updatecli/releases/tag/v0.18.3 that fixed the filtering of git tag resources.
> chore(updatecli) ensure that only nginx stable version is tracked 

- config/ext_jenkins-release.yaml
In order to complete #1949 adding a new ssh key and renaming some infra residues
>  feat(release.ci.jenkins.io) add agent VM templates for Linux and Windows as amazon ec2 instances #1949  new key and renaming

- clusters/prodpublick8s.yaml
- config/ext_jenkins-release.yaml
- updatecli/updatecli.d/charts/jenkins.yaml
- Now that the security release of 2022-02-09 has been delivered, we can enable back the automatic management of release.ci (reverts the behavior of #1979 )
- Manage secrets with the jenkins/jenkins helm chart instead of the custom "jenkins-additional", which is the same kind of change as we did for infra.ci in #1985)
- Fine tune the Azure volume used for the JENKINS_HOME of release.ci, as we did for infra.ci in #1986 (and which proved really efficient)
> feat(release.ci.jenkins.io) enable automated management + cherry pick secrets/mounts changes from infra.ci

- config/ext_jenkins-infra.yaml
This PR adds the Terraform's backend configuration file used in https://github.com/jenkins-infra/datadog
> feat(infra.ci) add datadog terraform's credential

- Jenkinsfile_k8s
In https://github.com/jenkins-infra/kubernetes-management/pull/2048, the checks failed and weren't able to validate that the introduce helmfile code was working as expected.
We merged the PR taking the risk of breaking the main branch, but we should not.
The core reason is that we run updatecli diff/apply *before* the helmfile stuff, because we use declarative pipeline syntax.
We could either switch to scripted or migrate all the updatecli tasks to a centralized multibranch repo (and remove updatecli code from this pipeline).
But for now, this PR will ensure that diff does not fail the whole pipeline.
> chore(pipeline) do not fail if updatecli diff fails

- config/ext_jenkins-infra.yaml
Since https://github.com/jenkins-infra/helpdesk/issues/2803, there haven't been any updatecli update due to jobs not triggered.
This PR bumps to latest weekly (hoping it would also fix the cron trigger issue).
> feat(infra.ci) Bump Docker image to 0.44.0-2.337

- updatecli/updatecli.d/docker-images/404.yaml
- updatecli/updatecli.d/docker-images/datadog.yaml
- updatecli/updatecli.d/docker-images/jenkins-lts.yaml
- updatecli/updatecli.d/docker-images/jenkins-weekly.yaml
- updatecli/updatecli.d/docker-images/keycloack-theme.yaml
- updatecli/updatecli.d/pod-templates/helmfile.yaml
- updatecli/values.yaml
- 1 fixed error comes from a duplicated value in `updatecli/values.yaml` from https://github.com/jenkins-infra/kubernetes-management/pull/2051. Ping @lemeurherve can you check that I've set the correct value for `github.user`?
- 1 fixed error comes from a `pullrequest` block not specifying the correct `target`
- Warnings around Docker image missing architecture
> chore(updatecli) cleanup updatecli manifest to fix errors and warnings

- config/ext_jenkins-infra.yaml
Replaced by azure credentials packer-azure-serviceprincipal
Follow-up of https://github.com/jenkins-infra/packer-images/pull/190
Close https://github.com/jenkins-infra/helpdesk/issues/2821
> chore: remove old azure SP string credentials used by packer-images

- Jenkinsfile_k8s
- PodTemplates.yaml
- updatecli/updatecli.d/pod-templates/helmfile.yaml
Reverts jenkins-infra/kubernetes-management#2095 because we are suffering from https://github.com/updatecli/updatecli/issues/583.
*Why didn't the check caught this issue*
- We are currently ignoring the failure of `updatecli diff` which hides the error. 
- This would be fixed once https://github.com/updatecli/updatecli/issues/465 is implemented in updatecli
- Until then, we **might** want to run updatecli in parallel of the kubernetes matrix to avoid blocking the process, OR not fail the pipeline when updatecli apply fail.
This PR also includes the following changes:
- Give memory /cpu to the pipeline process
- Ensure that updatecli runs in the same docker image as the rest of the pipeline (to ensure that we have the correct updatecli version and same tooling in exact same version)
> Revert "[updatecli] Bump jenkins-infra helmfile docker image" (updatecli to 0.21.0)

- config/ext_jenkins-infra.yaml
As part of https://github.com/jenkins-infra/helpdesk/issues/2683, this PR adds the following elements:
- Azure repository is now part of the "Terraform Jobs", watching for `Jenkinsfile_k8s` pipelines
- Credentials for azure management by terraform:
- 2 new backends config based on the aurerm backends for production and staging introduces in jenkins-infra/terraform-states
- 2 new Azure Service Principals for terraform (production and staging) to allow Terraform to manage Azure infrastructure
> feat(infra.ci) add azure terraform job

- config/ext_jenkins-infra.yaml
Avoid secret leaks when build fails
> fix: suppress log output in github checks

- config/ext_jenkins-infra.yaml
Also, suppress log output in github checks to avoid secret leaks when build fails
> feat(infra.ci) status check names

- config/ext_jenkins-infra-jobs.yaml
to allow plugin-site and jenkins.is.the.way jobs to succeed.
Consequence of https://github.com/jenkins-infra/helpdesk/issues/2840.
> fix(infra.ci) correct the scope of the netlify token 

- config/ext_jenkins-infra-jobs.yaml
This PR is part of https://github.com/jenkins-infra/helpdesk/issues/2789.
Requirements:
It creates a new folder with 5 sub-jobs (multibranch jobs), each one for 1 kind of report. The pipeline https://github.com/jenkins-infra/infra-reports/blob/master/Jenkinsfile#L51 will be split in an upcoming PR.
> feat(infra.ci) initial import of jenkins-infra/infra-report jobs 

- config/ext_jenkins-weekly.yaml
Ref: https://github.com/jenkins-infra/helpdesk/issues/2855#issuecomment-1089042558
> debug: disable health probes until a first instance is running

- config/ext_jenkins-infra-jobs.yaml
As part of https://github.com/jenkins-infra/helpdesk/issues/2789, the pipeline [library step `publishReports()` has to be allowed from infra.ci](https://github.com/jenkins-infra/pipeline-library/pull/348).
It requires a credential to allow sending the JSON reports into the correct Azure bucket hence the credential to be added.
The scope of this credential is only the folder `infra-reports` of course.
> feat(infra.ci) add the azure storage key required for publishing reports from infra-reports

- config/ext_jenkins-weekly.yaml
Fixes "/var/jenkins_config/apply_config.sh: cannot create /var/jenkins_home/jenkins.install.UpgradeWizard.state: Permission denied"
From https://github.com/jenkinsci/helm-charts/issues/210\#issuecomment-916217915
Part of https://github.com/jenkins-infra/helpdesk/issues/2855
> fix(weekly.ci.jenkins.io) Finish bootstrap + fix pipeline-library credz

- config/jenkinsio.yaml
This PR closes [jenkins-infra/helpdesk#2553](https://github.com/jenkins-infra/helpdesk/issues/2553).
Since https://github.com/jenkins-infra/kubernetes-management/pull/1724 that fixed the ingress chart upgrade from `4.0.6` to `4.0.8`, the configuration snippets were deleted.
With the last versions of the nginx controller, the snippet annotation is working as expected again, and the protection  against the attacks described by the [CVE-2021-25742](https://github.com/kubernetes/ingress-nginx/issues/7837) are avoided by filtering out some keywords from snippets: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#annotation-value-word-blocklist (alternative is to define the custom headers at the ingress controller installation level through the configmap).
The …
> fix(jenkinsio) enable again missing security headers 

- config/ext_jenkins-weekly.yaml
The frame I suggested to put the design library topic in looks fine on Jenkins' default theme, but dark theme or solarized don't look quite well when working with static colors.
> feat: Update presentation embed

- clusters/temp-privatek8s.yaml
- config/ext_jenkins-infra-jobs.yaml
(Superseeds and closes #2246 )
Ref. https://github.com/jenkins-infra/helpdesk/issues/2884
(edited to answer questions)
- Bump the helm chart jenkins-jobs to [0.3.0](https://github.com/jenkins-infra/helm-charts/releases/tag/jenkins-jobs-0.3.0), which makes github check disabled by default as per https://github.com/jenkins-infra/helm-charts/pull/120
- Cleanup current config to remove the deprecated `disableGitHubChecks` attributes
> feat(infra.ci) ensure that all github checks are disabled

- config/ext_datadog.yaml.gotmpl
This PR should fix the (frequent) datadog helm chart errors on datadog on cik8s (AWS EKS) or doks (DigitalOcean).
The error is the chart rolling update (usually when updating the image... each week) reaches a timeout.
Looking at the namespace `datadog` on `cik8s`, it appeared tha datadog agents (members of a daemonset - https://github.com/DataDog/helm-charts/blob/main/charts/datadog/templates/daemonset.yaml) were updated one at a time.
With ~25s to stop, pull, start, be ready per pod, It's fine for a cluster with less than 10 nodes (300s of timeout). But bigger clusters, such as cik8s or doks (when scaled up) are reaching the timeout.
Following the documentations at https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/ and …
> fix(datadog) increase agent updated at the same time during a rolling update

- config/ext_jenkins-release.yaml
as per Helpdesk#2837 
and the runbook (private): https://github.com/jenkins-infra/runbooks/pull/47
sops secret (private): https://github.com/jenkins-infra/charts-secrets/commit/5d25abb25e5d61a98619d4a008ea11ae626ce1f3
> Feat(release.ci): adding a dockerhub credential for PULL (warning readonly)

- updatecli/updatecli.d/charts/jenkins-agents-infra-release.yaml
Closes #2359
Ref. https://github.com/jenkins-infra/packer-images/issues/232
> fix(buildmasters) switch ubuntu-20 agent vm templates to ubuntu-20.04

- config/mirrorbits.yaml
As part of https://github.com/jenkins-infra/helpdesk/issues/2888:
- Enforce HTTPS on mirrors (all domains)
- handle requests from the domain mirrors.jenkins-ci.org
> feat(mirrors) enforce HTTPS + handle former domain

- config/jenkinsisthewayio.yaml
With this change, the whole original URL context (URI and query string) is kept during redirection:
```console
curl --silent -verbose --output /dev/null -H 'Host: jenkinsistheway.io' "https://rating.jenkins.io/something?foo=bar"
> GET /something?foo=bar HTTP/2
> Host: jenkinsistheway.io
< HTTP/2 308 
< location: https://stories.jenkins.io/something?foo=bar
```
instead of being redirected straight to https://stories.jenkins.io/
**Implementation detail**
- Nginx provides a variables `$request_uri` documented at https://nginx.org/en/docs/http/ngx_http_core_module.html#var_request_uri
- The nginx ingress annotation `permanent-redirect` that we use documented at https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#permanent-redirect) generates an nginx …
> fix(jenkinsistheway-redirect) ensure that the URL context is kept during redirection

- config/ext_jenkins-infra.yaml
Trying to make [this build](https://infra.ci.jenkins.io/job/docker-jobs/job/docker-inbound-agents/job/PR-24/10/console) pass, it seems hadolint isn't executed (?)
Retrieved the ami id from the last successfull build here: https://infra.ci.jenkins.io/job/infra-tools/job/packer-images/job/main/114/console
> chore: manually bump Windows 2019 EC2 agent template

- config/ext_jenkins-release.yaml
Revert the change introduced in https://github.com/jenkins-infra/kubernetes-management/pull/2468 which prevented agent to connect to the controller on release.ci.jenkins.io (cf https://release.ci.jenkins.io/job/core/job/weekly/job/release/job/master/135/console)
> fix: revert jenkinsUrl

- config/ext_jenkins-infra-jobs.yaml
This PR adds 2 new credentials for the terraform oracle project, holding the Oracle ID for the 2 compartments.
Required to make https://github.com/jenkins-infra/oracle/pull/8 work as expected
> feat(infra.ci) add compartment ID for oracle terraform project

- config/ext_jenkins-infra-jobs.yaml
Ref. https://github.com/jenkins-infra/jenkins-infra/issues/2248
The reason to use infra.ci is that our checks are vital for the infra, but they are coliding with development jobs.
> feat(infra.ci) add a new job for jenkins-infra/jenkins-infra

- clusters/cik8s.yaml
- clusters/doks.yaml
- clusters/prodpublick8s.yaml
- clusters/temp-privatek8s.yaml
- config/ext_jenkins-infra.yaml
- config/ext_temp-privatek8s-datadog.yaml
- updatecli/updatecli.d/charts/datadog.yaml
Supersedes #2625 by setting up a datadog agent with its own API key on temp-privatek8s and configure it in the corresponding datadog jcasc
Datadog API keys created for temp-privatek8s, cik8s and doks, then added in chart-secrets
Ref: jenkins-infra/helpdesk#2804
> fix(infra.ci.jenkins.io): setup datadog agent on temp-privatek8s

- clusters/prodpublick8s.yaml
- config/ext_github-comment-ops.yaml
- updatecli/updatecli.d/charts/github-comment-ops.yaml
Ref: https://github.com/jenkins-infra/helpdesk/issues/3060
> feat: add github-comment-ops chart

- clusters/cik8s.yaml
- clusters/doks.yaml
- clusters/prodpublick8s.yaml
- clusters/temp-privatek8s.yaml
Reverts jenkins-infra/kubernetes-management#2647
```
FAILED RELEASES:
NAME
datadog
in clusters/temp-privatek8s.yaml: failed processing release datadog: command "/usr/local/bin/helm" exited with non-zero status:
PATH:
/usr/local/bin/helm
ARGS:
0: helm (4 bytes)
1: upgrade (7 bytes)
2: --install (9 bytes)
3: --reset-values (14 bytes)
4: datadog (7 bytes)
5: datadog/datadog (15 bytes)
6: --version (9 bytes)
7: 2.36.6 (6 bytes)
8: --wait (6 bytes)
9: --timeout (9 bytes)
10: 840s (4 bytes)
11: --atomic (8 bytes)
12: --create-namespace (18 bytes)
13: --namespace (11 bytes)
14: datadog (7 bytes)
15: --values (8 bytes)
16: /var/folders/z6/xykmq_m902n_7v4j8sxhzkdm0000gn/T/helmfile1657383346/datadog-datadog-values-7bc995f5b6 (101 bytes)
17: --values (8 bytes)
18: …
```
> Revert "[updatecli] Bump datadog helm chart"

- clusters/cik8s.yaml
- clusters/doks.yaml
- clusters/prodpublick8s.yaml
- clusters/temp-privatek8s.yaml
Reverts jenkins-infra/kubernetes-management#2649
Manually applied this last datadog release on temp-privatek8s
> Revert "Revert "[updatecli] Bump datadog helm chart""

- config/ext_loki.yaml
The latest loki upgrade is failing without any change.
The errors on the cluster are related to the volume unable to be mounted/unmounted which also causes timeouts.
First step to unblock: currently deleting the PV (with the data: we don't use loki for real) and re-creating it thanks to this change as a managed-csi disk.
> fix(loki) ensure that a CSI disk is used instead of default (re-creates a new pod)

- config/ext_jenkins-infra.yaml
- config/ext_jenkins-release.yaml
As per https://www.jenkins.io/security/advisory/2022-07-27/#SECURITY-1468, the `git-client` plugin is set by this PR to use a manual list of host key for SSH verification.
Only github.com host key is included.
Documentation of the plugin for this particular feature can be found at: https://github.com/jenkinsci/git-client-plugin#ssh-host-key-verification
> fix(release.ci, infra.ci) Set git SSH host key verification to manually provided list and add github.com SSH ed25519 host key

- config/ext_datadog.yaml.gotmpl
- config/ext_jenkins-infra.yaml
Follow up of  https://github.com/jenkins-infra/helpdesk/issues/2804, this PR:
- Fix a typo in the datadog chart's value (all cluster) to ensure that logs collection is enabled on the datadog agents
- Enable traces collection in infra.ci.jenkins.io through datadog agent
(edited) N.B:
Log collection in the Jenkins datadog plugin was not enabled because it blocks all controller threads if logs cannot be collected.
Tried with https://plugins.jenkins.io/datadog/#plugin-content-log-collection-for-agents mentions a custom log source file to add to the datadog agent. That one might not be present in our current setup resulting in error messages on infra.ci.jenkins.io until we find the correct setup (by switching to official datadog image instead of ours)
=> we might want to fine tune this in the …
> fix(datadog) ensure log collection is enabled + feat(infra.ci.jenkins.io) enable datadog traces collection

- config/ext_jenkins-infra.yaml
- config/ext_jenkins-release.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3090.
All these agents are *already* using JDK11, but making it explicit will help when switching to JDK17
> fix(release.ci,infra.ci) set explicit agent java bin to ensure JDK11

- config/ext_jenkins-infra.yaml
Should fix Windows (which can't have command prefix)
Ref:
- jenkinsci/ec2-plugin#766
- jenkins-infra/helpdesk#3090
- jenkins-infra/docker-jenkins-weekly#565
> fix: use ec2-plugin 'javaPath' option instead of command prefix

- config/ext_jenkins-infra.yaml
Fixup of https://github.com/jenkins-infra/kubernetes-management/pull/2721
> fix: use antislash for the tempDir on Windows EC2 (`mkdir` fails otherwise)

- config/ext_jenkins-infra.yaml
Fixes #2722
I'm wondering if we should try to remove all default values from our JCasC definition to make it more readable & comprehensive, as we used a JCasC export which contains all default values to create it.
> chore: remove default amiType values

- config/ext_jenkins-infra-jobs.yaml
Ref jenkins-infra/helpdesk#3084 
- Job definition added
- A GitHub App is specified to scan/checkout/report checks to the repo but the secrets values are empty for now
- Default configuration applied for now (untrusted contributor cannot change the Jenkinsfile or trigger build)
> feat(infra.ci) add job definition to build the jenkinsci ATH Docker image

- clusters/prodpublick8s.yaml
Should fix:
> Error: release nginx-proxy-azure failed, and has been uninstalled due to atomic being set: PersistentVolume 'nginx-proxy-azure-pv' is invalid: spec: Required value: must specify a volume type
> chore: bump nginx-proxy

- Jenkinsfile_k8s
If there is only a cluster definition change: build only this cluster
If there is any (chart) `config` change: build on all clusters as we can't determine easily and reliably if a specific cluster is concerned by the (chart) change
If there is a cluster definition change and any (chart) `config` change: same as above, build on all clusters
> feat: build only modified cluster(s) if there isn't any config change

- clusters/prodpublick8s.yaml
- config/artifact-caching-proxy-test.yaml
> too many certificates (5) already issued for this exact set of domains in the last 168 hours: repo.azure.jenkins.io, retry after 2022-09-02T16:52:55Z: see https://letsencrypt.org/docs/duplicate-certificate-limit/'
> chore: test another artifact-caching-proxy on another subdomain

- clusters/prodpublick8s.yaml
- clusters/temp-privatek8s.yaml
Was put in place for a previous problem. This timeout causes troubles now as datadog release is frenquently in a bad state:
'Error: UPGRADE FAILED: another operation (install/upgrade/rollback) is in progress'
> fix: remove datadog release specific timeout

- updatecli/updatecli.d/docker-images/404.yaml
In #2828 , the nginx ingress configuration files were renamed (and a new one added for the public Doks ingress controller).
This PR fixes the updatecli manifest with these 5 files.
> chore(updatecli) fixup of #2828 to correct error messages about the nginx default 404 image manifest

- config/ext_datadog.yaml.gotmpl
The logs of the cluster-agent components recommens to run in HA (High Availability) mode. This PR enable the HA mode by setting the amount of replicas to `2` as per https://github.com/DataDog/helm-charts/tree/main/charts/datadog.
It's also the opportunity to enable the network advanced monitoring by datadog (https://github.com/DataDog/helm-charts/tree/main/charts/datadog#enabling-npm-collection).
Please note that we used to set up an incorrect value for the cluster agent: it must be singular form. It was "partially" working because the default value is to have it enabled since months. By fixing this "syntax" error, it means that more datadog components will be created in the helmfile diff.
> feat(datadog) enable HA mode for cluster agent + enable network monitoring

- config/ext_datadog.yaml.gotmpl
Fixup of #2843 as per the deployment logs of datadog:
```console
[2022-09-08T15:30:24.484Z] 
[2022-09-08T15:30:24.484Z] ###################################################################################
[2022-09-08T15:30:24.484Z] ####   WARNING: Cluster-Agent should be deployed in high availability mode     ####
[2022-09-08T15:30:24.484Z] ###################################################################################
[2022-09-08T15:30:24.484Z] 
[2022-09-08T15:30:24.484Z] The Cluster-Agent should be in high availability mode because the following features
[2022-09-08T15:30:24.484Z] are enabled:
[2022-09-08T15:30:24.484Z] * Admission Controller
[2022-09-08T15:30:24.484Z] 
[2022-09-08T15:30:24.484Z] To run in high availability mode, our recommandation is to update the chart …
```
> fixup of 539a517 to ensure full HA mode for datadog cluster-agent

- config/artifact-caching-proxy-common.yaml
Fixup of https://github.com/jenkins-infra/kubernetes-management/pull/2842
> fixup(artifact-caching-proxy): typo in resources.limits.memory

- PodTemplates.yaml
Reverts jenkins-infra/kubernetes-management#2879 because it fails during the `helmfile lint` step with:
```console
ARGS:
[2022-09-14T17:21:06.510Z]   0: helm (4 bytes)
[2022-09-14T17:21:06.510Z]   1: secrets (7 bytes)
[2022-09-14T17:21:06.510Z]   2: view (4 bytes)
[2022-09-14T17:21:06.510Z]   3: /home/jenkins/agent/workspace/_jobs_kubernetes-management_main/secrets/config/docker-registry-secrets/secrets.yaml (114 bytes)
[2022-09-14T17:21:06.510Z] 
[2022-09-14T17:21:06.510Z] ERROR:
[2022-09-14T17:21:06.510Z]   exit status 1
[2022-09-14T17:21:06.510Z] 
[2022-09-14T17:21:06.510Z] EXIT STATUS
[2022-09-14T17:21:06.510Z]   1
[2022-09-14T17:21:06.510Z] 
[2022-09-14T17:21:06.510Z] STDERR:
[2022-09-14T17:21:06.510Z]   Error: unknown command "view" for "helm"
[2022-09-14T17:21:06.510Z]   Run 'helm …
```
> Revert "Bump jenkins-infra helmfile docker image to 2.4.68"

- config/ext_jenkins-infra-jobs.yaml
Fixup of https://github.com/jenkins-infra/kubernetes-management/pull/2889
Ref: https://github.com/jenkins-infra/helpdesk/issues/3114
> fixup: correct Jenkinsfile path for plugin-health-scoring

- config/ext_jenkins-infra-jobs.yaml
Reverts jenkins-infra/kubernetes-management#2899 (not working, still looking for `Jenkinsfile_k8s`)
> Revert "fixup: correct Jenkinsfile path for plugin-health-scoring"

- clusters/cik8s.yaml
Will be deployed on a future public EKS
> chore: remove artifact-caching-proxy from cik8s

- clusters/doks-public.yaml
Not used, and release failed as there isn't any `jenkins-agents` namespace on this cluster.
> fix: override docker-registry-secrets values to use `datadog` namespace only on doks-public

- clusters/doks-public.yaml
It's the same credentials in all these datadog secrets, this PR is to be consistent between all clusters.
> chore: use own datadog `doks-public-secrets`

- config/artifact-caching-proxy__common.yaml
Node capacity on
- prodpublick8s: Standard_D8s_v3, 8 vCPU 32Go mem
- doks-public: s-4vcpu-8gb, 4 vCPU 8Go mem
- eks-public: t4g.xlarge, 4 vCPU 16Go mem
> chore(artifact-caching-proxy): increase resources

- config/ext_jenkins-infra-jobs.yaml
Extracted from and needed for https://github.com/jenkins-infra/kubernetes-management/pull/2944
Corresponding secret added by https://github.com/jenkins-infra/charts-secrets/commit/b251cd22b7e3e3f1e4fcfc67350173c0528f0ff3
(obtained with `aws eks update-kubeconfig --name jenkins-infra-public-ENRZrfwf --region us-east-2`)
> feat: add `kubeconfig-eks-public` credentials

- config/plugin-health-scoring.yaml
Excerpt of https://github.com/jenkins-infra/kubernetes-management/pull/2999 to unblock @alecharp
> hotfix: remove image.tag from `plugin-health-scoring` values

- clusters/cik8s.yaml
- config/ext_autoscaler_cik8s.yaml
Follow-up of https://github.com/jenkins-infra/kubernetes-management/pull/2944
> chore: align cluster name value declaration between cik8s & eks-public

- clusters/eks-public.yaml
after : https://github.com/jenkins-infra/aws/pull/250
datadog install with the amd64 image
> fix(eks-public / datadog):  add datadog release with amd64

- config/ext_public-nginx-ingress_eks-public.yaml
- updatecli/updatecli.d/docker-images/404.yaml
Now that we've switched from an incompatible ARM CPU architecture to a compatible amd64 one in https://github.com/jenkins-infra/aws/pull/250
Related restoration, same effect: #3024
> fix(eks-public): restore nginx-ingress default backend

- config/ext_autoscaler_eks-public.yaml
As the instance type has changed from 't4g.xlarge' to 't3a.xlarge' since https://github.com/jenkins-infra/aws/pull/250, the autoscaler pod stayed in 'pending' with the following warning:
> Warning  FailedScheduling  14s (x2 over 104s)  default-scheduler  0/2 nodes are available: 2 node(s) didn’t match Pod’s node affinity/selector.
> fix(eks-public): correct instance type for the autoscaler node selector

- config/ext_jenkins-infra-jobs.yaml
Cc @NotMyFault 
(edit for context)
- Related to https://github.com/jenkins-infra/ircbot/issues/104
- Allows to deploy the new versions of the ircbot image (v1.5.0 is from 2019 😱)
> feat(infra.ci) add a job for the Docker image of ircbot

- clusters/prodpublick8s.yaml
- config/ircbot.yaml
Closes https://github.com/jenkins-infra/kubernetes-management/pull/3036
cc @slide @halkeye
> fix(ircbot): no image.tag and bump chart version

- config/ext_jenkins-infra-jobs.yaml
While working on https://github.com/jenkins-infra/helpdesk/issues/3157, I realized this line was doing nothing, since https://github.com/jenkins-infra/helm-charts/pull/120
> chore(infra.ci) remove a deprecated (and ignored) directive for the jobs configuration

- updatecli/updatecli.d/docker-images/datadog.yaml
Same thing as https://github.com/jenkins-infra/jenkins-infra/pull/2439.
The goal of this PR is to avoid duplication of the `sha256:` prefix due to updatecli v0.36.0
> chore(updatecli) fix manifests with dockerdigest in 0.36.x

- config/ext_jenkins-infra.yaml
Use [Config File Provider](https://plugins.jenkins.io/config-file-provider/) on three settings.xml (one for each provider) to setup basic auth from a common new artifact-caching-proxy-credentials global usernamePassword credentials.
> feat(infra.ci.jenkins.io): artifact caching proxy Maven settings

- clusters/prodpublick8s.yaml
Reverts jenkins-infra/kubernetes-management#3076
The new version does not start (issue incoming in jenkins-infra/account-app with error logs) but we have to stop trying to deploy it.
> Revert "Bump `accountapp` helm chart version to 0.1.5"

- config/ext_jenkins-infra.yaml
- Removed ppc64 and s390x CPU architecture
- Bumped JDK11 to 11.0.16.1+1
- Bumped JDK17 to 17.0.4.1+1
This PR is related to https://github.com/jenkins-infra/helpdesk/issues/3087. It ensures a partial feature parity between ci.jenkins.io and infra.ci.jenkins.io to handle jobs migrated (or spread) between these 2 controllers.
Please note that:
- There is no updatecli tracking (yet)
- After a discussion with @lemeurherve , we though on a way to generate a common definition for both Puppet and helm chart, to be continued.
> feat(infra.ci) add tools `jdk8`, `jdk11`, `jdk17` and `mvn` adapted from ci.jenkins.io export

- config/artifact-caching-proxy_aws.yaml
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
annotations:
storageclass.kubernetes.io/is-default-class: "true"
name: ebs-gp3
parameters:
fsType: ext4
type: gp3
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```
Ref: https://github.com/jenkins-infra/helpdesk/issues/3053
> fix(artifact-caching-proxi/AWS): use new storage class

- config/artifact-caching-proxy_aws.yaml
- config/ext_autoscaler_cik8s.yaml
- config/ext_autoscaler_eks-public.yaml
This PR follows up the following AWS EKS changes on cik8s ("eks") and eks-public:
- https://github.com/jenkins-infra/aws/pull/272
- https://github.com/jenkins-infra/aws/pull/273
- https://github.com/jenkins-infra/aws/pull/274
- https://github.com/jenkins-infra/aws/pull/275
- https://github.com/jenkins-infra/aws/pull/276
- https://github.com/jenkins-infra/aws/pull/277
It uses the new IAM ARN roles for CSI storage provisioning on both clusters and it corrects the ACP storageClass.
PS: the current storage class is provided in comment in ACP values, until we find are able to "helmfile" apply it properly.
> fix(cik8s,eks-public) use new IAM ARNs + fix ACP storageclass to use 1.23 CSI

- config/ext_aws-load-balancer-controller.yaml
- config/ext_public-nginx-ingress_eks-public.yaml
After https://github.com/jenkins-infra/helpdesk/issues/3053, the EKS managed SG was updated with the tag `kubernetes.io/cluster/<cluster name>` which caused mayhem with the Loadbalancer (no more backends...) because subnet discoverability was expecting only 1 tagged SG while they were 2 (the [EKS managed SG](https://github.com/jenkins-infra/aws/blob/d783760bdd8df46d4f79719c4be88e32c8c9fb62/eks-public-cluster.tf#L73-L75) and the [Terraform EKS module managed Node SG (`node_security_group_id`)](https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest?tab=outputs).
Hard to diagnose because eks-public used the Legacy Cloud Load Balancer Controller (no logs) despite the new Controller being installed (logs but no mentions of the loadbalancer because delegated to the Legacy …
> hotfix(eks public) Correct LB system

- config/rss2twitter.yaml
As the service is deployed on prodpublick8s and its logs in dry mode are OK, this PR is activating the publication of the https://www.jenkins.io/releases.rss RSS feed on the [`Jenkins releases` Twitter account](https://twitter.com/jenkins_release).
Ref: https://github.com/jenkins-infra/helpdesk/issues/3085
> feat: activate `rss2twitter` service by disabling dry mode

- config/ext_jenkins-infra.yaml
While working on https://github.com/jenkins-infra/helpdesk/issues/3087, it appeared  that https://github.com/jenkins-infra/pipeline-steps-doc-generator requires at least 8 Gb of memory.
The PR https://github.com/jenkins-infra/pipeline-steps-doc-generator/pull/222 was failing the checks with a "Java heap" error.
The default `linux-amd64` machine on infra.ci is a T3Medium which is 2 vCPUs and 4 Gb: too small for this case.
The build `#8` of the PR The PR https://github.com/jenkins-infra/pipeline-steps-doc-generator/pull/222 succeeded with a T3Large (2 vCPUs and 8 Gb), but I chose a `T3XLarge` (4 vCPU / 16 Gb) for the following reasons:
- Same size as the default "Linux" ci.jenkins.io: https://github.com/jenkins-infra/jenkins-infra/blob/7222278ec24b8888ce28d80d7b6b6a9e53f45395/hieradata/clien …
> feat(infra.ci) add a new agent VM template 'linux-big' for higher memory use cases

- config/rss2twitter.yaml
This (typo) quote has for consequence for the link to be displayed while it shouldn't:
Ref: https://github.com/jenkins-infra/helpdesk/issues/3085
> fix(rss2twitter): remove double quote at the end of the tweet

- clusters/prodpublick8s.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3214, in order to generate the db login/pass from terraform, I need to split the secrets to ease to copy and paste process.
> chore(keycloak): splitting keycloak secrets

- config/ext_jenkins-infra.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3157
the node should be the same as on ci.jenkins.io to handle the same pipeline on both ci.jenkins.io AND infra.ci.jenkins.io
Ref. https://github.com/jenkins-infra/kubernetes-management/pull/3193
> feat(infra): new node agent for infra as for ci.jenkins.io

- config/ext_jenkins-infra.yaml
to avoid caching of libraries on PR, allowing to work on pipeline library without having to empty the cache
> feat(infra.ci): exclude pr from libraries caching

- config/ext_jenkins-infra.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3157.
The goal is to ensure that the (big) pods generating the stories.jenkins.io website (for both preview and production deployment) are scheduled.
The node pool `infracinodepool` had been created with a bigger machine size (8vCPUS/32 Gb) to ensure pods can be scheduled.
This PR makes sure that we only have Linux pods templates that are:
- used (other are emoved)
- schedulable (toleration applied to ensure that the correct node pool is used)
> feat(infra.ci.jenkins.io) update Linux pod templates configuration (cleanup + tolerations)

- clusters/prodpublick8s.yaml
Note: already applied to ensure no exposure (as per https://github.com/jenkins-infra/helm-charts/pull/349)
> bump plugin-health-scoring to 1.4.0

- config/ldap.yaml
This PR is related to both:
- https://github.com/jenkins-infra/helpdesk/issues/3257 to allow the new `private.vpn.jenkins.io` machine to reach the LDAP (tested manually)
- https://github.com/jenkins-infra/helpdesk/issues/3288 to allow the new JFrog platform to reach the LDAP
> feat(ldap) allow IPs for `private.vpn.jenkins.io` and JFrog AWS `us-east-1`

- clusters/privatek8s.yaml
- clusters/temp-privatek8s.yaml
- config/ext_jenkins-infra__common.yaml
- config/ext_jenkins-infra_privatek8s.yaml
- config/ext_jenkins-infra_temp-privatek8s.yaml
- updatecli/updatecli.d/charts/jenkins-additional.yaml
- updatecli/updatecli.d/charts/jenkins-jobs.yaml
- updatecli/updatecli.d/charts/jenkins.yaml
- updatecli/updatecli.d/docker-images/jenkins-weekly.yaml
This PR add the Jenkins controller intended for infra.ci.jenkins.io, without the corresponding jobs definitions (for another PR)
Follow-up of https://github.com/jenkins-infra/kubernetes-management/pull/3247
Remaining changes of https://github.com/jenkins-infra/kubernetes-management/pull/3194
> feat(privatek8s): add Jenkins controller

- updatecli/updatecli.d/charts/jenkins-agents-infra.ci.jenkins.io.yaml
reviewing this PR : https://github.com/jenkins-infra/kubernetes-management/pull/3375/files I though it would be better to have a condition to avoid breaking change by merging without seeing the bad change : 
`- ami: "{{ source "getLatestWindowsAgentAMIAmd64" }}"`
> chore(updatecli): add a condition to avoid error in version

- config/ldap.yaml
As https://github.com/jenkins-infra/helpdesk/issues/3288 is completed, these IPs can be removed.
> cleanup(ldap): remove previous JFrog instance IPs

- config/ext_datadog_privatek8s.yaml
- config/ext_datadog_publick8s.yaml
- config/ldap.yaml
```console
$ yamllint --config-file yamllint.config config
config/ldap.yaml
4:22      warning  too few spaces before comment  (comments)
5:26      warning  too few spaces before comment  (comments)
6:27      warning  too few spaces before comment  (comments)
7:25      warning  too few spaces before comment  (comments)
8:24      warning  too few spaces before comment  (comments)
9:26      warning  too few spaces before comment  (comments)
10:28     warning  too few spaces before comment  (comments)
11:28     warning  too few spaces before comment  (comments)
12:26     warning  too few spaces before comment  (comments)
13:27     warning  too few spaces before comment  (comments)
14:26     warning  too few spaces before comment  (comments)
15:26     warning  too few spaces before comment …
```
> chore: correct comment spacing to avoid yamllint warnings

- clusters/doks-public.yaml
- clusters/eks-public.yaml
- updatecli/updatecli.d/charts/cert-manager.yaml
updatecli was not tracking cert-manager versions for eks-public and doks-public.
> fix(eks-public/doks-public): upgrade cert-manager version to v1.11.0

- config/artifact-caching-proxy__common.yaml
As the `/healthz` path is the default health check path of the nginx ingress, this PR is specifying a distinct path to ensure the artifact-caching-proxy health is tested and not the nginx ingress.
Note: [the default chart value](https://github.com/jenkins-infra/helm-charts/blob/4173bbb9d8238ab89be27085f09234459a1298a2/charts/artifact-caching-proxy/values.yaml#L43) could also be changed.
> fix(artifact-caching-proxy): distinct health check path

- config/artifact-caching-proxy_aws.yaml
- config/ext_public-nginx-ingress_eks-public.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3305, this PR persists the manual changes that were done to allow Cert Manager to validate the HTTP-01 Let's Encrypt challenge in eks-public, for the ACP service.
- Setting the ingress class `public-nginx`as the default (to pick and implement any ingress rule without a `spec.ingressClass` attribute set to the value `public-nginx`
- Enabling the class by name mode to ensure that all cases of ingress rule specification are covered
- Set up ACP ingress rule to reuse its Ingress rule "in place" (instead of creating/deleting another ingress rule each time a challenge happens)
References:
- https://github.com/cert-manager/cert-manager/issues/4821
- https://cert-manager.io/docs/installation/upgrading/ingress-class-compatibility/
> fix(eks-public) correct ACP and public-ingress configuration to follow cert-manager recommendations

- clusters/prodpublick8s.yaml
Reverts jenkins-infra/kubernetes-management#3535
Every following deployment on prodpublick8s failed.
> Revert "Bump `grafana` helm chart version to 6.50.6"

- clusters/eks-public.yaml
- config/artifact-caching-proxy_aws.yaml
- config/ext_autoscaler_cik8s.yaml
- config/ext_autoscaler_eks-public.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3305, follows up https://github.com/jenkins-infra/aws/pull/335.
This PR introduces the following changes (already applied on production to validate):
- Revert https://github.com/dduportal/kubernetes-management/commit/0288bb0748a85242f4bf1c126d121817d2cd1c1d
- Use the storage class `ebs-sc-az1-retain` (bound to `us-east-2a` AZ)
- Enable HA for AWS autoscalers
- Enable topology awareness for AWS autoscalers
> fix(eks-public) correct ACP by using single AZ node pool, EBS PVC with custom SC and autoscaler topology awareness

- config/ext_jenkins-infra.yaml
Fix https://docs.cloudbees.com/docs/cloudbees-ci-kb/latest/best-practices/stuck-thread-looking-up-ipv6-hostname
> fix(infra.ci.jenkins.io): force Jenkins controller to use IPv4

- config/ext_jenkins-infra-jobs.yaml
Missing credentials noticed in https://github.com/jenkins-infra/incrementals-publisher/pull/23
> fix(infra.ci): add Docker hub credentials for incrementals-publisher

- config/ext_jenkins-infra-jobs.yaml
The incrementals-publisher job also needs to pull images from jenkinsciinfra Docker hub organisation.
Follow-up of #3608
> fix(infra.ci): add Docker hub credentials for incrementals-publisher (#3609

- config/ext_jenkins-infra-jobs.yaml
> fix(infra.ci): correct Docker pull credentials name for incrementals-publisher

- config/ext_jenkins-infra.yaml
- config/ext_jenkins-release.yaml
- config/ext_jenkins-weekly.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/3378
- Increase the memory for infra.ci from 4 to 8 Gigabyte (nodes have 4 vCPUS and 16 GB: it fits) to had more space to the controller to deal with running pipelines
- Remove the JVM option `MaxRAM` to let the JVM deal with its container memory limits (we are in 2023 and both JDK11 and JDK17 are ok with that, even with cgroups v2)
- Remove the JVM option `org.csanchez.jenkins.plugins.kubernetes.pipeline.ContainerExecDecorator.websocketConnectionTimeout` (impact: the value will be back to its default which is 30s AFAIR)
- Ensure that both release.ci and weekly.ci JVMs are using IPv4 (`-Djava.net.preferIPv4Stack=true`)
> fix(infra.ci,release.ci, weekly.ci) improve memory management for JVMs + cleanup JVM options

- config/ext_public-nginx-ingress_privatek8s.yaml
- config/ext_public-nginx-ingress_prodpublick8s.yaml
- config/ext_public-nginx-ingress_publick8s.yaml
Address the deprecation of `spec.loadBalancerIP` introduced with the version 1.24 of Kubernetes, see https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#deprecation
This new annotation is available for Kubernetes version 1.21 and later.
See https://github.com/Azure/AKS/issues/3122 & the new AKS load balancer doc: https://cloud-provider-azure.sigs.k8s.io/topics/loadbalancer/
Ref: https://github.com/jenkins-infra/helpdesk/issues/3387
> chore(public-nginx/AKS): replace `spec.loadBalancerIP` by `annotations.service.beta.kubernetes.io/azure-load-balancer-ipv4`

- config/ext_public-nginx-ingress_publick8s.yaml
Fixup of https://github.com/jenkins-infra/kubernetes-management/pull/3624
Fix the following error:
> Error: UPGRADE FAILED: an error occurred while rolling back the release. original upgrade error: cannot patch "public-nginx-ingress-ingress-nginx-controller" with kind Service: Service "public-nginx-ingress-ingress-nginx-controller" is invalid: spec.ipFamilyPolicy: Invalid value: "PreferDualStack": must be 'SingleStack' to release the secondary IP family: cannot patch "public-nginx-ingress-ingress-nginx-controller" with kind Service: Service "public-nginx-ingress-ingress-nginx-controller" is invalid: spec.ipFamilyPolicy: Invalid value: "PreferDualStack": must be 'SingleStack' to release the secondary IP family
Indeed, by default the `spec.ipFamilies` has only "IPv4" as value, adding "IPv6" …
> fixup(publick8s/public-nginx): complete `spec.ipFamilies` with IPv4 and IPv6

- config/ext_jenkins-infra.yaml
Ref: https://github.com/jenkins-infra/helpdesk/issues/3396
> chore(infra.ci): set Maven version to 3.9.0

- config/ext_jenkins-infra.yaml
Cf https://github.com/jenkins-infra/jenkins-infra/pull/2674#issuecomment-1452076960
Settings on ci.jenkins.io defined here: https://github.com/jenkins-infra/jenkins-infra/blob/production/dist/profile/templates/jenkinscontroller/casc/artifact-caching-proxy.yaml.erb
> fix(artifact-caching-proxy): update mirrored repositories list to be the same on infra.ci and ci.jenkins.io

- config/ext_jenkins-infra-jobs.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3419 
this PR add the repository jenkins-infra with the jenkins file `Jenkinsfile_updatecli` to the infra.ci.jenkins.io in order to replace the GHA.
The `Jenkinsfile_updatecli` is provided by the PR : https://github.com/jenkins-infra/jenkins-infra/pull/2673
> feat(updatecli): add the jenkins-infra (puppet) entry to updatecli

- config/ext_jenkins-infra-jobs.yaml
> fix(infra.ci) ensure that the updatecli job for puppet (jenkins-infra) watches the correct branches (production, etc.)

- clusters/cik8s.yaml
- clusters/doks.yaml
- Reference for cik8s: https://github.com/jenkins-infra/jenkins-infra/blob/b2ed0ee76d2d362a51353fa511a86b6792c10cd8/hieradata/clients/azure.ci.jenkins.io.yaml#L148
- Reference for doks: https://github.com/jenkins-infra/jenkins-infra/blob/b2ed0ee76d2d362a51353fa511a86b6792c10cd8/hieradata/clients/azure.ci.jenkins.io.yaml#L247
(edit) this PR follows up https://github.com/jenkins-infra/jenkins-infra/pull/2655 which changed the quotas on the Jenkins Kuberenetes plugin side. I forgot to propagate the change manually on Kubernetes side.
PS: this change will be automated by an updatecli manifest soon (ref. jenkins-infra/helpdesk#3431)
> feat(cik8s,doks) increase the max. pod quotas for jenkins-agents namespaces

- clusters/doks.yaml
As the droplets limit on DigitalOcean account has been increased to 100, we can now increase this cluster capacity to be the same as the AWS one.
Follow-up of https://github.com/jenkins-infra/jenkins-infra/pull/2679 & #3660
> feat(doks) increase the max. pod quotas for jenkins-agents namespaces

- clusters/prodpublick8s.yaml
Note: for ease of migration I've kept updatecli manifests unchanged, they might have the time to fail before the complete migration 🤷
> chore: remove `github-comment-ops`, `ircbot` & `rss2twitter` from `prodpublick8s` before their migration to `privatek8s`

- updatecli/updatecli.d/charts/jenkins-infra-tools-maven.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3396#issuecomment-1451997725
This PR  ensures that updatecli track the Maven version to update the tool version in infra.ci.jenkins.io.
> chore(updatecli) track the maven tool version for infra.ci.jenkins.io

- clusters/privatek8s.yaml
> fix(privatek8s.yaml): put the core package PVCs in the same namespace as the release agents

- updatecli/updatecli.d/charts/jenkins-agents-infra.ci.jenkins.io.yaml
> chore(updatecli): remove AMD64 ubuntu and windows 2019 for AWS

- updatecli/updatecli.d/charts/jenkins-agents-infra.ci.jenkins.io.yaml
Still missing a condition that check the existence of the image within the azure gallery of packer-image with  
`az image list or show`
> chore(infra.ci/updatecli): add Azure version from packer image version in updatecli manifest

- config/accountapp.yaml
As the helm chart release GitHub Action hasn't been triggered by https://github.com/jenkins-infra/helm-charts/commit/771c1c2b00daabd697748a2c618745e757a41521 nor https://github.com/jenkins-infra/helm-charts/commit/b041e70256f653207f04c68fee6e33cb551a66f0, this PR is bumping the Docker image version directly in its values.
Include the hotfix to unblock accounts.jenkins.io content: https://github.com/jenkins-infra/account-app/pull/254
Cf https://github.com/jenkins-infra/account-app/issues/250
> fix: force accountapp Docker image bump

- config/accountapp.yaml
Same as #3767 to include https://github.com/jenkins-infra/account-app/pull/251 as https://github.com/jenkins-infra/account-app/pull/254 didn't work
> fix: force account-app docker image bump

- config/jenkins-kubernetes-agents_ci-jenkins-io_doks.yaml
Decrease `doks` capacity until credits are renewed.
Related: https://github.com/jenkins-infra/jenkins-infra/pull/2745
Ref: https://github.com/jenkins-infra/helpdesk/issues/3487
> chore: temporarily decrease doks capacity

- updatecli/updatecli.d/charts/jenkins-infra-tools-maven.yaml
Blocked by ~https://github.com/jenkins-infra/kubernetes-management/pull/3773~ https://github.com/jenkins-infra/kubernetes-management/pull/3798  (due to filename changes).
Since #3750 we now have (easy) access to the semantic version of the packer images used for agents in the configuration.
This PR ensures that updatecli uses this version to check the expected Maven version for tools.
> chore(updatecli) ensure that Maven version is retrieved from the production deployed image instead of the 'main' branch that may be unreleased

- config/public-nginx-ingress_privatek8s.yaml
- updatecli/updatecli.d/allowed-github-hooks-ips.yaml
While working on the migration https://github.com/jenkins-infra/helpdesk/issues/2844, @lemeurherve and I realized that the IP restriction of the public nginx ingress on the `privatek8s` cluster was only at the NBginx level.
It works as expected, but we can improve this with this PR, by ensuring that the IP denylist is also set at the Loadbalancer level.
The command 
```
curl --silent --verbose --insecure https://20.15.118.70 --output /dev/null 
```
should timeout once deployed, unless run from an authorized IP.
- The value `co,ntroller.service.loadBalancerSourceRanges` is documented in https://github.com/kubernetes/ingress-nginx/blob/26d83d1b2058cc9c23657b4e97b9e5a6d5fe9871/charts/ingress-nginx/README.md?plain=1#L292
- We already use it on the `prodpublick8s` cluster (for LDAP: …
> feat(privatek8s) enable load balancer deny list for the public ingress, in full IPv4

- clusters/cik8s.yaml
- config/jenkins-kubernetes-agents_ci.jenkins.io_cik8s-bom.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3521
This PR adds a new namespace `jenkins-agents-bom` in the cluster `cik8s` (AWS EKS) to ensure:
- Logical and clear separation (for metrics, logs, configuration)
- Ease the definition of pod limit
Note that the docker-registry-secrets are not set up: it should not be needed (as the images `jenkinsciinfra/*` are not rate limited)
> feat(cik8s) add a new 'jenkins-agents-bom' namespace ready for handling 'bom' builds

- config/datadog_cik8s.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3521.
> fix(datadog in cik8s) ensure datadog agent runs on all node pools

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
Needed for https://github.com/jenkins-infra/packer-images/pull/606
Ref: https://github.com/jenkins-infra/helpdesk/issues/2778
> chore(infra.ci): separated updatecli pipeline for `packer-images`

- config/jenkins_infra.ci.jenkins.io.yaml
Same as https://github.com/jenkins-infra/jenkins-infra/pull/2774
> fix(infra.ci): add suffix to the packer-image gallery name

- config/mirrorbits.yaml
- Current used disk space is 486 Gb which is over the 80% threshold with a 500 Gib volume => setting it to `1000 Gib`
- Switch to CSI-premium tier to ensure performances
- Use CSI native options to eavoid any kind of "autoamtic" migration
- Fine tuned the mount options: only the owner should be able to write
> hotfix(prodpublick8s) migrate mirrorbits PV to native CSI, use a 1000 Gib size and fine-tune mountoptions

- config/mirrorbits.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/3525 (incident on the service get.jenkins.io).
As per datadog metrics for the past week:
- The deployment `mirrorbit` does not use as much resources as its resources definitions states, let's decrease:
- The deployment `mirrorbit-files` is constantly OOM killed: its resources definition is too low compared to what we observe on datadog:
- Decrease the amount of replicas to `2` to reduce pressure on the persistent volume which seems really busy on Azure side:
> fix(prodpublick8s) tune mirrorbit to fit resource usage

- clusters/prodpublick8s.yaml
- config/accountapp.yaml
Needs https://github.com/jenkins-infra/helm-charts/pull/495
The corresponding SMTP accounts credentials has been stored in accountapp secrets.
Ref: https://github.com/jenkins-infra/helpdesk/issues/3534#issuecomment-1521371887
> chore(accountapp): switch mail provider from Sendgrid to Mailgun

- Jenkinsfile_k8s
Fixup of #3877 
The method `credentials()` for declarative pipeline does not behave as expected when called withint a Groovy interpolation.
`cik8s` is the default (as it is an ephemeral cluster).
>  fix: pipeline credentials for AWS clusters 

- clusters/cik8s.yaml
- config/autoscaler_cik8s.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3542
This PR updates the values of some helmfile releases installed in `cik8s` to map to the new values (as per the creation of the new `cik8s` cluster).
> fix(cik8s) update AWS environement values (ARNs, namespaces etc.)

- clusters/cik8s.yaml
- config/jenkins-kubernetes-agents_ci.jenkins.io_cik8s-experiments.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3521#issuecomment-1521474486
This PR adds a new namespace for agents in `cik8s`. This namespace is expected to host "experiments" with new node pools/resources.
Updatecli PR will follow once merge, to update the quotas.
> feat(cik8s) add a new agent namespace to support experiments

- config/jenkins_infra.ci.jenkins.io.yaml
in order to simplify testing between AWS and AZURE vm
> chore(infra.ci): add aws and azure as label for arm64 VM

- config/jenkins_infra.ci.jenkins.io.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3567#issuecomment-1539563324
Twin of https://github.com/jenkins-infra/jenkins-infra/pull/2821
> fix(jenkins::controller) do not use ACP for maven repositories with id `local`

- config/jenkins_release.ci.jenkins.io.yaml
Follow up of https://github.com/jenkins-infra/docker-inbound-agents/pull/77
The `jnlp-windows` base pod template is not used by the release jobs (they have their own yaml definition) but it's a nice feature to provide a base working image to allow extending from in the future => that's why this PR updates the image instead of removing the template (as you suggested to not remove it)
> cleanup(release.ci) change default (unused) windows inbound agent container image

- clusters/eks-public.yaml
Avoid surcharging DNS requests from AWS clusters.
Related: https://github.com/jenkins-infra/helpdesk/issues/3559
> chore: remove custom Datadog HTTP checks from `eks-public` cluster

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
Follow-up of https://github.com/jenkins-infra/docker-datadog/pull/13
> chore: remove `docker-datadog` from infra.ci.jenkins.io jobs

- config/ldap.yaml
This `azure.ci` A record points to ci.jenkins.io IP and is not used anymore.
> chore(ldap): fix comment about inbound LDAPS from ci.jenkins.io instead of azure.ci.jenkins.io

- clusters/prodpublick8s.yaml
- clusters/publick8s.yaml
- updatecli/updatecli.d/charts/jenkins.yaml
> chore(weekly.ci.jenkins.io): migrate from `prodpublick8s` to `publick8s`

- config/ldap.yaml
The previous one was a range pointing to the "publick8s" (ie the current prodpublick8s) outbound IPs from two years ago.
> fix(ldap): correct publick8s outbound IP allowed

- config/jenkins_weekly.ci.jenkins.io.yaml
I checked something with design library this morning and noticed all jobs on weekly.ci are gone, and the header used to be plain text. Mark restored the previous header layout by flipping the security switch from plain text to safe html.
Therefore, I assume something (probably unintended) did happen to weekly.ci, I'm not aware of 👀 
A quick glance over the permission matrix on weekly.ci reveals I'm not permitted to modify jobs through the UI. Hence, I chose to come up with this JCasC approach, based on what I remember we had on weekly.ci.
> Restore example jobs on weekly.ci

- clusters/prodpublick8s.yaml
- clusters/publick8s.yaml
> chore(javadoc): migrate from `prodpublick8s` to `publick8s`

- clusters/prodpublick8s.yaml
- clusters/publick8s.yaml
> chore(wiki): migrate from `prodpublick8s` to `publick8s`

- updatecli/updatecli.d/charts/wiki.yaml
> fixup(updatecli): correct target for `wiki` helm chart manifest

- config/jenkins_weekly.ci.jenkins.io.yaml
If you're a darkmode user and not logged into weekly.ci, your os theme set is now respected properly.
> Respect users' os theme on weekly.ci

- config/jenkins_infra.ci.jenkins.io.yaml
- config/jenkins_weekly.ci.jenkins.io.yaml
Blocked by https://github.com/jenkins-infra/docker-jenkins-weekly/pull/1244
If I recall correctly, infra.ci pulls the weekly image too. Hence, I disabled the plugin on the infra configuration.
Preview:
> Configure custom header plugin

- config/keycloak.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3351,
This PR fixes the keycloak configuration, following up https://github.com/jenkins-infra/kubernetes-management/pull/3983, for the Dual-Stack setup as it was failing to start with the same errors as in https://github.com/codecentric/helm-charts/issues/415
The current fixup uses the IPv6 interfaces in the pod to listen, but it looks like it's breaking the HA module so the Jgroup setup has been cleaned up.
> hotfix(publick8s) adapt keycloak setup for Ipv6

- config/jenkins_weekly.ci.jenkins.io.yaml
Reverts jenkins-infra/kubernetes-management#3991 as it causes the following error in weekly.ci.jenkins.io logs (at startupt):
```
2023-05-26 11:11:09.565+0000 [id=28]	SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed ConfigurationAsCode.init
io.jenkins.plugins.casc.ConfiguratorException: Invalid configuration elements for type class io.jenkins.plugins.customizable_header.CustomHeaderConfiguration : header.
Available attributes : cssResource, enabled, headerColor, logo, logoText, title
at io.jenkins.plugins.casc.BaseConfigurator.handleUnknown(BaseConfigurator.java:375)
at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:364)
at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:286)
at …
```
> Revert "Enable context aware headers on weekly.ci"

- updatecli/updatecli.d/charts/plugin-health-scoring.yaml
Follow up of https://github.com/jenkins-infra/kubernetes-management/pull/4000
> chore(updatecli) fix PHS manifest to use publick8s

- config/jenkins_weekly.ci.jenkins.io.yaml
There is no `pullPolicy` value property in https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml
> fix(weekly.ci.jenkins.io): replace `pullPolicy` field name by `imagePullPolicy`

- config/artifact-caching-proxy_azure.yaml
- config/incrementals-publisher.yaml
- config/javadoc.yaml
- config/jenkins_weekly.ci.jenkins.io.yaml
- config/keycloak.yaml
- config/plugin-health-scoring.yaml
- config/rating.yaml
- config/uplink.yaml
- config/wiki.yaml
This PR ensures pods are assigned to [`x86medium` node pool](https://github.com/jenkins-infra/azure/blob/ecdcc7369199b8494f4b63fd28c240187ac61e49/publick8s.tf#L84-L96) in `publick8s`, and avoid mixing type of nodes for a same service.
~For smaller services, the cheaper [`arm64small` node pool](https://github.com/jenkins-infra/azure/blob/ecdcc7369199b8494f4b63fd28c240187ac61e49/publick8s.tf#L98-L110) has been privileged, while other has been assigned to the `publicpool` by default.~
Ref: https://github.com/jenkins-infra/helpdesk/issues/3351 ~& https://github.com/jenkins-infra/helpdesk/issues/3584~
> fix(publick8s): add `nodeSelector` to migrated services

- config/reports.yaml
As there is no associated record in the `jenkins-ci.org` DNS zone in Azure Portal, this PR removes it.
Ref: https://github.com/jenkins-infra/kubernetes-management/pull/4028#discussion_r1214099796
> chore(reports): remove nonexistant `reports.jenkins-ci.org` ingress host & TLS

- updatecli/updatecli.d/charts/jenkins-infra-tools-maven.yaml
follow up https://github.com/jenkins-infra/packer-images/pull/701
and correct : 
```
ERROR: ✗ No line matched in the file "https://raw.githubusercontent.com/jenkins-infra/packer-images/1.10.0/provisioning/tools-versions.yml" for the pattern "maven_version:\\s\"(.*)\""
Pipeline "Bump Maven version (Jenkins tools) on infra.ci.jenkins.io" failed
```
> chore(updatecli): correct maven manifest

- clusters/publick8s.yaml
- config/ldap.yaml
- updatecli/updatecli.d/charts/ldap.yaml
This PR adds the LDAP service to `publick8s` cluster, with a new secret configuration using the new storage account with restricted access created in https://github.com/jenkins-infra/azure/pull/392 instead of the existing one which will be removed at the end of the migration described in https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1576741071
> chore(ldap): deploy to `publick8s`

- config/private-nginx-ingress_publick8s.yaml
- config/public-nginx-ingress_publick8s.yaml
https://github.com/jenkins-infra/kubernetes-management/pull/4034 is failing to deploy: AKS tries to schedule the new pods to the `arm64small` nodepool.
This PR is a short-term to ensure nginx ingresses, on `publick8s`, are scheduled on the nodepool name `x86medium`.
=> long term, we should start using toleration and taints to avoid implicit scheduling to ARM64 (and eventually a generic nodeSelector that could span across multiple node pools to allow use doing blue/green on node pools)
> fix(publick8s) stick ingress pods to x86medium (intel) nodepool

- config/jenkins_infra.ci.jenkins.io.yaml
This exception is added to fix the build of https://github.com/jenkinsci/ircbot-plugin which relies on https://github.com/pircbotx/pircbotx/ whose binary releases (and snapshots) are published to https://jitpack.io/#pircbotx/pircbotx/, not mirrored in our Maven repositories for now.
Twin PR: https://github.com/jenkins-infra/jenkins-infra/pull/2895
Ref: https://github.com/jenkins-infra/helpdesk/issues/3591
> fix(artifact-caching-proxy): add exception for `jitpack.io` Maven repository

- clusters/publick8s.yaml
- config/ldap.yaml
- config/ldap_publick8s.yaml
- updatecli/updatecli.d/charts/ldap.yaml
Same as #4042 but without modifying the existing LDAP release on `prodpublick8s`.
> This PR adds the LDAP service to `publick8s` cluster, with a new secret configuration using the new storage account with restricted access created in https://github.com/jenkins-infra/azure/pull/392 instead of the existing one which will be removed at the end of the migration described in https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1576741071
> chore(ldap): deploy to `publick8s` and set its load balancer to use a public IP defined as code

- clusters/prodpublick8s.yaml
Follow-up of #4044
A proper cleanup will be made at the end of the migration.
Ref: https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1576741071
> chore: remove `ldap` release from `prodpublick8s`

- config/datadog_confd_checksd.yaml
This PR removes unwanted text I commited by mistake in https://github.com/jenkins-infra/kubernetes-management/pull/3919
Ref: https://github.com/jenkins-infra/helpdesk/issues/3608
> fix(datadog): remove typo from `packageCanBeDownloaded.py` check

- clusters/prodpublick8s.yaml
- clusters/publick8s.yaml
- config/mirrorbits.yaml
- updatecli/updatecli.d/charts/mirrorbits.yaml
In draft until 12:00 UTC (cf https://github.com/jenkins-infra/status/pull/316)
Ref: https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1586969797
> chore(mirrorbits): migrate from `prodpublick8s` to `publick8s`

- clusters/prodpublick8s.yaml
- clusters/publick8s.yaml
- config/jenkinsio.yaml
- updatecli/updatecli.d/charts/jenkinsio.yaml
Ref: https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1588040182
> chore(jenkins.io): migrate from `prodpublick8s` to `publick8s`

- config/datadog_confd_checksd.yaml
Ref: https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1591316525
> cleanup(datadog): remove `mirror.azure.jenkins.io` mirror monitoring

- config/plugin-site-issues.yaml
Remove this host, initially planned for a use with Fastly CDN like plugin-site and jenkins.io
> cleanup(plugin-site-issues): remove unused `plugin-site-issues.origin.jenkins.io` host

- Jenkinsfile_k8s
as per https://docs.digitalocean.com/products/kubernetes/how-to/upgrade-cluster/#new-control-plane we have to disable any action on digital ocean clusters 
to follow the process use https://github.com/jenkins-infra/helpdesk/issues/3582
> feat(doks/doks-public) disabling during upgrade to 1.25

- Jenkinsfile_k8s
Reverts jenkins-infra/kubernetes-management#4099
as per https://github.com/jenkins-infra/helpdesk/issues/3582
> Revert "feat(doks/doks-public) disabling during upgrade to 1.25"

- clusters/publick8s.yaml
Reverts jenkins-infra/kubernetes-management#4141 including the switch from NodeJS 16 to NodeJS 18 causing https://github.com/jenkins-infra/incrementals-publisher/issues/45
Ref: https://github.com/jenkins-infra/helpdesk/issues/3649
> Revert "Bump `incremental-publisher` helm chart version to 0.5.6"

- config/javadoc.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/3582#issuecomment-1629210833
> hotifx(publick8s) put back javadoc workload to the arm64small nodepool

- config/datadog_publick8s.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3623#issuecomment-1613504371
and datadog documentation: https://github.com/DataDog/helm-charts/blob/f5c0c8699fcb1d19b87c964f6a13dc228a213414/charts/datadog/values.yaml#L1575
> feat(publick8s): add arm64 toleration for datadog agents

- config/reports.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3619#issue-1745920424
this allow the reports deployment to use the arm64 node-pool in order to save some spending.
> feat(publick8s): migrate reports to arm64 nodepool

- config/jenkins_infra.ci.jenkins.io.yaml
Same as https://github.com/jenkins-infra/jenkins-infra/pull/2992
Ref: https://github.com/jenkins-infra/helpdesk/issues/3599#issuecomment-1653881431
> feat(infra.ci.jenkins.io): do not use ACP for the `central` Maven repository

- config/jenkinsio.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3686
Forcing to SSL redirect is the default: https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md#server-side-https-enforcement-through-redirect
> feat(publick8s) Force SSL redirect for jenkinsio

- config/jenkins_infra.ci.jenkins.io.yaml
This PR activates [ANSI color](https://plugins.jenkins.io/ansicolor/) globally on infra.ci.jenkins.io
<details><summary>Screenshots:</summary>
Without ANSI color:
With ANSI color only:
With ANSI color and default background set to "White":
</details>
> feat(infra.ci.jenkins.io): activate ANSI color globally

- config/mirrorbits.yaml
The httpd docker image tag is already kept upto date in the mirrorbits helm chart
> Remove httpd image tag from mirrorbits

- config/mirrorbits.yaml
Follow-up of #4236 
Mirrorbits Docker image changelog: https://github.com/jenkins-infra/docker-mirrorbits/compare/v0.1.2...0.1.94: zero functional change to the mirrorbits app.
> feat: cleanup `mirrorbits` values now included by default in its chart and bump it from `0.1.2` to `0.1.94`

- clusters/publick8s.yaml
- config/accountapp.yaml
`IfNotPresent` is already the default value: https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting
Supersedes and closes https://github.com/jenkins-infra/kubernetes-management/pull/4249
> chore(accountapp): remove default `image.pullPolicy`

- config/jenkins_infra.ci.jenkins.io.yaml
- config/jenkins_release.ci.jenkins.io.yaml
- config/jenkins_weekly.ci.jenkins.io.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3072, this PR switches the 3 Jenkins controllers managed in this repository (weekly.ci.jenkins.io, infra.ci.jenkins.io and release.ci.jenkins.io) to JDK17 instead of JDK11.
Superseds and closes #4267 and #4266
> feat((weekly,infra,release).ci.jenkins.io) switch JVM to JDK17

- clusters/publick8s.yaml
- config/updates.jenkins.io.yaml
From https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-1688304653:
> Hopping mirrorbits accepts different domains for mirror URL and mirror rsync address, I [have] transplant[ed] the rsyncd part of the deleted mirror chart which was used for azure.mirror.jenkins.io decomissionned mirror service (https://github.com/jenkins-infra/helm-charts/pull/607) in the mirrorbits chart[.]
> 
> With this rsyncd service using the same local reference volume of mirrorbits, we should then be able to add the R2 bucket mirror, associated with this rsyncd service address.
Follow-up of https://github.com/jenkins-infra/helm-charts/pull/609
Ref: https://github.com/jenkins-infra/helpdesk/issues/2649
> feat(updates.jenkins.io): add rsyncd service

- config/ldap.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3688, this PR allows incoming requests from the cert.ci.jenkins.io virtual network to the LDAP
> feat(ldap) add new cert.ci vnet outbound IP

- config/ldap.yaml
Related to jenkins-infra/helpdesk#3688
> cleanup(ldap) remove legacy public IP of cert-ci from allow-list

- clusters/publick8s.yaml
Reverts jenkins-infra/kubernetes-management#4306
> Revert "Bump `mirrorbits` helm chart version to 0.65.0"

- config/wiki.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3619
and now that the docker image is arm64 compliant thanks to https://github.com/jenkins-infra/pipeline-library/pull/730 and https://github.com/jenkins-infra/pipeline-library/pull/739
following the PR #4309 that provide an image compatible both with amd64 and arm64.
we can provide the settings to spawn on ARM64 nodepool
> feat(wiki): add nodeselector and tolerations to spawn on arm64 nodepool

- clusters/publick8s.yaml
To work on https://github.com/jenkins-infra/helpdesk/issues/2649 I need to do some tests with resources used by the current updates.jenkins.io POC release.
This PR comments out this release temporarily.
> chore(updates.jenkins.io): comment out release temporarily

- config/jenkins_infra.ci.jenkins.io.yaml
Configuring https://plugins.jenkins.io/customizable-header already [present in our weekly image](https://github.com/jenkins-infra/docker-jenkins-weekly/blob/f6e01a2e06b18411ae49b974956cba5bd0aa152d/plugins.txt#L56), similar to [what's already set on weekly.ci.jenkins.io](https://github.com/jenkins-infra/kubernetes-management/blob/79b6abcd54527d4dae0eb3718e0c771cc7c65c78/config/jenkins_weekly.ci.jenkins.io.yaml#L131-L144).
Before:
Light theme:
Dark theme:
Note: not a fan but there is also an option to use a custom "context aware" logo, which outside of the homepage replace the beekeeper logo by the current page icon (not activated in this PR).
<details>
</details>
> feat: add custom header to `infra.ci.jenkins.io`

- config/jenkins_infra.ci.jenkins.io.yaml
Fixup of #4273, I didn't notice there was already a configuration section for this plugin, with `enabled` set to `false` and causing the following error:
> io.jenkins.plugins.casc.ConfiguratorConflictException: Found conflicting configuration at YamlSource: /var/jenkins_home/casc_configs/system-settings.yaml  in /var/jenkins_home/casc_configs/system-settings.yaml, line 36, column 14:
>         enabled: false
> fixup(infra.ci.jenkins.io): remove conflicting previous `custom-header` configuration

- PodTemplates.yaml
Follow-up of #4328
Ref: https://github.com/jenkins-infra/kubernetes-management/pull/4320#issuecomment-1713183980
> chore(updatecli): fix `key "$.spec.containers[0].name", in YAML file "PodTemplates.yaml", is incorrectly set to "\"jnlp\""`

- clusters/publick8s.yaml
This reverts commit 1d28d3114843c0cb569a13351f32e36f09d67725.
> Revert "Bump `wiki` helm chart version to 0.3.98 (#4333)"

- config/wiki.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3719
> feat(wiki): apply antiaffinity rule to avoid multiple pods on the same node

- config/jenkins_infra.ci.jenkins.io.yaml
Twin of https://github.com/jenkins-infra/jenkins-infra/pull/3070 but for infra.ci.jenkins.io
- https://maven.apache.org/guides/mini/guide-mirror-settings.html#AdvancedMirrorSpecification mentions that `external:*` is a pattern matching "all repositories" except URLs to localhost or file based.
- Found in https://github.com/jenkinsci/maven-hpi-plugin/pull/537 which pointed to https://maven.apache.org/plugins/maven-invoker-plugin/examples/fast-use.html#fast-build-configuration-mergeusersettings-and-mirrors
- Remove the `!local` exception added as part of https://github.com/jenkins-infra/helpdesk/issues/3567 (replaced by the `external:` pattern)
> fix(ci.jenkins.io) exclude all externals Maven repositories from ACP mirroring

- config/jenkins_infra.ci.jenkins.io.yaml
We tried improving the pipelone output logs in https://github.com/jenkins-infra/kubernetes-management/pull/4238.
But since then, it has been impossible to read the pipeline outputs or copy and past. This PR removes the configuration to go back to the default state.
> feat(infra.ci) disable ANSI color to allow reading pipeline logs

- config/wiki.yaml
to avoid autoscaler to reduce to one single node with both pods
> feat(wiki): revert back to hard anti affinity rule

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
This PR adds a job for https://github.com/jenkins-infra/cloudflare.
Corresponding secrets have been generated via https://github.com/jenkins-infra/terraform-states (private repository), and stored in infra.ci.jenkins.io secrets (https://github.com/jenkins-infra/charts-secrets, also a private repository).
Preliminary work for https://github.com/jenkins-infra/cloudflare/pull/1
Ref: https://github.com/jenkins-infra/helpdesk/issues/2649
> feat(infra.ci.jenkins.io): add CloudFlare terraform job

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
This PR moves this job which is only running updatecli.
We don't really care about build history for this job.
If it was the case, it would have needed to create the new job first, then connect into the controller and manually move the build history to this new job, then delete the old job.
> chore(infra.ci.jenkins.io): move `helm-charts` job from `Kubernetes Management` folder to `Dependencies Management`

- config/jenkins_infra.ci.jenkins.io.yaml
While working on https://github.com/jenkins-infra/packer-images/pull/819, I realized we never added the support of Windows 2022 Azure VM agents.
This PR fixes it to allows using Windows 2022 container images in infra.ci.jenkins.io.
💡 Note: following https://learn.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-2022%2Cwindows-11#windows-server-host-os-compatibility, we should be able to test running 2019 containers on 2022 host OS with success which should greatly simplify configuration in the future to only support 1 Windows line.
> feat(infra.ci.jenkins.io) add support for Windows 2022 Azure VM agents

- config/uplink.yaml
Since we deployed https://github.com/jenkins-infra/kubernetes-management/pull/4437, we realized that the node pool scaled from 3 to 5 nodes to fulfill the antiaffinity hard constraint.
The question is: do we need that much of replicas?
Looking at datadog shows that, NO we don't:
💡 We keep 2 replicas to ensure HA
> feat(publick8s) shring uplink replicas from 5 to 2

- config/jenkinsio.yaml
As it is only a backend for fastly, no need to spin up so many pods.
The idea is to avoid the same issue as https://github.com/jenkins-infra/kubernetes-management/pull/4444 and to avoid running too much process (and VMs) when we don't need it.
(edit) A few CPU and memory metrics for the pods of the `jenkinsio` namespace from the past 3 months demonstrating that don't need that much:
💡 We keep 2 replicas to ensure HA
> feat(publick8s) shrink jenkinsio replicas from 5 to 2 

- config/jenkins_release.ci.jenkins.io.yaml
Similar to https://github.com/jenkins-infra/kubernetes-management/pull/4273, custom header for https://release.ci.jenkins.io
Light theme:
Dark theme:
Dark theme, fullscreen:
<details><summary>Before</summary>
</details>
<details><summary>After</summary>
</details>
Note: thinking of a blue gradient for trusted.ci.jenkins.io, and of a green one for cert.ci.jenkins.io
> feat: add custom header to `release.ci.jenkins.io`

- config/public-nginx-ingress_publick8s.yaml
Since https://github.com/jenkins-infra/kubernetes-management/pull/4415 (see https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v1.9.0), the custom user snippet in Ingress annotations has been disabled by default.
By enabling the snippet annotations on the public ingress of the `publick8s`, this PR fixes the deployment errors like below caused by this 4.8.0 deployment
```
Error: UPGRADE FAILED: release <redacted> failed, and has been rolled back due to atomic being set: cannot patch "<redacted>" with kind Ingress: admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: nginx.ingress.kubernetes.io/configuration-snippet annotation cannot be used. Snippet directives are disabled by the Ingress administrator
```
💡As seen with @smerle33 we still use these …
> fix(publick8s) enable snippet annotations for public ingress

- PodTemplates.yaml
This reverts commit a0241601c51c9f55b3a234f66f55dac0bc5a7acf.
The kubernetes-management job is failing with
> ERROR: Unable to pull Docker image "jenkinsciinfra/helmfile:3.0.17". Check if image tag name is spelled correctly.
> Revert "Bump jenkins-infra helmfile docker image to 3.0.17 (#4455)"

- PodTemplates.yaml
Reverts jenkins-infra/kubernetes-management#4463
The image is probably fine, there seems to be an issue with Docker Hub, reverting this revert, see https://github.com/jenkins-infra/helpdesk/issues/3767#issuecomment-1739988362
> Revert "Revert "Bump jenkins-infra helmfile docker image to 3.0.17 (#4455)""

- config/jenkins_infra.ci.jenkins.io.yaml
Reverts jenkins-infra/kubernetes-management#4467
as it timed out on azure with the 1.27.1 version
> Revert "Bump agent templates for infra.ci.jenkins.io (packer-image 1.27.1)"

- clusters/publick8s.yaml
Self merging as it is an hotfix already applied in production
> hotfix(publick8s) bump plugin-site to 0.3.2

- clusters/publick8s.yaml
Reverts jenkins-infra/kubernetes-management#4521
error with the content type header 
```
<br />
<b>Warning</b>:  Undefined array key "callback" in <b>/var/www/html/rate/result.php</b> on line <b>45</b><br />
<br />
<b>Warning</b>:  Undefined array key "json" in <b>/var/www/html/rate/result.php</b> on line <b>48</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by 
```
> Revert "Bump `rating` helm chart version to 0.3.1"

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3751 to test the PR on the shared pipeline library
> feat(privatek8s) disable Tag discovery for wiki/docker-confluence jobs in infra.ci.jenkins.io

- clusters/cik8s.yaml
- clusters/doks-public.yaml
- clusters/doks.yaml
- clusters/eks-public.yaml
- clusters/privatek8s.yaml
- clusters/publick8s.yaml
Reverts jenkins-infra/kubernetes-management#4519
We received Pagerduty alerts since 24h on the rating.jenkins.io web service.
The synthetics and the jenkins.io pages shows the service is running perfectly.
Checking in datadog, the metrics collected since Wed. 11 Oct. 2023 15h10 GMT+2 have the field `cluster_name` empty, but *only* for the `url` https://rating.jenkins.io.
However jenkins-infra/kubernetes-management#4519 was deployed at 15h08. Coincidence? I think not.
Besides, digging in the datadog agent changelog:
- https://github.com/DataDog/datadog-agent/releases/tag/7.48.0 is fine but checking the agent version 7.48.0:
- https://github.com/DataDog/integrations-core/blob/master/AGENT_CHANGELOG.md#datadog-agent-version-7480 shows:
> Kubernetes API server metrics 4.0.0 BREAKING CHANGE
- …
> Revert "Bump `datadog` helm chart version to 3.40.0"

- config/public-nginx-ingress_publick8s.yaml
Similar to https://github.com/jenkins-infra/kubernetes-management/pull/4540
Status announcement: https://github.com/jenkins-infra/status/pull/390
Ref: https://github.com/jenkins-infra/helpdesk/issues/3619#issuecomment-1713522131
> feat(publick8s): migrate `public-nginx-ingress` controller and default backend to arm64

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
Reverts jenkins-infra/kubernetes-management#4515
This revert is only there to deliver https://github.com/jenkins-infra/docker-confluence-data/pull/50
> Revert "feat(privatek8s) disable Tag discovery for wiki/docker-confluence jobs in infra.ci.jenkins.io"

- config/mirrorbits.yaml
Reverts jenkins-infra/kubernetes-management#4577
Mirrorbits:
> exec /bin/tini: exec format error 
Files:
> exec /usr/local/bin/httpd-foreground: exec format error
> Revert "feat(publick8s): migrate `mirrorbits` to arm64"

- Jenkinsfile_k8s
This reverts commit 631789bf01e289f275217dd70da81ed7ae502fa2.
It enables the management of the 2 clusters `doks` and `doks-public` after their upgrade to Kubernetes 1.26
> Revert "feat(doks, doks-public) disable clusters management (#4588)"

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
This PR adds `uplink` to the Docker jobs on infra.ci.jenkins.io.
- Closes https://github.com/jenkins-infra/uplink/issues/39
- Related: https://github.com/jenkins-infra/uplink/pull/42
- Ref: https://github.com/jenkins-infra/helpdesk/issues/3619
> feat: add `uplink` to the Docker jobs on `infra.ci.jenkins.io`

- config/updates.jenkins.io.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/2649
provide a service account to trigger mirrobits scan for mirrors
> feat(publick8s): adding a service account for mirrorbits for update.jenkins.io

- config/updates.jenkins.io.yaml
This PR fixes the failing ingress matching for (azure.)updates.jenkins.io by ensuring the regexp engine is enabled for Nginx (same as get.jenkins.io in fact: annotation was lost when I bootstraped the mirrorbits-parent chart).
> fix(publick8s) ensure regexp engine is enabled for updates.jenkins.io ingress paths

- config/uplink.yaml
Reverts jenkins-infra/kubernetes-management#4609
The pod image deployed to an arm64 node corresponds to the amd64 architecture, and thus was in crashloopbackoff:
https://github.com/jenkins-infra/helm-charts/blob/773d4f596d73df1ca15401de848895b8548add44/charts/uplink/values.yaml#L7
> Revert "feat(publick8s): migrate `uplink` to arm64"

- clusters/publick8s.yaml
- config/uplink.yaml
Reverts jenkins-infra/kubernetes-management#4610
Includes https://github.com/jenkins-infra/helm-charts/pull/903
> feat(publick8s): migrate `uplink` to arm64 (second shot)

- config/jenkins_infra.ci.jenkins.io.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3783
This PR adds the JDK21 tool installation on the infra.ci.jenkins.io controller
> feat(privatek8s) add JDK21 tool installation on infra.ci.jenkins.io

- config/jenkins_infra.ci.jenkins.io.yaml
- updatecli/scripts/check-jdk.sh
- updatecli/updatecli.d/jenkins-controllers/tools-jdk11.yaml
- updatecli/updatecli.d/jenkins-controllers/tools-jdk17.yaml
- updatecli/updatecli.d/jenkins-controllers/tools-jdk21.yaml
- updatecli/updatecli.d/jenkins-controllers/tools-jdk8.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3783, this PR adds updatecli manifests to track the JDK tool installation versions for JDK8, JDK11, JDK17 and JDK21.
To test the manifest, I've used it to update locally:
- JDK8 to `8u392-b08` (`updatecli apply` without `scmid` in targets)
- JDK11 to `11.0.16.1+1` (`updatecli apply` without `scmid` in targets)
- JDK17 to `17.0.8.1+1` ( Custom source + `updatecli apply` without `scmid` in targets) => this is the last version with x64_windows in the same version as Linux
Note: JDK21 is already up to date since #4629 
Note 2: https://github.com/updatecli/updatecli/issues/1733 would help to simplify the manifests here A LOT
> privatek8s: track JDK tool installations with `updatecli` + bump JDK8, JDK11 and JDK17 to latest available version

- config/cert-manager_publick8s.yaml
This PR migrates the two other services of cert-manager to arm64 on publick8s.
Current nodes used by cert-manager pods:
Follow-up of:
- #4576 
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3619
> feat(publick8s): migrate `cert-manager`'s cainjector and webhook to arm64

- config/datadog_publick8s.yaml
This PR removes the arm64 toleration (constraint) for the `datadog` pods. (Related: LDAP PagerDuty alert)
Fixup of:
- #4575 
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3619
> fixup(publick8s): don't force `datadog` pods to be only on arm64 nodes

- clusters/publick8s.yaml
- config/ipv6-lb-service.yaml
- config/ldap.yaml
- config/public-nginx-ingress_publick8s.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3683#issuecomment-1798182954
WARNING : 
if we change : `service.beta.kubernetes.io/azure-load-balancer-ipv4` and replace it with `service.beta.kubernetes.io/azure-pip-name` we will endup having twice the key `service.beta.kubernetes.io/azure-pip-name` one for ipv4 one for ipv6. 
`Map keys must be unique` as we have one for ipv4 and one for ipv6 !
it seems that the service.beta.kubernetes.io/azure-pip-name is not mandatory to be able to use `service.beta.kubernetes.io/azure-load-balancer-resource-group`
--- 
Requires https://github.com/jenkins-infra/helm-charts/pull/933 and https://github.com/jenkins-infra/helm-charts/pull/934
Closes #4650 #4651
> feat(publick8s): change LB annotation to move public ips RG

- config/jenkins_infra.ci.jenkins.io.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/3812
This PR ensures we use the same kind of instance (lower costs for spots) with ephemeral disks (faster startup and no $$ to pay for managed disks).
Note that our quota might be limiting : let's keep it like this for now until we start using the new MSOP subscription.
> feat(infra.ci) align Azure-VM agent sizing with ci.jenkins.io

- config/updates.jenkins.io.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-1808612479
This PR fine tune the ingress rule of update.jenkins.io to only send requests ending with `.json`, `.html` or `.txt` extensions to mirrorbits:
- The https://updates.jenkins.io/ URL will still be sent to Apache (which has all the files) so it can serve the index.html file as the default file before trying listing diretctories
- All other `html` and `txt` files are copied to the mirror along the `json` files (both UC and crawler)
> feat(publick8s) fine tune ingress rule for updates.jenkins.io

- config/updates.jenkins.io.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3619#issuecomment-1816831551
ARM64 version of 
- `httpd`: https://hub.docker.com/layers/library/httpd/2.4.58/images/sha256-032af99592618d77a391821b7ada3d1917c274a34a62688c847de8a7b017bfbc?context=explore
no sha : https://github.com/jenkins-infra/helm-charts/blob/109c46956afc2f37fdfedf306cde4f3a21666e53/charts/httpd/values.yaml#L7
- `rsyncd`: https://hub.docker.com/layers/jenkinsciinfra/rsyncd/1.0.13/images/sha256-0a88d7a622d241f7c177ad5a44ac4fde3eaf60a984b72af960bc11429e2d0a75?context=explore
sha : https://github.com/jenkins-infra/helm-charts/blob/109c46956afc2f37fdfedf306cde4f3a21666e53/charts/rsyncd/values.yaml#L6C22-L6C86. : `tag: 1.0.13@sha256:d3ed3a8438f0927b5b5e518a53feb098e4d7520433aa20ec20c7398830bb6245`
> feat(publick8s): migrate mirrorbits-parents, httpd and rsync to arm64

- clusters/publick8s.yaml
- config/contributors.jenkins.io.yaml
- updatecli/updatecli.d/charts/nginx-website.yaml
This PR adds a release for deploying `nginx-website` helm chart on `publick8s` cluster with `contributorsjenkinsio` storage account mounted as volume to serve the content generated by https://github.com/jenkins-infra/contributor-spotlight/ on https://contributors.origin.jenkins.io, to be cached by Fastly CDN.
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3809#issuecomment-1822357561
> feat(publick8s): add `contributors.jenkins.io`

- clusters/publick8s.yaml
- config/contributors.jenkins.io.yaml
Follow-up of https://github.com/jenkins-infra/helm-charts/pull/961, revert outdated hotfix https://github.com/jenkins-infra/kubernetes-management/commit/208c32f4366a322d3a3a3d65e6783a92c33776b9
> fix(contributors.jenkins.io): correct secret name

- config/jenkins_release.ci.jenkins.io.yaml
Before:
After:
Additionally, I've reversed the gradient, so its color intensity goes from left to right, instead of right to left.
> Use a less aggressive red for release.ci's header

- config/updates.jenkins.io.yaml
Fix the following warnings from kubernetes-management build logs:
```
+ yamllint --config-file yamllint.config config
config/updates.jenkins.io.yaml
8:55      warning  too few spaces before comment  (comments)
14:42     warning  too few spaces before comment  (comments)
```
> chore(updates.jenkins.io): remove yamllint warnings

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
This PR adds File Share SAS query string credentials to contributors.jenkins.io job on infra.ci.jenkins.io to update the webiste content with azcopy.
Corresponding secret added in the private repo charts-secrets: https://github.com/jenkins-infra/charts-secrets/commit/9e59870ebab7497c084d3e790d09e481338dcadd
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3809#issuecomment-1822357561
> chore(contributors.jenkins.io): add File Share SAS query string credentials

- config/jenkins_infra.ci.jenkins.io.yaml
https://hub.docker.com/layers/jenkinsciinfra/builder/3.1.0/images/sha256-7150f769249c071fec7ee18338183193c36d489dc9a2fb2d211242fcc89350cd?context=explore
> chore: Bump docker-builder to 3.1.0

- config/datadog_publick8s.yaml
- config/falco.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3827
specify a toleration for datadog and falco in order to get spawn on system nodepool after we tainted it
> feat(publick8s): adding a toleration for system nodepool on datadog and falco

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
This PR specifies the unique Jenkinsfile to use for plugin-site job on infra.ci.jenkins.io
Ref:
- https://github.com/jenkins-infra/plugin-site/issues/1377
> chore: unique Jenkinsfile for plugin-site

- clusters/privatek8s.yaml
Reverts jenkins-infra/kubernetes-management#4754
because it fails to deploy:
- helmfile reaches a timeout in the build
- Trying to deploy manually shows the following errors:
```
Events:
Type     Reason     Age               From               Message
----     ------     ----              ----               -------
Normal   BackOff    16s               kubelet            Back-off pulling image "ghcr.io/timja/github-comment-ops:v1.4.3"
Warning  Failed     16s               kubelet            Error: ImagePullBackOff
Normal   Pulling    3s (x2 over 17s)  kubelet            Pulling image "ghcr.io/timja/github-comment-ops:v1.4.3"
Warning  Failed     3s (x2 over 17s)  kubelet            Failed to pull image "ghcr.io/timja/github-comment-ops:v1.4.3": rpc error: code = NotFound desc = failed to …
```
> Revert "Bump `github-comment-ops` helm chart version to 1.4.3"

- config/jenkins_infra.ci.jenkins.io.yaml
We had VM initializations failing on infra.ci but randomly.
After torough testing with @smerle33 , we did not find any usable logs about the datadog-agent startup.
However, https://github.com/DataDog/datadog-agent/pull/5064 and https://github.com/DataDog/datadog-agent/issues/16559 are tipping us about the permissions in `/etc/datadog-agent` directory which must stay writeable by the user `dd-agent` to allow creation of configurations such as `auth_token` file during the start and stop phases
This PR updates the init script to ensure these permissions are correct:
- Stopping the datadog-agent service as a first step avoid concurence between the datadog-agent process (`dd-agent`) and the init script (`root`)
- Setting ownership to the 2 datadog dirs (config and logs) with a recursive flag …
> fix(infra.ci) ensure azure VM init script for Linux set up proper permissions for datadog-agent config dir

- config/jenkins_infra.ci.jenkins.io.yaml
to avoid temporary error on datadog startup that forbid the VM to be used
> feat(infra.ci): persist usage of VM even if init fail to avoid failure on transiant error from datadog

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
- config/jenkins_infra.ci.jenkins.io.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3818#issuecomment-1868237892
This PR switches to the new azure subscription the following elements:
- The updatecli job configuration (credential value)
- The all in one tempolates for VMs and pod template to 1.43.0
> feat(infra.ci) bump packer-image to 1.43.0 in the new subscription

- config/ldap.yaml
The goal is to pack more containers by compressing requests (scheduler) while keeping sustainable limits
Ref. https://github.com/jenkins-infra/helpdesk/issues/3827
Metrics in datadogs:
> feat(publick8s) tune ldap resources

- config/keycloak.yaml
The goal is to pack more containers by compressing requests (scheduler) while keeping sustainable limits
Ref. https://github.com/jenkins-infra/helpdesk/issues/3827
Metrics in datadogs:
> feat(publick8s) tune keycloak resources 

- config/mirrorbits.yaml
The goal is to pack more containers by compressing requests (scheduler) while keeping sustainable limits
Ref. https://github.com/jenkins-infra/helpdesk/issues/3827
Metrics in datadogs:
> feat(publick8s) tune mirrorbits (get.jenkins.io) resources

- config/updates.jenkins.io.yaml
Tin of https://github.com/jenkins-infra/kubernetes-management/pull/4828 but with a bit more CPU limit (as we expected `.htaccess` addition trafic)
Related to https://github.com/jenkins-infra/helpdesk/issues/3827
> feat(publick8s) tune updates.jenkins.io resources

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3888
This PR enable (and names) the GH checks for all the updatecli the jenkins-infra/contributor-spotlight jobs
> feat(privatek8s) infra.ci: enable github checks for updatecli and contributor-spotlight jobs

- config/jenkins_infra.ci.jenkins.io.yaml
need to correct updatecli manifest
> hotfix(infra.ci): jcasc missing a double quotes

- config/jenkins_release.ci.jenkins.io.yaml
With the removal of remoting from the release infrastructure in https://github.com/jenkins-infra/release/pull/491, I propose to remove remoting from the preconfigured folder and job setup too.
> Remove remoting from release.ci

- config/ldap.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3908
The PR https://github.com/jenkins-infra/azure-net/pull/194 introduced a NAT gateway for ci.jenkins.io, effectively changing its outbound IP
> feat(publick8s) update ci.jenkins.io public IP

- config/ldap.yaml
This PR is related to https://github.com/jenkins-infra/helpdesk/issues/3908#issuecomment-1892555342
It will allow ci.jenkins.io secondary (new) controller to reach LDAP
> feat(publick8s) allow ci.jenkins.io's secondary NAT gateway to LDAP

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
ref. https://github.com/jenkins-infra/helpdesk/issues/3837#issuecomment-1898378430
This PRs adds the `ldap` jobs in infra.ci (in Docker jobs folder)
> feat(privatek8s) add docker-ldap job to infra.ci.jenkins.io

- config/ldap.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3837#issuecomment-1898378430
This PR pins (temporarily) the LDAP image version. Next step would be to update the helm chart (and remove values in this repository) to get them updated.
> feat(publick8s) pin LDAP images to version 1.0.1

- config/jenkins_infra.ci.jenkins.io.yaml
- config/jenkins_release.ci.jenkins.io.yaml
- config/jenkins_weekly.ci.jenkins.io.yaml
The change proposed adds a pipeline overview to the build page:
I have disabled adding the overview to the job page because the pipeline-stage-view plugin clogs up the page with its overview, unfortunately:
> Add a pipeline overview to the build page

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3823
> (un)feat(infra.ci): remove docker-hashicorp-tools  from docker-jobs

- updatecli/updatecli.d/docker-images/jenkins-weekly_infra.ci.jenkins.io.yaml
- updatecli/updatecli.d/docker-images/jenkins-weekly_weekly.ci.jenkins.io.yaml
This PR allows to update only infra.ci.jenkins.io or weekly.ci.jenkins.io if only one of them has a new version.
Tested with https://github.com/jenkins-infra/docker-jenkins-weekly/releases/tag/1.26.2-2.441 containing only the weekly.ci.jenkins.io image variant, validating no update for infra.ci.jenkins.io:
<details>
```
$ updatecli diff --config updatecli/updatecli.d/docker-images/jenkins-weekly_weekly.ci.jenkins.io.yaml --values updatecli/values.yaml
+++++++++++
+ PREPARE +
+++++++++++
Loading Pipeline "updatecli/updatecli.d/docker-images/jenkins-weekly_weekly.ci.jenkins.io.yaml"
SCM repository retrieved: 1
++++++++++++++++++
+ AUTO DISCOVERY +
++++++++++++++++++
++++++++++++
+ PIPELINE +
++++++++++++
#################################################################### …
```
> chore(updatecli/docker-jenkins-weekly): adapt manifests to individually update instances

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
This PR creates an Azure Service Principal credentials in contributors.jenkins.io job on infra.ci.jenkins.io so it can be used in pipeline to log in with `az`.
Note: using Service Principal Application as source.
Follow-up of:
- https://github.com/jenkins-infra/azure/pull/599
- https://github.com/jenkins-infra/charts-secrets/commit/972d04793108f2232c3adc720881a26bbba79d34 (private repo)
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3414
> chore(infra.ci.jenkins.io): create azure service principal credentials for contributors.jenkins.io

- config/jenkins_infra.ci.jenkins.io.yaml
manual upgrade as updatecli doesn't catch the update anymore
> Bump Jenkins Weekly docker image version on infra.ci.jenkins.io to 1.27.5-2.442

- updatecli/updatecli.d/docker-images/jenkins-lts.yaml
- updatecli/updatecli.d/docker-images/jenkins-weekly_infra.ci.jenkins.io.yaml
- updatecli/updatecli.d/docker-images/jenkins-weekly_weekly.ci.jenkins.io.yaml
Fixup of #4925 
Closes #4934 closes #4933 
(new PRs will be opened)
> chore(updatecli) fix all jenkins manifests related to 5.x chart's image specification

- config/jenkins_infra.ci.jenkins.io.yaml
Reverts jenkins-infra/kubernetes-management#4946
infra.ci can't spawn agent pods, failing with:
> stream logs failed container "jnlp" in pod "jnlp-linux-arm64-b9rj5" is waiting to start: ContainerCreating for jenkins-infra-agents/jnlp-linux-arm64-b9rj5 (jnlp)
> exec /usr/local/bin/jenkins-agent: exec format error
> Stream closed EOF for jenkins-infra-agents/jnlp-linux-arm64-b9rj5 (jnlp)
> Revert "Bump agent templates for infra.ci.jenkins.io (packer-image 1.51.0)"

- updatecli/updatecli.d/charts/kubernetes-pods-quotas.yaml
This PR fixes the kubernetes-pods-quotas updatecli manifest, broken since https://github.com/jenkins-infra/jenkins-infra/pull/3272
Ref:
- https://github.com/jenkins-infra/jenkins-infra/pull/3272
- https://github.com/jenkins-infra/helpdesk/issues/3913
> fix(updatecli/pod-quotas): new hieradata location

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
This PR sets the infra.ci.jenkins.io account app job to use the same Jenkinsfile as ci.jenkins.io.
Related:
- https://github.com/jenkins-infra/account-app/pull/354
Ref:
- https://github.com/jenkins-infra/account-app/pull/351#discussion_r1485875113
> chore(infra-jobs/account-app): use one Jenkinsfile for both ci.jenkins.io and infra.ci.jenkins.io

- config/jenkins_infra.ci.jenkins.io.yaml
This PR sets `JAVA_HOME` by default to `/opt/jdk17` in infra.ci.jenkins.io kubernetes agents pod templates.
Ref:
- https://github.com/jenkins-infra/account-app/pull/354#discussion_r1490539848
> chore(infra.ci): set `JAVA_HOME` by default to `/opt/jdk17` on agents

- clusters/doks-public.yaml
- clusters/eks-public.yaml
- clusters/privatek8s.yaml
- clusters/publick8s.yaml
- config/cert-manager.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3948#issuecomment-1948206377
need to change the timeout to a value between 1 and 29 for kubernetes upgrade.
```
cert-manager, cert-manager-webhook, MutatingWebhookConfiguration (admissionregistration.k8s.io) has changed:
...
matchPolicy: Equivalent
-     timeoutSeconds: 30
+     timeoutSeconds: 25
failurePolicy: Fail
...
cert-manager, cert-manager-webhook, ValidatingWebhookConfiguration (admissionregistration.k8s.io) has changed:
...
matchPolicy: Equivalent
-     timeoutSeconds: 30
+     timeoutSeconds: 25
failurePolicy: Fail
sideEffects: None
...
```
> feat(all): config cert-manager webhooks timout for validating and mutating

- clusters/publick8s.yaml
- config/jenkinsio.yaml
This PR uses the last version 1.2.0 of jenkinsio chart to allow specifying a different storage account for jenkinsio & jenkinsio-zh so we can migrate jenkins.io to its new `jenkinsio` storage account.
I've put the original `prodjenkinsio` storage account credentials as a `zh` one in https://github.com/jenkins-infra/charts-secrets/blob/main/config/jenkinsio/secrets2.yaml (private repo) alongside the new `jenkinsio` storage account (which does not contain the `zhjenkinsio` File Share, only the new `jenkins-io` one) to avoid service disruption.
I'll update https://github.com/jenkins-infra/charts-secrets/blob/main/config/jenkinsio/secrets.yaml to contain both storage account credentials and change the release config in a follow-up pull request.
Tested on another release locally with success. …
> chore(jenkins.io): migrate to its new `jenkinsio` storage account

- clusters/publick8s.yaml
This PR is the follow-up to reuse secrets.yaml now updated with the content of secrets2.yaml. (Two steps migration to avoid service disruption)
Follow-up of:
- #5023 
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3414
> chore(jenkins.io): use secrets.yaml instead of secrets2.yaml

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
This PR adds an Azure Service Principal credentials to interact with `plugins-jenkins-io` File Share.
Follow-up of:
- https://github.com/jenkins-infra/azure/pull/630
- https://github.com/jenkins-infra/charts-secrets/commit/7ef0d46bddd554f39691e11c24884d3adffa7849 (private repo)
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3414#issuecomment-1964568638
> chore(plugins.jenkins.io): add AzureServiceprincipal credential for `plugins-jenkins-io` File Share

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
This PR removes the GitHub check names, now useless since the use of https://github.com/jenkinsci/github-scm-trait-notification-context-plugin:
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/2778#issuecomment-1959565465
> chore(infra-jobs): remove `githubCheckName`s

- clusters/publick8s.yaml
This PR get rid of the intermediate secret used to avoid service interruption while migrating to the new storage account.
Follow-up of:
- #5027 
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3414#issuecomment-1964568638
> chore(plugins.jenkins.io): use secrets.yaml instead of intermediate-secrets.yaml

- clusters/publick8s.yaml
- config/javadoc.yaml
This PR  migrates javadoc.jenkins.io to its new `javadocjenkinsio` storage account, using an intermediate secret to avoid any service interruption.
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3414#issuecomment-1966067802
> chore(javadoc.jenkins.io): use new `javadocjenkinsio` storage account

- config/jenkins_infra.ci.jenkins.io.yaml
This PR adds two large linux agents on infra.ci.jenkins.io with similar resources than `jdk17` agents on ci.jenkins.io.
Ref:
- https://github.com/jenkins-infra/account-app/pull/354#issuecomment-1973243093
> chore(infra.ci): add large jnlp linux agents

- Jenkinsfile_k8s
Reverts jenkins-infra/kubernetes-management#5053
to re-enable privatek8s and check the helmfile diff
> Revert "chore: remove privatek8s cluster from the pipeline"

- updatecli/updatecli.d/charts/jenkins-agents-infra.ci.jenkins.io.yaml
This PR improves the condition to detect a new packer-image all in on version:
If the release of jenkins-infra/packer-images fails, then the last stage is never run.
This last stage is expected to build and deploy a multi-architecture manifest to the DockerHub for the new image version being released (see https://github.com/jenkins-infra/packer-images/blob/7f910ad4457d6f62d45af4762235ea5457581997/Jenkinsfile_k8s#L211-L238)
Until this stage is reached, all architectures on the DockerHub answers with the same image SHA: this is the goal of the added condition.
Copy and pasted (mostly) from https://github.com/jenkins-infra/jenkins-infra/blob/c6efe085075ff612e6340946716d3ca9ef037699/updatecli/weekly.d/jenkinscontroller-agents-packer-agent-all-in-one.yaml#L46-L51 where it has worked as …
> chore(updatecli) improve condition for packer-image detection to avoid opening PR until the image release is complete.

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/2778
Since https://github.com/jenkins-infra/helm-charts/pull/1081 (deployed in https://github.com/jenkins-infra/kubernetes-management/pull/5015), we have customized SCM notifications from controllers to GitHub to allow splitting jobs on the same repository without messing up checks.
Following up the changes in https://github.com/jenkins-infra/kubernetes-management/pull/5025/files, this PR also fully disable GH Notification Checks to remove the `jenkins` check which we do not need anymore for the `updatecli` jobs:
> feat(privatek8s/infra.ci) remove GitHub checks for updatecli jobs in favor of customized scm notifications

- config/plugin-site-issues.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/3978#issuecomment-2008687538
This PR specifies the use of an ECDSA certificate instead of RSA for the https://plugin-site-issues.jenkins.io/ website.
Certificates are auto-generated by cert-manager with Let's Encrypt.
Note we can only specify ECDSA per `Certificate` custom resource through ingress annotation as per https://cert-manager.io/docs/usage/ingress/. 
As we cannot specify to use `ECDSA` by default at the `ClusterIssuer`  level (ref. https://github.com/cert-manager/cert-manager/issues/2764) we might have to do this change to all ingresses.
So this PR is a first test to validate it is worth the effort.
Once merged, we'll force-renew the certificate to validate it works and the user in …
> feat(publick8s/plugin-site-issues) specify an ECDSA LetsEncrypt certificate instead of RSA

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3961
This PR creates a new job on infra.ci, inside the top-level "Infra Report" folder, to handle the Plugin Health Score report generation.
Note: the job can be created first: it won't find any `Jenkinsfile` for now when scanning until a PR on infra-report is opened :)
> feat(privatek8s/infra.ci) add PHS Report job in infra-reports

- config/plugin-site-issues.yaml
Hotfix of https://github.com/jenkins-infra/kubernetes-management/pull/5080.
Already applied on production (hotfix) with success.
Related to https://github.com/jenkins-infra/helpdesk/issues/3978
Ref. https://cert-manager.io/docs/usage/ingress/#supported-annotations
This change fixes the message `Existing private key is not up to date for spec <...>` in the `kubectl describe certificate` output which prevented the certificate renewal due to an algorithm change (RSA -> ECDSA in this case)
> hotfix(publick8s/plugin-site-issue) force TLS certificate private key renewal when changing alogrithm - uses ingress annotation for cert-manager

- config/plugin-site-issues.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3978
As there are no strong compelling reason to use ECDSA over RSA and we can't default to ECDSA by default, this PR rolls back the changes introduced in https://github.com/jenkins-infra/kubernetes-management/pull/5080 and https://github.com/jenkins-infra/kubernetes-management/pull/5110 as we want to keep with the same default settings for all of our certificates: enforcing the ECDSA-related annotation across all ingresses is time-consuming.
Please note that a one-time manual change will be required to re-issue an RSA certificate by adding the following annotation to the `plugin-site-issue` ingress right before force-renewing (with `cmctl`):
```
cert-manager.io/private-key-rotation-policy: Always
```
> cleanup(publick8s/plugin-site-issues) rollback custom annotations back to default key algorithm (RSA)

- config/jenkins_infra.ci.jenkins.io.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3823#issuecomment-2036372624
move the persistence volume to a ZRS storage to be able to move the instance from zone 3 to zone 1, which is compliant with ARM64
> chore(infraci): move persistence volume to ZRS in prevision for ARM64 migration

- config/jenkins_infra.ci.jenkins.io.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3823#issuecomment-2036372624
this will migrate infra.ci to it's specific pool which is arm64 as per https://github.com/jenkins-infra/azure/pull/658 
----
Deployment procedure
as this is an heavy change on infra.ci infrastructure it is safer to apply it manually (instead of relying on agent re-connection if everything goes according to the plan) 
- from a local administrator machine with access to privatek8s API (and same kubectl / helmfile version as packer image allinone agent)
- ensure that the local kubernetes-management repository is up to date with this PR (including `./secrets` sub repository)
- execute helmfile diff to ensure that the change is correctly plan
- deploy with helmfile apply
- merge this PR as soon as the pod is …
> chore(infra.ci): migrate to arm64

- config/datadog_privatek8s.yaml
Follow up of #5126
Related to https://github.com/jenkins-infra/helpdesk/issues/3823
This PR fixes the datadog configuration in the `privatek8s` cluster to ensure we have an agent per node.
Today we only have datadog agents on the syspool and linuxpool node pools.
The arm64 node pools have taints forbidding the datadog agent to be scheduled.
By adding tolerations to the datadog deployment, we allow them to be scheduled on any kind of nodes.
----
Notes:
- The Windows node pool (used only during Jenkins core releases by release.ci.jenkins.io is out of scope)
- The tolerations added in this PR covers ALL the other node pools: all controllers, all agents, etc.
- Tested manually with success on production and then roll backed.
- Thanks @MarionPlt for the rubber ducking on this one!
> fix(privatek8s/datadog) ensure datadog agent runs on all nodes by updating tolerations

- config/datadog_privatek8s.yaml
- config/datadog_publick8s.yaml
Follow up of #5132
Related to https://github.com/jenkins-infra/helpdesk/issues/3823
This PR ensures that datadog installation works as expected in our AKS clusters by following datadog recommendations:
- First change allows datadog agent to run on Azure Linux (ref. https://github.com/jenkins-infra/azure/pull/662). It applies the datadog troubleshooting trick (https://docs.datadoghq.com/agent/troubleshooting/hostname_containers/?tab=helm#accessing-the-container-runtime-api) to use the container runtime API when resolving the hostname.
- Fixes the error message `Error: Error while getting hostname, exiting: unable to reliably determine the host name. You can define one in the agent config file or in your hosts file` in the datadog-agent pod logs (when it is in `CrashLoopBackOff`)
- Second …
> fix(publick8s,privatek8s) ensure datadog setup works on AKS (Azure Linux, Admission Controller)

- config/jenkins_release.ci.jenkins.io.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3823#issuecomment-2056385986
adding a podSecurityContextOverride to avoid long volume mount attach times https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/README.md#long-volume-attachmount-times
> feat(privatek8s/release.ci) add podSecurityContextOverride to avoid long volume attach/mount times

- config/jenkins_release.ci.jenkins.io.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/4042
migrate release.ci to arm64 dedicated nodepool.
> chore(release.ci): migrate to arm64

- config/jenkins_release.ci.jenkins.io.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/4042
following #5140 and #5141 using last docker image version compatible with arm64 as per https://github.com/jenkins-infra/docker-jenkins-lts/pull/857
> chore(release.ci): migrate to arm64 with correct docker image version

- config/updates.jenkins.io.yaml
This PR update the new Update Center deployment (Azure + mirrorbits) to have the described setup (azure.updates.jenkins.io => httpd and mirrors.updates.jenkins.io => mirrorbits).
As we don't need to filter path with nginx-ingress & regexp anymore, removing the correspond snippet annotation.
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2075477428
> feat(updates.jenkins.io): set azure.updates.jenkins.io backend to `httpd` and mirrors.updates.jenkins.io to `mirrorbits`

- config/updates.jenkins.io.yaml
As the httpd service doesn't need to have a common File Share with the mirrorbits service, this PR disables it from the mirrorbits-parent release.
Cherry-picking https://github.com/jenkins-infra/kubernetes-management/pull/5184/commits/c84ef20723470f7c15ff3a51773b5ae740aa1f9e from:
- https://github.com/jenkins-infra/kubernetes-management/pull/5184
We need to do it in two steps to avoid the concurrency error described in https://github.com/jenkins-infra/kubernetes-management/pull/5184#issuecomment-2085520946
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2076659536
> chore(updates.jenkins.io): disable `httpd` service in mirrorbits-parent release

- clusters/publick8s.yaml
- config/updates.jenkins.io.yaml
- config/updates.jenkins.io_httpd.yaml
As the httpd service doesn't need to have a common File Share with the mirrorbits service, this PR ~disables it from the mirrorbits-parent release~ (extracted in #5186), and adds a dedicated httpd release from its own chart so it can use its own updates-jenkins-io-httpd File Share created in https://github.com/jenkins-infra/azure/pull/676.
We're keeping the mirrorbits and the rsync services under mirrorbits-parent umbrella as they still need to share the same updates-jenkins-io File Share.
Corresponding secret added in https://github.com/jenkins-infra/charts-secrets/commit/688566ee492e9026f09289d79ece7f8f4f06cdf3 (private repo).
Follow-up of:
- https://github.com/jenkins-infra/kubernetes-management/pull/5175
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-20766595 …
> feat(updates.jenkins.io): dedicated File Share for the `httpd` service

- clusters/publick8s.yaml
- config/updates.jenkins.io_httpd.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2089993133.
The goal of this PR is to instantiate an `httpd` service for the `azure.updates.jenkins.io` webservice with its own distinct fileshare.
It is a second tentative of delivering #5184 with an additional fixup commit to ensure PV + PVC are created without error and it reverts #5190.
The `httpd` chart does not require (at least for now) a change: we can set up a statically provisioned PVC.
Validations:
- The official AKS documentation was used to set up the attributes: https://learn.microsoft.com/en-us/azure/aks/azure-csi-files-storage-provision#statically-provision-a-volume
- The resulting YAML had been statically verified: 
- The command `helmfile template -f ./clusters/publick8s.yaml -l …
> feat(publick8s/updates.jenkins.io): deploys a dedicated `httpd` service with a distinct fileshare

- config/updates.jenkins.io.yaml
- config/updates.jenkins.io_httpd.yaml
Fixup of #5192 and #5186
Related to https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2090743133
This PR specifies distinct secret names for cert-manager to store TLS certificates.
It should fix the TLS errors when reaching the services
> hotfix(publick8s/updates.jenkins.io) ensure each distinct ingress uses a distinct secret to store their certificates

- clusters/publick8s.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2090967319
> hotfix(publick8s) stop managing updates-jenkins-io releases until storage is migrated to premium

- clusters/publick8s.yaml
- config/docs.jenkins.io.yaml
This PR adds docs.jenkins.io nginx website release to publick8s cluster.
Secrets added in https://github.com/jenkins-infra/charts-secrets/commit/b2ff9092b64d6b1a7d685f7d724b144a55e31ee5 (private repo).
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3885#issuecomment-2090052823
> feat: add docs.jenkins.io to publick8s cluster

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
This PR creates an Azure Service Principal credentials in docs.jenkins.io job on infra.ci.jenkins.io so it can be used in pipeline to log in with `az`.
Note: using Service Principal Application ID as source.
Secrets added in https://github.com/jenkins-infra/charts-secrets/commit/b274498850438b91617150b608c9fa624a7527d6 (private repo).
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3885#issuecomment-2090052823
> chore(infra.ci.jenkins.io): create azure service principal credentials for docs.jenkins.io

- config/jenkins_infra.ci.jenkins.io.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/4080#issuecomment-2095863202
removing datadog plugin configuration before removing the plugin with https://github.com/jenkins-infra/docker-jenkins-weekly/pull/1606
no configuration found for datadog on weekly.ci
> feat(infra.ci): remove datadog plugin configuration

- config/jenkins_infra.ci.jenkins.io.yaml
- config/jenkins_release.ci.jenkins.io.yaml
- config/jenkins_weekly.ci.jenkins.io.yaml
This PR switches the default notification URL of infra.ci.jenkins.io and weekly.ci.jenkins.io from "default" to "Jenkins Classic" so `display/redirect` links redirect to the main build page instead of the less useful pipeline graph view page.
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/2833#issuecomment-2100635026
> chore(infra/weekly.ci.jenkins.io): switch default notification URL to Jenkins Classic

- Jenkinsfile_k8s
- clusters/cijioagents1.yaml
- config/datadog_cijioagents1.yaml
- config/jenkins-kubernetes-agents_ci.jenkins.io_cijioagents1-bom.yaml
- config/jenkins-kubernetes-agents_ci.jenkins.io_cijioagents1.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3954#issuecomment-2107226189
This PR introduces a new cluster management for the AKS cluster `ci.jenkins.io-agents-1`).
Tested locally: worked once https://github.com/jenkins-infra/azure/pull/698 is applied.
Note: ACP is not yet uncommented as we want to implement tolerations in its chart to allow running in the node pool for arm64
> feat: add a new ci.jio.agents-1 cluster in AKS

- clusters/cijioagents1.yaml
- config/artifact-caching-proxy_azure-aks.yaml
- updatecli/updatecli.d/charts/artifact-caching-proxy.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3954
This PR adds an initial installation of ACP into the new AKS `ci.jenkins.io-agents-1` cluster with the following attributes:
- No ingress (and as such: no need for a secret used to protect external access) as usage is only internal
- We might need an eventual network access from Azure VM in the near future: to be studied given we use CNI overlay
- ARM64 deployment
- Storage does NOT specify "retain" as we don't care to retain disk if the PV is deleted
Notes:
- Tested once and worked well in production. Cleaned up so this PR will be an auditable initial installation
- The expected internal URL for this service for agents is: `http://artifact-caching-proxy.artifact-caching-proxy:8080`
- Updatecli manifest amended: the check …
> feat(ci.jenkins.io-agents-1) initial installation of ACP

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
Experiment related to https://github.com/jenkins-infra/helpdesk/issues/4114
Follow up of https://github.com/jenkins-infra/azure-net/pull/245 which fails on the `main` branch with the error `ERROR: Could not find credentials entry with ID 'azure-reports-access-key'` due to missing credential.
This PR  adds the expected credential but scoped to only the Terraform jobs. 
Note it replaces an unused infracost credential.
> feat(privatek8s/infra.ci.jio) allow terraform jobs to publish on reports.jenkins.io

- config/cert-manager.yaml
As per https://github.com/cert-manager/cert-manager/releases/tag/v1.15.0, the value `installCRDs:` is still used but deprecated.
This PR updates our cert-manager configurations to use the new [`crds.enable` and `crds.keep`](https://github.com/cert-manager/cert-manager/pull/6760] values.
> chore(publick8s/privatek8s) update deprecated CRD configuration for cert-manager 1.15.x

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
as per 
- https://github.com/jenkins-infra/helpdesk/issues/3923
adding the secret credential in the kubernetes-management (secrets already added in charts-secrets for infra.ci -- commit [2fcc66d]) 
must precede https://github.com/jenkins-infra/kubernetes-management/pull/5309
> feat(infracijioagents1): add credential to kubernetes-management

- clusters/publick8s.yaml
- config/stats.jenkins.io.yaml
This PR adds the stats.jenkins.io service, served on new.stats.jenkins.io until the GSoC project completion, will be migrated to stats.jenkins.io after that.
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/4132#issuecomment-2167717401
> feat(publick8s): add `stats.jenkins.io` service

- config/jenkins_infra.ci.jenkins.io.yaml
as per 
- https://github.com/jenkins-infra/helpdesk/issues/3923
add a new cloud kubernetes in the infra.ci pointing to the new cluster `infracijioagents1`
using a specific label for now, not to interfere with the existing ones, to let the time to upgrade kubernetes to 1.28 see https://github.com/jenkins-infra/helpdesk/issues/4144#event-13202159425
> feat(infra.ci): add the new cluster as kubernetes cloud

- Jenkinsfile_k8s
- config/jenkins_infra.ci.jenkins.io.yaml
since few weeks we sometime see timeout errors when the pipeline send request to AKS control planes. it appear that the VM agents of infra.ci are not allowed to reach these control planes. This PR is a short term fix to ensure that we are using pod agents on privatek8s only, which are allowed to reach control planes.
note: this PR cleans up labels on both sides: pipeline (requester) and VM agents templates (provider)
> fix(pipeline, privatek8s/infra.ci): fix io timeout due to unauthorized network when accessing controlplanes

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
This PR creates an Azure Service Principal credentials in stats.jenkins.io job on infra.ci.jenkins.io so it can be used in pipeline to log in with `az`.
Note: using Service Principal Application ID as source.
Secrets added in https://github.com/jenkins-infra/charts-secrets/commit/67d0e595754f5d0acb991c70c20b4371f182b345 (private repo).
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/4132#issuecomment-2167717401
> feat(privatek8s/infra.ci.jenkins.io): create azure service principal credentials for stats.jenkins.io

- Jenkinsfile_k8s
as per https://github.com/jenkins-infra/helpdesk/issues/4144#issuecomment-2178169723
we remove the cluster `infracijioagents1`from the kubenetes-management to handle is upgrade to kubernetes 1.28
> feat(infracijioagents1): removing temporarily from management to upgrade to kubernetes 1.28

- Jenkinsfile_k8s
Reverts jenkins-infra/kubernetes-management#5337
putting back the cluster `infracijioagents1` within kubernetes-management now that it's upgraded to kubernetes 1.28
> Revert "feat(infracijioagents1): removing temporarily from management to upgrade to kubernetes 1.28"

- config/jenkins_infra.ci.jenkins.io.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/3923
This PR migrates the container agents workloads of infra.ci.jenkins.io to the new `infracijio-agent-1` cluster
Note: 
- The agent pod template `jnlp-windows` is removed as we do not have Windows Node pool on the new cluster (and it is not used: we use Windows Azure VM if needed)
- The agent pod template `jnlp-linux` is renamed to `jnlp-linux-amd64`. It keeps the same labels as before + addition label `jnlp-linux-amd64`
- The env. var `ARTIFACT_CACHING_PROXY_PROVIDER` is added to `jnlp-linux-amd64` and `jnlp-linux-arm64`
> feat(privatek8s/infra.ci.jenkins.io) migrate container agents workload to infracijioagents1

- clusters/privatek8s.yaml
- config/datadog_infracijioagents1.yaml
- config/jenkins-infra-agents-privatek8s.yaml
- config/jenkins_infra.ci.jenkins.io.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3923
This PR removes the following elements:
- (now) unused namespace for infra.ci agents (as they moved to another cluster)
- A unused top-level credential for infra.ci
- lint warnings
Note: once applied, this PR will require the namespace to be deleted with: `kubectl delete ns jenkins-infra-agents`
> cleanup(privatek8s) remove unused infra.ci agent setup

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
This PR adds a stats.jenkins.io job dedicated to previews so it can be triggered by any contributor even if they don't have write permission on stats.jenkins.io repository.
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/4132#issuecomment-2185272935
> feat: add dedicated `stats.jenkins.io` PR previews job

- Jenkinsfile_k8s
Reverts jenkins-infra/kubernetes-management#5348 as per https://github.com/jenkins-infra/helpdesk/issues/4144#issuecomment-2182701643
cijioagents1 cluster is added back to kubernetes management as it has been upgraded to kub 1.28.
> Revert "feat(cijioagents1): removing temporarily from management to upgrade to Kubernetes 1.28"

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
This PR removes a credentials replaced by https://github.com/jenkins-infra/kubernetes-management/pull/4894.
A follow-up pull request will be opened to cleanup this from charts-secrets repo too.
> cleanup(privatek8s/infra.ci.jenkins.io): remove unused contributors SAS querystring credentials

- Jenkinsfile_k8s
As per https://github.com/jenkins-infra/helpdesk/issues/4144#issuecomment-2190936375
Removing privatek8s cluster from kub management to proceed with kub 1.28 upgrade.
> feat(privatek8s): Removing temporarily from management to upgrade to kub 1.28

- Jenkinsfile_k8s
As per https://github.com/jenkins-infra/helpdesk/issues/4144#issuecomment-2190936375
Reverts jenkins-infra/kubernetes-management#5353 as cluster is upgraded to kub 1.28
> Revert "feat(privatek8s): Removing temporarily from management to upgrade to kub 1.28"

- config/jenkins_infra.ci.jenkins.io.yaml
Ref. https://www.jenkins.io/security/advisory/2024-06-26/
Manual apply as there are not automation
> feat(privatek8s/infra.ci.jenkins.io) bump image version to `1.48.1-2.464`

- config/jenkins_weekly.ci.jenkins.io.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/4044
this will follow the data migration done by temporary pod
the existingClaim is getting precedence with home-pvc.yaml creation 
see: 
- https://github.com/jenkinsci/helm-charts/blob/fac862d10e311fda6c9df2b695754f482f7e4641/charts/jenkins/templates/jenkins-controller-statefulset.yaml#L395
and
- https://github.com/jenkinsci/helm-charts/blob/fac862d10e311fda6c9df2b695754f482f7e4641/charts/jenkins/templates/home-pvc.yaml#L2
local diff looks good
```
jenkins-weekly, jenkins-weekly, Secret (v1) has changed:
+ Changes suppressed on sensitive content of type Secret
jenkins-weekly, jenkins-weekly, StatefulSet (apps) has changed:
...
- name: jenkins-home
persistentVolumeClaim:
-           claimName: jenkins-weekly
+           claimName: …
```
> feat(jenkins-weekly) migrate from premium to standard ZRS volume already provisionned by terraform azure

- config/jenkins_release.ci.jenkins.io.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/4044
migrating to terraform managed disk/pv/pvc in standard ZRS
⚠️ do not merge, need a last moment sync for the migration
> feat(release.ci): migrate volume/pv/pvc to standard ZRS

- Jenkinsfile_k8s
As per https://github.com/jenkins-infra/helpdesk/issues/4144#issuecomment-2196274746
Removing publick8s cluster from kub management to proceed with kub 1.28 upgrade.
> feat(publick8s): Removing temporarily from management to upgrade to kub 1.28

- Jenkinsfile_k8s
As per https://github.com/jenkins-infra/helpdesk/issues/4144#issuecomment-2196274746:
Reverts jenkins-infra/kubernetes-management#5385, as cluster is upgraded to kub 1.28
> Revert "feat(publick8s): Removing temporarily from management to upgrade to kub 1.28"

- config/accountapp.yaml
- config/contributors.jenkins.io.yaml
- config/docs.jenkins.io.yaml
- config/get-jenkins-io.yaml
- config/javadoc.yaml
- config/jenkinsio.yaml
- config/reports.yaml
- config/stats.jenkins.io.yaml
- config/updates.jenkins.io_httpd.yaml
While working on https://github.com/jenkins-infra/helpdesk/issues/3837, we saw in datadog that the "real life" usage of most of the arm64 services is way below the resource requests.
This PR optimizes this to ensure we can pack more per nodes on arm64
> feat(publick8s) decrease resource requests to pack more pods

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
- https://github.com/jenkins-infra/helpdesk/issues/3837 requires the `docker-keycloak-theme` image to be built with `arm64`
- `docker-plugins-self-service` generates builds on infra.ci but is never used.
> feat(privatek8s/infra.ci) add docker-keycloak-theme job and remove (unused) docker-plugins-self-service

- clusters/publick8s.yaml
- config/keycloak.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3837
This PR migrates Keycloak to `arm64` nodes.
- Both container images are availabe in `arm64`:
- https://quay.io/repository/keycloak/keycloak?tab=tags&tag=17.0.1-legacy
- https://hub.docker.com/layers/jenkinsciinfra/keycloak-theme/0.1.1/images/sha256-eb982ad10e437c95e837d0035afb3c0e9212c39564fb54e2ba68d0131dd4fda5?context=explore
> feat(publick8s/keycloak) migrate to arm64

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
This PR adds all jenkins-infra repositories containing an updatecli folder to `updatecli` jobs on infra.ci.jenkins.io.
Supersedes:
- #5413
- #5415
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/2778
> chore: add all jenkins-infra repositories containing an updatecli folder to `updatecli` jobs on infra.ci.jenkins.io

- config/jenkins_infra.ci.jenkins.io.yaml
- config/jenkins_weekly.ci.jenkins.io.yaml
- updatecli/updatecli.d/docker-images/jenkins-weekly_infra.ci.jenkins.io.yaml
- updatecli/updatecli.d/docker-images/jenkins-weekly_weekly.ci.jenkins.io.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/4171, this PR updates manually to the "new" images.
No core of plugins changes expected (incoming subseuquent PRs for this)
> fix(privatek8s) use the correct 'splitted' images for infra.ci and weekly.ci

- config/public-nginx-ingress__common.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4177
It appears that we do not have gzip enabled on the ingress. This PR enables it for the following reasons:
- Even if we serve large files, clients will receive (if they can handle gzip) smaller files
- Less data to send back (less outbound bandwidth to pay for)
- Faster pages to load (https://github.com/jenkins-infra/helpdesk/issues/4177)
- Only downside: a bit more CPU usage for the nodes hosting the nginx ingress controllers. But we are fine on that matter:
> feat(all) enable gzip with default mime types for all public ingresses

- config/public-nginx-ingress__common.yaml
Ref. https://github.com/jenkins-infra/kubernetes-management/pull/5442#pullrequestreview-2187587850
Follow up of #5442 but with `brotli` compression in addition of `gzip`
> feat(all) enable brotli with default mime types for all public ingresses

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
- config/public-nginx-ingress__common.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4167
This PR sets the required credential on infra.ci.jenkins.io to:
- Use the new TF backend credentials
- Have a staging environment available for datadog
Associated secret change: https://github.com/jenkins-infra/charts-secrets/commit/e7cf3e23d47119706bb945a0bfe5ca4454ed55e6
> feat(privatek8s/infra.ci) set up Terraform datadog job to use new backends

- config/jenkins_infra.ci.jenkins.io.yaml
- config/jenkins_release.ci.jenkins.io.yaml
- config/jenkins_weekly.ci.jenkins.io.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/4186
set up the Git Jenkins tool to have the native git CLI as first (and default) and add JGit as secondary (fallback)
> feat(publick8s/weekly.ci, privatek8s/infra.ci, privatek8s/release.ci): adding native-git and jgit tools

- clusters/publick8s.yaml
- config/public-nginx-ingress__common.yaml
- config/updates.jenkins.io_httpd.yaml
- updatecli/updatecli.d/charts/httpd.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2255522243
This PR ensures that the HTTP redirects from the HTTPD component of `updates-jenkins-io` keeps the HTTPS scheme in their redirection target.
- If there are any HTTP external request made to the service, the ingress upgrades it to HTTP so no impact:
```
$ curl --silent --show-error --output /dev/null --fail --write-out '%{redirect_url}' 'http://azure.updates.jenkins.io/update-center.json?id=default&version=2.469' 
https://azure.updates.jenkins.io/update-center.json?id=default&version=2.469%
```
- We do not expect the internal HTTPD to be requested by something else than the ingress
----
NOTE: 2 minor changes are part in this PR. I chose to add them as per the following:
- A new `updatecli` manifest …
> fix(publick8s/updates.jenkins.io) set HTTPD ServerName to `https://localhost` to ensure HTTP redirects keeps the HTTPS scheme

- config/jenkins_infra.ci.jenkins.io.yaml
While working on https://github.com/jenkins-infra/helpdesk/issues/4165, it appeared we had some infra.ci.jenkins.io Helm chart settings to cleanup:
- Decreasing probes initial delay for faster restarts (cc @smerle33 for info : you will like it)
- Disable GitHub API throttling
- Use defaults for sidecar
- Document some values for the reader
> chore(privatek8s/infra.ci) jenkins settings cleanup

- config/updates.jenkins.io_httpd.yaml
This PR sets up the HTTPD service to answer on requests with the Host set to `updates.jenkins.io` to:
- Allow testing while overriding the `updates.jenkins.io` DNS records to point to the cluster IP (`20.7.178.24`)
- Ensure that we have a valid TLS termination for this domain (anticipating the brwonouts)
> feat(publick8s/updates.jio) set up HTTPD to answer requests using the `updates.jenkins.io` hostname

- config/datadog_infracijioagents1.yaml
Otherwise the datadog agents are not spawned on the infra.ci agent nodes (and we are missing metrics)
> fix(infra.ci-agents-1) correct datadog agent tolerations

- config/ldap.yaml
Follow up of https://github.com/jenkins-infra/azure-net/pull/277
2 new outbounds IP for ci.jenkins.io network need to be added in the LDAP service
> hotfix(publick8s/ldap) allow new ci.jio outbound IPs

- config/jenkins_infra.ci.jenkins.io.yaml
Ref. https://github.com/jenkins-infra/azure/pull/794
This PR:
- Enables using the DockerHub ACR mirror (same as https://github.com/jenkins-infra/jenkins-infra/pull/3575)
- Fixes the Windows Azure VM agents which weren't restarting datadog agent after setting it up
> feat(infra.ci) use DockerHub ACR mirror for Azure VM agents

- clusters/publick8s.yaml
- config/public-nginx-ingress__common.yaml
- config/public-nginx-ingress_publick8s.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/4206
This PR fixes the 2 errors related to `Authorization Failures` with IPv6 Public IP deprecated and being reused (trying to) by the LB.
The root causes are the same: using DualStack LBs instead of 2 SingleStack LBs.
- Fixing the Nginx ingress LB  using helm chart values specifying the SingleStack `IPv4`
- Fixing the custom IPv6 LB using its new `1.0.1` (fixed) chart from https://github.com/jenkins-infra/helm-charts/pull/1251
> fix(publick8s/public-ingress) ensure external LBs are SingleStack to prevent errors trying to create unused IPv6s

- config/artifact-caching-proxy_azure-aks.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/4204#issuecomment-2278334260
This PR changes the ACP (of the `ci.jio-agents1` cluster) service from `ClusterIP` to an (Azure internal) `LoadBalancer` with a static IP in the ci.jenkins.io ephemeral agents network.
> feat(ci.jio-agents1/acp) use an Azure-internal LB to expose the service to another subnet

- config/artifact-caching-proxy_azure-aks.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/4204
While re-reading the [Nginx doc about `resolver`](http://nginx.org/en/docs/http/ngx_http_core_module.html#resolver) I realized that:
- When the error `(110: Operation timed out) while connecting to upstream` happens it is mostly due to numerous DNS requests blocked. Since we try to resolve hostname every 60s, DNS caching could help (@timja mentioned https://github.com/Azure/AKS/issues/3673 for instance).
- But we are only using directly the [quad-9 DNS](https://www.quad9.net/) DNS server and not the local Kube DNS, bypassing the whole DNS chain
This PR specifies the local Kube DNS and then chain with the quad 9 DNS server as fallback:
- More efficient DNS resolution with local caching out of the box
- More resilient: if the …
> fix(ci.jio-agents1/acp) use a resolver chain and start with local kube-dns

- config/jenkins_infra.ci.jenkins.io.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2283576911
This PR sets up infra.ci.jenkins.io to have a custom UC using the new UC's intermediate URL. It will test Jenkins can retrieve metadata from it, but won't test the "redirects" used to download plugins
> chore(privatek8s/infra.ci.jio) temporarily uses the new UC

- config/updates.jenkins.io.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2283801444
This PR fixes the "too much redirection" when hitting the app root (https://azure.updates.jenkins.io -> https://mirrors.updates.jenkins.io -> https://azure.updates.jenkins.io etc.).
It set up the ingress to immediately redirects any exact request on `/` to the `/index.html` file explicitly so the file is served by a mirror (instead of the Azure cluster).
> fix(publick8s/mirrors.updates.jio) redirect the app-root to `/index.html`

- config/jenkins_infra.ci.jenkins.io.yaml
As per https://github.com/jenkins-infra/helpdesk/issues/4124#issuecomment-2275506395
Added jdk-17 and jdk-21 Ubuntu-22(AMD and ARM) ssh agents to infra.ci, Ubuntu-22 (AMD and ARM) template will have jdk-11 by default.
> feat(infra.ci.jio): Added AZ VM templates for Ubuntu-22 AMD and ARM maven-17 and maven-21 agents

- clusters/publick8s.yaml
- config/geoipdata.yaml
- config/public-nginx-ingress__common.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/4240
This PR installs the new chart `geoipupdates` in a new namespace `geoipdata`.
Requires:
- https://github.com/jenkins-infra/azure/pull/803 to have a provisioned PVC in the namespace `geoipdata`
- https://github.com/jenkins-infra/helm-charts/releases/tag/geoipupdates-0.0.1 (first release of the chart)
- https://github.com/jenkins-infra/charts-secrets/commit/78d89c557a9863219d087023abf4fd180ed7add6 for the secrets
> feat(publick8s) install geoipdata chart

- clusters/publick8s.yaml
- config/updates.jenkins.io.yaml
Requires:
- The chart v4.x to be published - 
- Secrets to be updates: https://github.com/jenkins-infra/charts-secrets/commit/ca6c979ff887dce71fc2b67060aada3bf60e123e
Related to https://github.com/jenkins-infra/helpdesk/issues/4240 and https://github.com/jenkins-infra/helpdesk/issues/2649, this PR bumps the publick8s/updates.jenkins.io mirrorbits chart up to 2 major versions with configuration update to:
- 3.x:
- Have a visible mirrorbits configuration through values to fine tune the scans compared to the updates center regular runs
- Removing fallbacks to avoid URL rewrites with removal of the first `/` in URIs (https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2286023633)
- Do not remove a mirror when it responds a 404 or 3xx to avoid errors when scanning
- 4.x: remove …
> feat(publick8s/updates.jenkins.io) bump mirrorbits chart from 2.x to 4.x

- clusters/publick8s.yaml
- config/get-jenkins-io.yaml
Same as https://github.com/jenkins-infra/kubernetes-management/pull/5565, related to https://github.com/jenkins-infra/helpdesk/issues/4240
This PR updates the mirrorbits chart to 4.0.0 with the associated configuration.
Requires https://github.com/jenkins-infra/charts-secrets/commit/95657f9458ff57157663bb20a7e71afed1e7e6c7
> feat(publick8s/get.jenkins.io) bump mirrorbits chart from 2.x to 4.x

- config/get-jenkins-io.yaml
- config/updates.jenkins.io.yaml
Requires the version 5.0.1 of the mirrorbits chart (deployed with https://github.com/jenkins-infra/kubernetes-management/pull/5578)
This PR ensures that both mirrorbits systems have enforced security:
- No privilege escalation possible
- No capacilities
- Readonly rootFS
- non root user enforced
> fix(publick8s) ensure enforced security for both get.jenkins.io and azure.updates.jenkins.io

- config/updates.jenkins.io.yaml
This PR fines tunes the mirrors.updates.jio mirrorbits service:
- Disable Gzip (as the ingress already uses gzip or brotli: https://github.com/jenkins-infra/kubernetes-management/blob/e7ce1aa86f72571e29762bb105ada0c6ad65d425/config/public-nginx-ingress__common.yaml#L37-L38) so mirrorbits will use less CPU and will have better latency
- Only scan mirrors once a day since update center already scans every 5 min
- Scan the local repository at the same frequency as the UC script (e.g. 5 min)
- Do NOT disable a mirror if it triggers a redirect
- Set the US East mirror as fallback to handle the 10-15s window every 5 min where local repository is refreshed => this should fix the HTTP/503 errors
> fix(publick8s/updates.jio) fine tune configuration: set up correct scan intervals, disable gzip and do not block mirrors when redirecting

- config/get-jenkins-io.yaml
- config/updates.jenkins.io.yaml
- yamllint.config
- Disable gzip on the mirrorbits backends as [ingress is doing gzip now](https://github.com/jenkins-infra/kubernetes-management/pull/5442)
- chore: set up yamllint comments rule to avoid warning due to updatecli parser (see https://github.com/jenkins-infra/kubernetes-management/commit/7f68d6474b095ddc530d0a6613d31d2c63fe01e8)
- Add comments for get.jio and updates.jio values to help understand
> fix(publick8s/get.jio) disable gzip + comments

- config/get-jenkins-io.yaml
- config/updates.jenkins.io.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/3837
This PR migrates the 4 mirrorbits pods (2 for get.jenkins.io and 2 for updates.jenkins.io) to `arm64` nodes.
Requires https://github.com/jenkins-infra/kubernetes-management/pull/5585 to ensure we have a mirrorbits image with full support for both CPU architectures
> feat(publick8s/get.jio + mirrors.updates.jio) switch to arm64 nodes

- config/jenkins_infra.ci.jenkins.io.yaml
As per https://github.com/jenkins-infra/helpdesk/issues/4244#issue-2472582870 :
init script of Linux SSH AZ agents in infra.ci is now in sync with the puppet code. If it tests successful we can proceed with the agent builds https://github.com/jenkins-infra/helpdesk/issues/4124#issuecomment-2295792812
> fix(infra.ci.jio): init script test for ssh AZ agents

- config/stats.jenkins.io.yaml
This PR enables `try_files` nginx config directive to allow direct links for this React application.
Ref:
- https://github.com/jenkins-infra/stats.jenkins.io/issues/118
- https://github.com/jenkins-infra/helpdesk/issues/4132#issuecomment-2298635602
- https://github.com/jenkins-infra/helm-charts/pull/1297
> fix(stats.jenkins.io): enable `try_files` directive to allow direct links

- config/jenkins_infra.ci.jenkins.io.yaml
As per https://github.com/jenkins-infra/helpdesk/issues/4124#issuecomment-2295792812
init script while deploying AZ linux vms has been fixed thus the linux JDK agents can be added to infra.ci.
Changes made has been generalised to other linux agents as per https://github.com/jenkins-infra/helpdesk/issues/4244#issuecomment-2301394723
> fix(infra.ci.jio): init script fix for linux AZ agents

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
Fixup of #5559
Related to https://github.com/jenkins-infra/helpdesk/issues/4165
Fixes the following error:
```
[Wed Aug 21 16:56:38 UTC 2024] Starting branch indexing...
ERROR: [Wed Aug 21 16:56:38 UTC 2024] Could not update folder level actions from source docker-jobs/account-app
[Wed Aug 21 16:56:38 UTC 2024] Finished branch indexing. Indexing took 0 ms
FATAL: Failed to recompute children of Docker Jobs » account-app
java.lang.IllegalArgumentException: Owner mismatch: jenkinsci vs. jenkins-infra
```
> hotfix(privatek8s/infra.ci) use correct owner for docker-jobs GH app

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4165#issuecomment-2302520444
Requires https://github.com/jenkins-infra/charts-secrets/commit/af886926f77c8d9fe4a48fdf815892b782e3f04a
Twin of #5599 but for Terraform Jobs
This PR also fixes the credential ID to avoid confusion (fixup of #5599)
Applied to the 7 Terraform Jobs
> feat(privatek8s/infra.ci) set up Terraform Jobs to use a new folder-scoped GHA

- Jenkinsfile_k8s
As per https://github.com/jenkins-infra/helpdesk/issues/4161#issuecomment-2299149540
`infracijioagents1` is removed from the kubenetes-management to upgrade to kubernetes 1.29
> chore(infracijioagents1): removing temporarily from management to upgrade to kubernetes 1.29

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/4256
Requires SOPS secrets to be added - https://github.com/jenkins-infra/charts-secrets/commit/9768641ff796c7f307f714f885c2bc308b8506a5
> feat(privatek8s/infra.ci) add GH app for Docker jobs (deployment only)

- Jenkinsfile_k8s
https://github.com/jenkins-infra/helpdesk/issues/4161#issuecomment-2306465432
> chore: exclude privatek8s cluster while upgrading to 1.29

- Jenkinsfile_k8s
Reverts jenkins-infra/kubernetes-management#5614
Related to https://github.com/jenkins-infra/helpdesk/issues/4161#issuecomment-2306465432
> Revert "chore: exclude privatek8s cluster while upgrading to 1.29"

- Jenkinsfile_k8s
Related to https://github.com/jenkins-infra/helpdesk/issues/4161#issuecomment-2306560872
> chore: exclude publick8s cluster while upgrading to 1.29

- Jenkinsfile_k8s
Reverts jenkins-infra/kubernetes-management#5616
Related to https://github.com/jenkins-infra/helpdesk/issues/4161#issuecomment-2306560872
> Revert "chore: exclude publick8s cluster while upgrading to 1.29"

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
- config/jenkins_infra.ci.jenkins.io.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/4165
This PR ensures that the Updatecli Gh App is only used where necessary:
- Top level credential removed
- Both UpdateCLI Jobs and Docker Jobs have the new credz
It will also fix the failing build of the new Updatecli Jobs
Search for this credential ID: https://github.com/search?q=org%3Ajenkins-infra%20github-app-updatecli-on-jenkins-infra&type=code
> fix(privatek8s/infra.ci) ensure updatecli pipelines - wether olds (in Docker jobs) and news (in Update Cli jobs) have the correct GitHub app

- config/updates.jenkins.io.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/4259
we switch mirrors.updates.jenkins.io mirrorbits to the public redis instance on azure.
need https://github.com/jenkins-infra/charts-secrets/commit/cb6bd65a3416a51f65f69c84931678ac97a2b48a before merging.
once merged, mirrorbits is expected to use fallback: no user impact expected except for geo-localization of requests.
> feat(publick8S/mirrors.updates.jio) switch to public-redis instance

- config/get-jenkins-io.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/4259
Requires:
- nice to have: data updates to the DB ID `1` on the new instance (done)
- must have: credentials  updated in sops: https://github.com/jenkins-infra/charts-secrets/commit/1f77315acbc0005afcdd2c00564c640dd0ff0847
> feat(publick8s/get.jio) switch redis instance

- config/updates.jenkins.io.yaml
- updatecli/updatecli.d/charts/jenkins-infra-tools-maven.yaml
This change enables the `mirrorbits` CLI and exposes the server gRPC protocol through a Kubernetes Service.
This service of `LoadBalancer` kind associated to an Azure Private Link service: it allows access through private networks without requiring any network peering of any kind.
Related to https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2325103688
Requires:
- Helm chart support for the `mirrorbits` CLI: https://github.com/jenkins-infra/helm-charts/pull/1291
- Permission to be fixed to allow `publick8s` to manage the Azure PLS: https://github.com/jenkins-infra/azure/pull/819
> feat(publick8s/mirrors.updates.jio) enable `mirrorbits` CLI

- config/updates.jenkins.io.yaml
Follow up of #5648 : the PLS is not reachable as the AKS subnet has a custom routing table which create mayhem.
We also should be safer by having this resource with a con figuration as close as possible as another internal LB working (private Nginx ingress).
Related to https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2325103688
> feat(publick8s/updates.jenkins.io) switch PLS to the data tier subnet

- config/jenkins_infra.ci.jenkins.io.yaml
Reverts jenkins-infra/kubernetes-management#5651
> Revert "Bump Jenkins Weekly docker image version on infra.ci.jenkins.io to 2.0.27-2.475"

- config/private-nginx-ingress__common.yaml
- config/public-nginx-ingress__common.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2330934069
The ingress (access) logs collected in datadog does not provide an easy way to discriminate between services.
This PR adds the namespace and name of the ingress for which a given access log line is meant to.
It follows the Nginx Ingress controller documentation which provides these 2 fields in addition to the usual Nginx fields: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/log-format/
Tested on a manual apply (and then roll backed) in pair with @smerle33 on the private Nginx of the private cluster, to ensure it does not fail the admission + the access logs format is changed with what we want
> feat(ALL/nginx ingresses): add namespace and ingress name to the access logs

- config/updates.jenkins.io_httpd.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2330934069
> hotfix(publick8s/updates.jenkins.io) the hostname `updates.jenkins-ci.org` was missing leading to user errors during the Update Center brownout 1.

- updatecli/updatecli.d/charts/accountapp.yaml
- updatecli/updatecli.d/charts/acme.yaml
- updatecli/updatecli.d/charts/cert-manager.yaml
- updatecli/updatecli.d/charts/codecentric-keycloak.yaml
- updatecli/updatecli.d/charts/datadog.yaml
- updatecli/updatecli.d/charts/env-jenkins-release.yaml
- updatecli/updatecli.d/charts/falco.yaml
- updatecli/updatecli.d/charts/github-comment-ops.yaml
- updatecli/updatecli.d/charts/incrementals-publisher.yaml
- updatecli/updatecli.d/charts/ipv6-lb-service.yaml
- updatecli/updatecli.d/charts/ircbot.yaml
- updatecli/updatecli.d/charts/javadoc.yaml
- updatecli/updatecli.d/charts/jenkins-infra-jobs.yaml
- updatecli/updatecli.d/charts/jenkins-kubernetes-agent.yaml
- updatecli/updatecli.d/charts/jenkins.yaml
- updatecli/updatecli.d/charts/jenkinsio.yaml
- updatecli/updatecli.d/charts/jenkinsisthewayio.yaml
- updatecli/updatecli.d/charts/ldap.yaml
- updatecli/updatecli.d/charts/mirrorbits-parent.yaml
- updatecli/updatecli.d/charts/nginx-ingress.yaml
- updatecli/updatecli.d/charts/nginx-website.yaml
- updatecli/updatecli.d/charts/plugin-health-scoring.yaml
- updatecli/updatecli.d/charts/plugin-site-issues.yaml
- updatecli/updatecli.d/charts/plugin-site.yaml
- updatecli/updatecli.d/charts/rating.yaml
- updatecli/updatecli.d/charts/reports.yaml
- updatecli/updatecli.d/charts/rss2twitter.yaml
- updatecli/updatecli.d/charts/uplink.yaml
- updatecli/updatecli.d/charts/wiki.yaml
As per https://github.com/jenkins-infra/kubernetes-management/issues/5663#issue-2506884201:
We updated all manifest tracking Helm Charts versions to use YAML path targets instead of file targets.
It allows using YAML path queries to perform selection of the list object based on attribute filters which was the proposed solution.
> feat(updatecli): Switch Helm Chart related manifest targets to native(YAML) queries

- config/stats.jenkins.io.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/4265#issuecomment-2342985525
> hotfix(publick8s/stats.jenkins.io) add the new stats.jenkins.io hostname to ingress

- clusters/publick8s.yaml
- config/updates.jenkins.io.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2345352162
Requires https://github.com/jenkins-infra/helm-charts/pull/1327 feature
> fix(publick8s/updates.jenkins.io) force redirection on mirrorbits even if accept header is set to 'application/json'

- config/get-jenkins-io.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2345352162
to avoid confusion between a json call and a json provided by mirrorbits, we enforce the outputMode to redirect, this will ensure that the json delivered is the correct one, and not a generated one.
following https://github.com/jenkins-infra/kubernetes-management/pull/5680 for updates.jenkins.io
> feat(get.jenkins.io): force the outputMode to redirect

- config/updates.jenkins.io_httpd.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2352782412
lets enable a rollout restart for the httpd pods to avoid `The .htaccess files mentioned in the errors were marked as "incomplete" in the Apache status monitor and were truncated on the file system.`
> feat(updates.jio): enable rollout restart for httpd every hour

- clusters/publick8s.yaml
- config/updates.jenkins.io-unsecured.yaml
- config/updates.jenkins.io.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2352944136
Need the new (Redis) secret: https://github.com/jenkins-infra/charts-secrets/commit/66340f36ab34a678e4430a8aee36d203e3255075
This PR installs, in updates-jenkins-io, a new mirrorbits instance which uses the same data as the existing one but has different ingresses.
It relies on 2 new mirrorbits chart features:
- Ability to reuse the same PVCs: https://github.com/jenkins-infra/helm-charts/pull/1339
- Ability to specify additional ingresses: https://github.com/jenkins-infra/helm-charts/pull/1344
The support of ingress traffic split based on the protocol used (HTTP or HTTPS) utilizes the following techniques:
- The existing ingress for `mirrors.updates.jenkins.io`, which handles both HTTP and HTTPS (and …
> feat(publick8s/updates.jenkins.io) add an HTTP-only mirrorbits instance

- updatecli/updatecli.d/jenkins-infra-tools-maven.yaml
As per https://github.com/jenkins-infra/helpdesk/issues/4283#issue-2514368763
The log for the updatecli diff has been cleaned up by using a better match pattern.
The manifest has been move to the top updatecli.d folder.
> chore(updatecli):Improve lengthy maven manifest

- config/stats.jenkins.io.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/4132#issuecomment-2352333521 and https://github.com/jenkins-infra/helpdesk/issues/4291
lets defined manual locations to avoid 200 errorcode for 404
> feat(stats.jenkins.io): override the locations to avoid 200 for 404 errors

- clusters/publick8s.yaml
Reverts jenkins-infra/kubernetes-management#5721
> Revert "Bump `plugin-health-scoring` helm chart version to 3.0.0"

- clusters/publick8s.yaml
- config/updates.jenkins.io_httpd-unsecured.yaml
- config/updates.jenkins.io_httpd.yaml
This PR introduces a new component for updates.jenkins.io: a httpd installation only for HTTP workflow.
- The persistent vollume has been provisioned (empty) in https://github.com/jenkins-infra/azure/pull/840
- Filled the PV with a copy of the data currently in `updates-jenkins-io-redirects` fileshare, with the top-level `.htaccess` updated:
```diff
- RedirectMatch 307 (.*)$ https://mirrors.updates.jenkins.io$1
+ RedirectMatch 307 (.*)$ http://mirrors.updates.jenkins.io$1
```
- Tested on production (and then deleted) with success:
```
$ curl --silent --show-error --output /dev/null --fail --write-out '%{redirect_url}' 'http://azure.updates.jenkins.io/internal_http/update-center.json?id=default&version= …
```
> feat(publick8s/updates.jenkins.io) installs an httpd HTTP-only component

- config/updates.jenkins.io_httpd-secured.yaml
This PR enables the handling of HTTP traffic coming to `azure.updates.jenkins.io `(and `updates.jenkins.io` + `updates.jenkins-ci.org`) by using the same internal redirect trick as in #5708 for `mirrors.updates.jenkins.io` (but simpler as there are no need for the `index.html` redirect).
> feat(publick8s/updates.jenkins.io) enable HTTP traffic split

- config/updates.jenkins.io-content-secured.yaml
- config/updates.jenkins.io-content-unsecured.yaml
Fixup of #5749 
This PR corrects the ingresses introduces for mirrorbits only in #5749 with:
- Fixed regexp to support the file `TIME` (it was a bug present since months)
- Removed an unwanted rewrite leading to HTTP/404 errors for all requests
> fix(poublick8s/mirrors.updates.jenkins) correct ingress rexgexp and remove unwanted rewrite

- config/updates.jenkins.io-content-secured.yaml
- config/updates.jenkins.io-content-unsecured.yaml
Since the update center generator is now run every 10 min (instead of 5), we have to adapt the mirror scan to avoid too much activity
> feat(publick8s/updates.jenkins.io) only scan mirrors on a 10 min basis instead of 5

- config/updates.jenkins.io-content-unsecured.yaml
This PR enables the CLI for `mirrorbits` on the `content-unsecured` mirrorbits component as per https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2364054995.
Notes:
- It utilizes the same Azure PLS but on another port to avoid spinning up other LBs or network routes (a technique found in https://dev.to/lastcoolnameleft/azure-private-link-service-load-balancer-aks-limitation-44db)
- Note: the IPv4 used here forbids dualstack AND will have to be tracked. It is the loadbalancer's exposed IP, it is NOT the associated PLS IP!
- Same password for both instance (as it is the same content). Pushed in (private) https://github.com/jenkins-infra/charts-secrets/commit/5010730d4feae95cee8ab1995b5dc70e58e42200
> feat(publick8s/mirrors.updates.jio) enable CLI for the content-unsecured component

- config/datadog_publick8s.yaml
> fix(publick8s) disable Datadog apache integration to avoid hammering our httpd with HTTP/404 errors on /server-status

- clusters/publick8s.yaml
- config/updates.jenkins.io-content-secured.yaml
- config/updates.jenkins.io-content-unsecured.yaml
- config/updates.jenkins.io_httpd-secured.yaml
- config/updates.jenkins.io_httpd-unsecured.yaml
This PR:
- Fixes up #5759 by using proper components for mirrorbits and httpd
- Fine tune the httpd instances (requires https://github.com/jenkins-infra/helm-charts/pull/1368 to be deployed as the `1.4.0` version) to remove the error logs
```text
[mpm_event:error] [pid 1:tid 1] AH00484: server reached MaxRequestWorkers setting, consider raising the MaxRequestWorkers setting
[mpm_event:error] [pid 1:tid 1] AH10159: server is within MinSpareThreads of MaxRequestWorkers, consider raising the MaxRequestWorkers setting
```
> fix(publick8s/updates.jio) correct datadog httpd logs setup + fine tune httpd MPM events

- config/updates.jenkins.io-content-secured.yaml
- config/updates.jenkins.io-content-unsecured.yaml
Goal: server the Jenkins favicon.ico from mirrors (added manually) to limit the amount of 4xx from Cloudflare
> fix(publick8s/mirrors.updates.jio) also serve ICO files

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
As per https://github.com/jenkins-infra/helpdesk/issues/4365#issuecomment-2437105277
We need an IAM user 'updatecli' with it's `UPDATECLI_AWS_ACCESS_KEY_ID` and `UPDATECLI_AWS_SECRET_ACCESS_KEY`. 
Once credentials are created and available, we can merge this PR which will allow us to run aws related updatecli jobs
> chore(updatecli):Add aws credentials for updatecli jobs

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
This PR unblocks https://github.com/jenkins-infra/cloudflare/pull/40
Requires secret to be pushed (https://github.com/jenkins-infra/charts-secrets/commit/779c0c03ec2c73146106df79fc97f81be688fbc3) and applied to infra.ci (https://infra.ci.jenkins.io/job/kubernetes-jobs/job/kubernetes-management/job/main/43579/)
> feat(privatek8s/infra.ci.jenkins.io) add a new credential (Datadog API key) in Cloudflare terraform job

- config/ldap.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/4320 and required by https://github.com/jenkins-infra/helpdesk/issues/4315
Note: this IP will be exported in the future report for jenkins-infra/terraform-aws-sponsorship
> feat(publick8s) add the new aws.ci.jio controller outbound IP to allowed list for LDAP

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/4355#issue-2586619289
As per https://github.com/jenkins-infra/packer-images/pull/1526#pullrequestreview-2438017043
aws credentials are required to include aws garbage collection in the `Jenkinsfile_gc` pipeline.
Further steps include adding aws garbage collector to the pipeline.
> chore(garbage-collector) Add aws credentials for aws garbage collection

- config/updates.jenkins.io_httpd-secured.yaml
- config/updates.jenkins.io_httpd-unsecured.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/4402
in order to solve the inconstancy and in parallel of dealing with azcopy, we choose to remove the rollout every hour as it tend to unmount/remount the volume and generate conflicts.
> feat(update.jio) disable httpd Restart cronjob

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/4316
As noted in https://github.com/jenkins-infra/jenkins-infra/pull/3739, the PR https://github.com/jenkins-infra/jenkins-infra/pull/3737 did broke the updatecli builds for Puppet as it now requires and AWS credential.
This PR adds the packer credential (for now) to fix this issue
> feat(privatek8s/infra.ci) add missing credential for the updatecli job for jenkins-infra (puppet)

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/4355
Since https://github.com/jenkins-infra/helm-charts/pull/1429 includes the feature to disable Github notification, we apply the configuration to our garbage collector job on `packer-images`
> feat(privatek8s/infra.ci) disables GitHub notifications on the `packer-images` gc job

- clusters/publick8s.yaml
- config/updates.jenkins.io-rsync.yaml
Part of https://github.com/jenkins-infra/helpdesk/issues/4402
Deploys https://github.com/jenkins-infra/helm-charts/pull/1434 in `publick8s` for updates.jenkins.io
> feat(publick8s/updates.jenkins.io) bump rsync service to 2.0.0 (breaking) chart

- clusters/publick8s.yaml
- config/updates.jenkins.io-rsyncd-data.yaml
(on the new NFS PVC) introduced in #5933. Reverts c6d26f3c
Related to https://github.com/jenkins-infra/helpdesk/issues/4402
Requires https://github.com/jenkins-infra/azure/pull/887 to be merged and deployed with success
> feat(publick8s/updates.jenkins.io) restore the rsyncd-data service 

- config/updates.jenkins.io_httpd-secured.yaml
- config/updates.jenkins.io_httpd-unsecured.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/4402
This PR switches the Apache and Mirrorbits instances of updates.jenkins.io to use the new NFS PVC.
Requires https://github.com/jenkins-infra/update-center2/pull/829 to be merged and successfull at least twice (to have data filled into the PVC).
> feat(publick8s/updates.jenkins.io) use the new NFS PVC with subdir mounts for HTTPD

- clusters/publick8s.yaml
- config/updates.jenkins.io-content-secured.yaml
- config/updates.jenkins.io-content-unsecured.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4402#issuecomment-2506471357
Blocked by https://github.com/jenkins-infra/update-center2/pull/830 and https://github.com/jenkins-infra/crawler/pull/155
> feat(publick8s/updates.jenkins.io) switch mirrorbits instances to the new NFS PVC

- updatecli/updatecli.d/charts/datadog.yaml
While reviewing https://github.com/jenkins-infra/kubernetes-management/pull/5946, it appeared we were not tracking all clusters
> chore(updatecli) add untracked clusters for datadog manifest

- clusters/publick8s.yaml
- config/geoipdata.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/4278
deploying geoipupdater on a staging environement as a kubernetes cronjob.
kept in dry-run mode for now to check the cron
> feat(publick8s): add geoipupdater in dry-run mode for now

- config/geoipdata.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/4278 and https://github.com/jenkins-infra/helpdesk/issues/4240
following #5982 this PR deploy the new cronjob in production, the geoip database from maxmind will be updated once a day at 00:30AM.
setting back the production accountid and licence within the secrets https://github.com/jenkins-infra/charts-secrets/commit/63d87ed6eea9e634e5efae6f1fce4daae90251fb
> feat(publick8s): geoipupdater on production

- clusters/publick8s.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4441
As usual, this PR is not sufficient: a manual operation is required to remove the cronjob and associated resources with (and un-commented code of course):
```
helmfile -f ./clusters/publick8s.yaml -l name=geoipdata delete
```
> hotfix(publick8s) stop managing geoipupdate cronjob

- config/updates.jenkins.io-content-secured.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/4401
No helmfil diff changes should be shown as the mirrorbits config is a secret
> feat(publick8s/UC) set archives.jio as mirrors fallback

- clusters/cijioagents1.yaml
- clusters/infracijioagents1.yaml
- config/docker-registry-secrets.yaml
Datadog charts are the only last users of this chart and they use GCR Docker images (no auth, no rate limit).
So this chart release is unneeded. It will also simplify the bootstrap processed hen creating a new cluster.
Notes: 
- Requires a cleanup in SOPS chart secrets once applied successfully (not before)
- Requires a manual removal of the existing secrets once applied successfully (not before):
```text
ci.jio-agents-1:
$ kubectl get secrets -A  | grep dockerconfigjson
jenkins-agents-bom       dockerhub-credential                            kubernetes.io/dockerconfigjson        1      218d
jenkins-agents           dockerhub-credential                            kubernetes.io/dockerconfigjson        1      218d
$ kubectl get secrets -A  | grep dockerconfigjson     
datadog …
```
> cleanup(ci.jio-agents-1, infra.ci.jio-agents-1) remove Docker registry credential secret as unused anymore

- Jenkinsfile_k8s
- clusters/cijioagents2.yaml
- config/datadog_cijenkinsio-agents-2.yaml
- config/datadog_infracijioagents1.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/4319#issuecomment-2539442223
starting adding the new EKS cluster to infra.ci kubernetes-management
kubeconfig added as secrets here https://github.com/jenkins-infra/charts-secrets/commit/a24b1ec79f738ab2b2d01b46ea3111feec1abcb0
and datadog api key here https://github.com/jenkins-infra/charts-secrets/commit/c7505e8517376fd712cea6673d06c0191e5d24a9
need https://github.com/jenkins-infra/kubernetes-management/pull/6021
⚠️ BEFORE merging this PR we need to create the `datadog` namespace
using : 
```
kubectl config use-context arn:aws:eks:us-east-2:326712726440:cluster/cijenkinsio-agents-2
kubectl create ns datadog
```
splitting in multiple PR:
this one is with the minimum release possible, so only datadog as a start
> feat: add a new kubernetes cluster cijenkinsio-agents-2 with datadog as unique release

- config/updates.jenkins.io-content-secured.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4481
This PR adds a missing annotation which allows Cert Manager to track the certificate and renew it
> fix(publick8s) ensure cert-manager tracks the SSL certificate for mirrors.updates.jenkins.io

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
As per https://github.com/jenkins-infra/helpdesk/issues/4479
We require AWS credentials to use aws cli commands with updatecli to track and update cluster addons versions
> feat(privatek8s/infra.ci) adds aws credentials for updatecli used by `terraform-aws`sponsorship`

- config/artifact-caching-proxy_azure-cijenkinsio-agents-2.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/4319#issuecomment-2597798044
This PR sets up the Kubernetes Service for Artifact Caching Proxy in the new ci.jenkins.io-agents-2 cluster to be exposed through an AWS internal load balancer.
Tested with success locally.
Source documentations:
- https://docs.aws.amazon.com/eks/latest/userguide/auto-configure-nlb.html
- https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/service/annotations/
> feat(ci.jio-agents-2) enable internal LB for ACP

- config/artifact-caching-proxy_azure-cijenkinsio-agents-2.yaml
- updatecli/updatecli.d/acp-lb-aws.yaml
- updatecli/updatecli.d/acp-lb-azure.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/4317#issuecomment-2612017565,
This PR adds automatic tracking of the subnets and IP configurations for the AWS ACP LB.
Now, any changes in the subnets settings of https://github.com/jenkins-infra/terraform-aws-sponsorship will be tracked by `updatecli` and a PR will be created to pass these changes.
Note: we had to delete the SVC for https://github.com/jenkins-infra/terraform-aws-sponsorship/pull/112 to succeed
> chore(updatecli) track the ACP AWS LB configuration from Terraform Infra reports

- config/artifact-caching-proxy_azure-cijenkinsio-agents-2.yaml
This PR updates the ACP configuration in ci.jenkins.io-agents-2 cluster to avoid errors such as:
```
[error] 22#22: *336648 upstream timed out (110: Operation timed out) while SSL handshaking to upstream, <...>
```
> fix(ci.jenkins.io-agents-2/ACP) enable passing SNI to backend upstreams

- updatecli/updatecli.d/acp-lb-aws.yaml
Ref. https://github.com/jenkins-infra/kubernetes-management/pull/6183#pullrequestreview-2593708639
Follow up of https://github.com/jenkins-infra/kubernetes-management/pull/6146 and https://github.com/jenkins-infra/terraform-aws-sponsorship/pull/117
This PR fixes the updatecli manifest tracking the ACP AWS LB network settings to only retrieve data specified in the ACP part of the report.
> chore(updatecli) fix ACP AWS LB manifest to ensure we only have 1 subnet per AZ (and 1 IP per subnet)

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4321#issuecomment-2643226880
Blocks https://github.com/jenkins-infra/terraform-aws-sponsorship/pull/122
> feat(privatek8s/infra.ci) add DockerHub credential for new ECR pull-through cache in Terraform AWS

- clusters/cijioagents2.yaml
- config/hub-mirror_cijioagents2.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4321#issuecomment-2645860911
Requires https://github.com/jenkins-infra/charts-secrets/commit/689f2c7e3babf8eab116031d240d1845e1b327a6
Tested once manually.
> feat(ci.jenkins.io-agents-2) add a Docker registry mirroring DockerHub

- config/hub-mirror_cijioagents2.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4321
Fixup of #6222 
When testing the new registry mirror, we ended with errors HTTP/500 responded to Docker Engine when trying to get images with the following log on Registry side:
```
time="2025-02-13T09:53:00.527942139Z" level=error msg="response completed with error" err.code=unknown err.detail="filesystem: mkdir /var/lib/registry/docker: permission denied" err.message="unknown error" go.version=go1.20.8 http.request.host="k8s-hubmirro-hubmirro-f5b8613a86-574b882e7a7e93d0.elb.us-east-2.amazonaws.com:5000" http.request.id=a88445fd-0208-4477-b353-84a5b7910e21 http.request.method=HEAD http.request.remoteaddr="10.0.131.247:29797" http.request.uri="/v2/library/busybox/manifests/latest" http.request.useragent="docker/27.5.1 go/go1.22.11 …
```
> hotfix(ci.jenkins.io-agents-2/hub-mirror) add a ugly hack to set up volume permissions on init

- config/jenkins-kubernetes-agents_ci.jenkins.io_cijioagents2-bom.yaml
Following #6227, since we saw errors in ci.jenkins.io such as:
```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://A5986B0920D06F1E0CABF431FF7678F9.yl4.us-east-2.eks.amazonaws.com/api/v1/namespaces/jenkins-agents-bom/pods. Message: pods "jnlp-maven-bom-xj5lm" is forbidden: exceeded quota: pods, requested: pods=1, used: pods=150, limited: pods=150. Received status: Status(apiVersion=v1, code=403, details=StatusDetails(causes=[], group=null, kind=pods, name=jnlp-maven-bom-xj5lm, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=pods "jnlp-maven-bom-xj5lm" is forbidden: exceeded quota: pods, requested: pods=1, used: pods=150, limited: pods=150, metadata=ListMeta(_continue=null, remainingItemCount=null, …
```
> hotfix(cijioagents2) increase BOM pods quota from `300` to `400`

- Jenkinsfile_updatecli
- updatecli/updatecli.d/acp-lb-aws.yaml
fixup of #6222
also, stop running `updatecli diff` on the `main` branch for faster runs
>  chore(updatecli) correct AWS LB manifest and optimize pipeline on principal branch

- Jenkinsfile_k8s
as per https://github.com/jenkins-infra/helpdesk/issues/4258#issuecomment-2663661996
remove `cijioagents1` from pipeline
> feat(cijioagents1) removed from the jenkinsfile for kub 1.30 upgrade

- config/ldap.yaml
- updatecli/updatecli.d/pvc-ldap.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/4544#issuecomment-2671423226.
This PR tracks the LDAP PVC names: both data and backup which is possible since https://github.com/jenkins-infra/azure/pull/940
Tested locally:
```
target: target#updatePvcNameUnsecured
-----------------------------
**Dry Run enabled**
⚠ - change detected:
* key "$.persistence.customBackupClaimName" should be updated from "\"\" # Tracked by updatecli" to "ldap-jenkins-io-backup", in file "config/ldap.yaml"
target: target#updateDataPvcName
------------------------
**Dry Run enabled**
✔ - no change detected:
* key "$.persistence.customDataClaimName" already set to "ldap-jenkins-io-data", from file "config/ldap.yaml"
```
> chore(updatecli) track LDAP PVC names

- config/jenkins_infra.ci.jenkins.io.yaml
as seen in the logs of a windows agent on infra.ci: 
```
Volume in drive C is Windows
Volume Serial Number is 123B-47A8
Directory of C:\
File Not Found
Error: unknown command "restart" for "agent.exe"
Did you mean this?
restart-service
```
see https://github.com/jenkins-infra/jenkins-infra/pull/3809 for ci.jio
> fix(datadog/windows): the datadog restart parameter is 'restart-service'

- updatecli/updatecli.d/charts/nginx-ingress.yaml
As 4.12.x breaks things for us: https://github.com/jenkins-infra/kubernetes-management/pull/6068#pullrequestreview-2527313501
Let's start with pinning to 4.11.x and getting new patches.
In particular, we have to check https://github.com/kubernetes/ingress-nginx/issues/13002
> chore(updatecli) ping nginx-ingress to 4.11.x

- Jenkinsfile_updatecli
As per - https://github.com/jenkins-infra/helpdesk/issues/4539#issuecomment-2740495511
We now use scripted pipeline syntax
> chore(jenkinsfile_updatecli): Use current node execution context for `kubernetes-management`

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
as per https://github.com/jenkins-infra/pipeline-library/issues/906
and https://github.com/jenkins-infra/pipeline-library/pull/907
this provide jobs in infra.ci.jenkins.io to run the pipeline (already done by ci.jenkins.io: https://ci.jenkins.io/job/Infra/job/pipeline-library/job/master/744/ and also updatecli
> feat(privatek8s/infra.ci.jio) add updatecli multiubranch job for `jenkins-infra/pipeline-library`

- clusters/publick8s.yaml
- config/ldap.yaml
Ref. https://github.com/jenkins-infra/helm-charts/pull/1616 which deprecates the list `service.whitelisted_sources` in favor of a new map `service.lbAllowSources` for easier maintenance (updatecli can now track the keys instead of fragile array numeric indexes)
> feat(publick8s/ldap) bump chart to 3.0.0 and adapt values (array -> map for LB source list)

- config/ldap.yaml
- updatecli/updatecli.d/configs/ldap-restricted-ips.yaml
This change introduces 2 minors fixes on the publik8s's LDAP
- Since #6381 we can (and should) specify JFrog allowed CIDR as a single string (comma separated string list)
- Since #6379 we use a map instead of a list: the updatecli manifest needs fix
> chore(publick8s/ldap) fix jfrog multi IP and updatecli manifest 

- config/ldap.yaml
- Use list of strings when needed (LB outbound IPs)
- Comment untracked elements
This PR should not make any change to production resources: it's only syntactic sugar to allow proper updatecli tracking
> chore(publick8s/ldap) cleanup config

- config/ldap.yaml
This PR removes 2 IPs from the LDAP allow-list for its inbound LoadBalancer:
- SpamBot (ref. https://github.com/jenkins-infra/backend-confluence-spam-remover/tree/master) was a service run along with the Confluence service in the Jenkins infra to remove spam bot users. It has been archived in November 2022 and is no longer needed
- Accounts.jenkins.io runs in the AKS cluster since 2020 and access LDAP through the private pod IP as it run in the same private network. The public IP referenced in the LDAP allow list is the former OSUOSL VM which used to run the account app
> cleanup(publick8s/ldap) remove 2 unused IPs from allow-list: spambot and legacy account-a))

- config/ldap.yaml
- updatecli/updatecli.d/configs/ldap-restricted-ips.yaml
This change increase the amount of CIDR/public IPv4 tracked by `updatecli` to keep the LDAP allow-list up to date.
It tracks:
- All CIDR/IPs which are exported by the [Terraform Azure project](jenkins-infra/azure):
- The LoadBalancer outbound IPs for `publick8s` and `privatek8s` (note: their NAT outbound IP are tracked in the Azure Net project, so not in the scope of this change) to allow access from infra.ci/release.ci (privatek8s) and for weekly.ci/accounts.jenkins.io (publick8s, when the private routing fails to use the NAT gateway and the outbound LB: recommended by Microsoft)
- The Pods CIDR IPs for `publick8s` for weekly.ci/accounts.jenkins.io (default behavior through private network)
- puppet.jenkins.io VM outbound IP (required by the Puppet master)
- All the JFrog outbound IPs …
> chore(updatecli) track all LDAP CIDR/IPs from terraform-azure and Jfrog API

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4619
Credential value pushed to SOPS in https://github.com/jenkins-infra/charts-secrets/commit/4d0bfc8fc9e4eca79f17d2649b85d8db63a51f14
> feat(privatek8s/infra.ci) add the cijenkinsio-agents-1 admin kubeconfig to the kubernetes-manegement job

- clusters/cijioagents1.yaml
- clusters/cijioagents2.yaml
- config/artifact-caching-proxy_azure-cijenkinsio-agents-1.yaml
- updatecli/updatecli.d/charts/artifact-caching-proxy.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4619
The ACP settings have been extracted from the former Azure cluster, but adapted to what we learnt when running in AWS (ref. https://github.com/jenkins-infra/helpdesk/issues/4545):
- Only 1 replica
- No CPu limit to avoid throttling requests (it is safe to do this on non CI agents workloads when we have static workloads)
> feat(cijenkinsio-agents-1) install ACP with 1 replica and no CPU limits

- clusters/cijioagents1.yaml
- config/cijioagents1-maven-cacher.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4619#issuecomment-2775692473
Now that the "Maven Cacher" PVCs have been created, we can proceed.
Differences from the AWS EKS "Maven Cacher":
- `amd64` CPU
- Use internal ACP URL (might be cherry picked to EKS)
> feat(cijenkinsio-agents-1) add maven-cacher release

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
As per - https://github.com/jenkins-infra/pipeline-library/issues/918
We want to avoid building docker images on tag discovery.
This PR disables tag discovered builds for `docker-404`
> feat(publick8s/infra.ci.jenkins.io) Disable tag discovery for the job `docker-404`

- updatecli/updatecli.d/configs/acp-lb-azure.yaml
- updatecli/updatecli.d/configs/ldap-restricted-ips.yaml
Fixup of #6403 and #6417 were the changes broke updatecli manifests.
This PR expects the LDAP IP to change as I used the inbound IP for azure.ci.jenkins.io in #6417 while LDAP expects the outbound IPs (from the NAT gateway) - https://github.com/jenkins-infra/helpdesk/issues/4620
> chore(updatecli) fix ldap and ACP-azure IP tracking manifests

- clusters/cijioagents2.yaml
- clusters/infracijioagents1.yaml
- clusters/privatek8s.yaml
Note: will need a cleanup (removal) of `config/jenkins-kubernetes-agents/secrets.yaml` in the private jenkins-infra/chart-secrets SOPS repositories once applied with success.
> cleanup(privatek8s,infraciagents1,cijenkinsio2) remove unused Docker pull credentials in the `jenkins-agents` namespaces

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
Related to - https://github.com/jenkins-infra/pipeline-library/issues/918
We are disabling tag discovery on docker jobs to avoid infinite builds on infra.ci
> chore(jenkins-jobs): Disable tag discovery for all docker jobs

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
As per 
- https://github.com/jenkins-infra/helpdesk/issues/4638#issue-2993599829
We need to enable Tag discovery for PHS to deploy on manually created tags.
> chore(privatek8s/infra.ci.io): Enable tag discovery for Plugin Health Scoring

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
Related to 
- https://github.com/jenkins-infra/helpdesk/issues/2778#issue-1130384384
This PR adds `docker-crond` to updatecli jobs to make updatecli run as a distinct pipeline
> chore(privatek8s/infra.ci.jenkins.io): Add `docker-crond` to updatecli jobs

- config/jenkins_infra.ci.jenkins.io.yaml
see https://github.com/jenkinsci/customizable-header-plugin/pull/194/files#r2054468199
deprecated parameter: hoverColor
> fix(jenkins_infra.ci.jenkins.io): remove hoverColor in header as it crash jcasc

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4554#issuecomment-2824152635
> cleanup(privatek8s/infra.ci) remove the docker-inbound-agents jobs as the repository is archived

- Jenkinsfile_k8s
- clusters/privatek8s-sponsorship.yaml
- config/datadog_privatek8s_sponsorship.yaml
Requires #6484 
- The cluster manifest has been created from the current `privatek8s` but removed all releases except datadog
- Requires datadog secret tokens: https://github.com/jenkins-infra/charts-secrets/commit/aa40929da0811dfd85aec7908dad6d94f4a91db3
> feat: add privatek8s_sponsorship cluster

- clusters/privatek8s-sponsorship.yaml
- config/public-nginx-ingress_privatek8s_sponsorship.yaml
Tested with success manually, then uninstalled (and removed NS) prior to the PR. The public LB was created with the provided public IPv4 with no errors.
> feat(privatek8s-sponsorship) add public-nginx-ingress release

- clusters/privatek8s-sponsorship.yaml
This PR adds the 2 PVCs (and associated resources: PVs and secret) used by release.ci agents.
Note: the goal is to create the resources with the same settings as in the current `privatek8s` before importing them in Terraform for static management (so it would be easier to check the settings and eventual drift in Terraform by importing them)
> feat(privatek8s-sponsorship) add core-package PV/PVCs

- config/private-nginx-ingress_privatek8s_sponsorship.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/4250#issuecomment-2838032516
Applied manually with success: we can now reach the private ingress through the current DNS
> hotfix(privatek8s-sponsorship/private-nginx-ingress) correct internal LB annotation to use the proper IPv4

- clusters/privatek8s-sponsorship.yaml
- clusters/privatek8s.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4250#issuecomment-2838032516
- Add the `rss2twitter` release
- Add the `github-comments-bot` release
- Comment out migrated releases from `privatek8s` even if disabled
This PR can only be merged after:
- https://github.com/jenkins-infra/azure-net/pull/371 is merged and deployed successfully
- The deployments of `rss2twitter` and `github-comment-ops` have been scaled to zero on `privatek8s`:
```
kubectl -n rss2twitter scale --replicas=0 deployment rss2twitter
kubectl -n github-comment-ops scale --replicas=0 deployment github-comment-ops
```
> feat(privatek8s-sponsorship) migrate rss2twitter and github-comment-ops

- config/github-comment-ops.yaml
- config/rss2twitter.yaml
The Azure monitor on `privatek8s` shows we are using deprecated node selector labels:
This PR fixes these depreciations by aligning the node selector labels with the infra.ci and release.ci controllers installations.
> fix(privatek8s) correct deprecated node selector labels

- config/jenkins_infra.ci.jenkins.io.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4121#issuecomment-2890355054
> feat(privatek8s/infra.ci) bump runtime JDKs from 17 to 21 (controllers and agents)

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
Not needed anymore, as per https://github.com/jenkins-infra/helpdesk/issues/4671
> feat(privatek8s/infra.ci) remove the infra-reports/plugins-migration job

- config/jenkins_weekly.ci.jenkins.io.yaml
The Design Library logo only really works in light mode - its pretty hard to read in dark mode (and will be even harder when https://github.com/jenkinsci/dark-theme-plugin/pull/591 is released).
> Remove Design Library logo from Dashboard on weekly.ci.jenkins.io

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
Ref https://matrix.to/#/!JLUOInpEYmxJIYXlzs:matrix.org/$opnKFVudmgQHamLtoP5klsjg5od2i3MfE55dN-rsYKE?via=g4v.dev&via=gitter.im&via=matrix.org
@zbynek reported that creating a tag on https://github.com/jenkins-infra/docker-plugin-site-issues/ did not trigger publication on DockerHub.
As caught by @smerle33, we are missing a specific job configuration which prevents tags to be discovered. Ideally we should enable "CD" by setting `automaticSemanticVersioning` to `true` in https://github.com/jenkins-infra/docker-plugin-site-issues/blob/5c26cf209a8af5c8623b37fcede82d5250612f0f/Jenkinsfile_k8s#L7 but let's starting with this change now so we can deliver a new version
> fix(privatek8s/infra.ci) ensure docker-plugin-site-issues job scans for tags

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/4689#issuecomment-2961894408
add the credential into infra.ci to admin the new cluster infracijioagents2
> feat(infra.ci): adding a credential for kubeconfig for infracijioagents2

- config/get-jenkins-io.yaml
> fix(publick8s/get.jio) add missing datadog logs collection annotation for httpd

- updatecli/updatecli.d/charts/datadog.yaml
to fix errors on main builds since removal of infracijioagents1: https://github.com/jenkins-infra/helpdesk/issues/4689#issuecomment-2961894408
> chore(updatecli): remove datadog tracking for infracijioagents1 and add infracijioagents2

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
Requires https://github.com/jenkins-infra/charts-secrets/commit/7ec95fbf5afedefbb86db5da50c8108c3a0b8881
> feat(privatek8s/infra.ci) replace the kubeconfig of (deprecated) infracijenkinsio-agents-1 by the new AWS cijenkinsio-agents-2

- config/ldap.yaml
We'll have to track the IP in a subsequent PR, but at least initial provisioning can work so @smerle33 won't be blocked on the Puppet part.
> feat(publick8s/ldap) allow aws.ci.jenkins.io to reach the LDAP for authentication

- clusters/cijioagents2.yaml
- config/artifact-caching-proxy_aws-cijenkinsio-agents-2.yaml
- config/cijioagents2-maven-cacher.yaml
- config/hub-mirror_cijioagents2.yaml
- config/jenkins-kubernetes-agents_ci.jenkins.io_cijioagents2-bom.yaml
- config/jenkins-kubernetes-agents_ci.jenkins.io_cijioagents2.yaml
- updatecli/updatecli.d/charts/datadog.yaml
- updatecli/updatecli.d/charts/docker-registry.yaml
- updatecli/updatecli.d/charts/jenkins-kubernetes-agent.yaml
- updatecli/updatecli.d/charts/maven-cacher.yaml
- updatecli/updatecli.d/configs/acp-lb-aws.yaml
- updatecli/updatecli.d/configs/docker-registry-aws.yaml
- updatecli/updatecli.d/configs/jenkins-kubernetes-agent.yaml
- updatecli/updatecli.d/configs/ldap-restricted-ips.yaml
- updatecli/updatecli.d/configs/maven-cacher.yaml
- updatecli/updatecli.d/docker-images/maven-cacher.yaml
- updatecli/updatecli.d/jenkins-controllers/kubernetes-pods-quotas.yaml
Follows up (and tracks) most of the moving elements introduced by:
- https://github.com/jenkins-infra/kubernetes-management/pull/6739
- https://github.com/jenkins-infra/kubernetes-management/pull/6740
- https://github.com/jenkins-infra/kubernetes-management/pull/6741
- https://github.com/jenkins-infra/kubernetes-management/pull/6743
- https://github.com/jenkins-infra/kubernetes-management/pull/6744
- https://github.com/jenkins-infra/kubernetes-management/pull/6745
- https://github.com/jenkins-infra/kubernetes-management/pull/6746
> chore(updatecli) track (most) charts versions, docker image versions and configuration for `cijenkinsagents2` cluster

- config/jenkins-jobs_infra.ci.jenkins.io.yaml
- Retrieved with `terraform output privatek8s_admin_sa_kubeconfig` from jenkins-infra/azure project
- Secret value set up by https://github.com/jenkins-infra/charts-secrets/commit/fcf3400fd4e6193be9f5f4cdbd5ec33707cf4b90 (required)
> feat(privatek8s/infra.ci) add kubeconfig credential for the new `privatek8s` CDF cluster

- Jenkinsfile_k8s
- clusters/privatek8s.yaml
- config/datadog_privatek8s.yaml
Requires #6849 (`kubeconfig` to reach the `privatek8s` cluster) and https://github.com/jenkins-infra/charts-secrets/commit/3ff996d33601d8bdc32dc125af2c786d764313f9 (datadog secrets)
> feat: add privatek8s (CDF) cluster with only datadog helmfile release

- config/datadog_privatek8s.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/4690
This PR ensure `datadog` installation in `privatek8s` is successful. It removes a workaround which used to be recommended by Datadog to ensure AKS kubelet CRT can be used (as it was not supporting SAN back in that time).
However they [now recommend to remove the workaround](https://docs.datadoghq.com/containers/kubernetes/distributions/?tab=helm#kubelet-serving-certificate-rotation) if the cluster has auto-cert. enabled, which is the case for `privatek8s` :
```
$ kubectl get nodes | wc -l
6
$ kubectl get nodes -L kubernetes.azure.com/kubelet-serving-ca | wc -l
6
```
> fix(privatek8s) remove datadog workaround around kubelet certificate and enable tls verification again

- clusters/privatek8s.yaml
- config/private-nginx-ingress_privatek8s.yaml
- config/public-nginx-ingress_privatek8s.yaml
Note: Successfuly applied manually (due to infra.ci being down - https://status.jenkins.io/issues/2025-07-29-infra.ci-down/) in 2 times (due to ACME requiring Cert Manager CRDs to be installed):
```
helmfile apply -f ./clusters/privatek8s.yaml -l name=cert-manager
helmfile apply -f ./clusters/privatek8s.yaml
```
> feat(privatek8s) add cert-manager, then acme and the ingresses

- clusters/privatek8s.yaml
- config/jenkins-jobs_infra.ci.jenkins.io.yaml
- config/jenkins-kubernetes-agents_release.ci.jenkins.io.yaml
Requires https://github.com/jenkins-infra/azure/pull/1139
Applied manually due to infra.ci being down.
> feat(privatek8s) add infra.ci jobs and release.ci agents releases

- Jenkinsfile_k8s
- clusters/privatek8s.yaml
- config/jenkins_infra.ci.jenkins.io.yaml
Note: merging and then applying to ensure infra.ci, once started, won't try to rollback things.
> feat: migrate infra.ci from privatek8s to privatek8s (CDF) and stop managing privatek8s-sponsorship

- clusters/publick8s.yaml
Reverts jenkins-infra/kubernetes-management#6900
Migration to mirrorbits v0.6.0 on get.jenkins.io failed with the following error during the redis migration:
```
2025/08/07 06:49:07.619 UTC Upgrade failed: redigo: nil returned
github.com/etix/mirrorbits/database/v2.(*Version2).UpdateMirrors
/mirrorbits/database/v2/version2.go:95
github.com/etix/mirrorbits/database/v2.(*Version2).Upgrade
/mirrorbits/database/v2/version2.go:50
github.com/etix/mirrorbits/database.(*Redis).Upgrade
/mirrorbits/database/upgrade.go:78
github.com/etix/mirrorbits/database.(*Redis).dbUpdateHandler
/mirrorbits/database/redis.go:381
runtime.goexit
/usr/local/go/src/runtime/asm_arm64.s:1223
```
Coming from https://github.com/etix/mirrorbits/blob/v0.6/database/v2/version2.go#L92-L96
> Revert "Bump `mirrorbits-parent` helm chart version to 7.1.0"

- clusters/publick8s.yaml
- config/publick8s-redis.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4691
Initial implementation with the following assertions:
- 3 nodes (more efficient reconciliation compared to 2)
- Only 1 master (read and write) but 2 replica (read only)
- Redis Sentinel enabled to track master (as mirrorbits supports it)
- Assuming we start at 1.8 Gb dataset, but allowing for more
> feat(publick8s) add a redis database for mirrorbits usages

- config/datadog_publick8s.yaml
Partial revert of https://github.com/jenkins-infra/kubernetes-management/pull/6852 (for `publick8s` only)
Ref. https://github.com/jenkins-infra/kubernetes-management/pull/6852#issuecomment-3167569856
> fix(publick8s/datadog) re-enable metrics without tlsVerify when accessing kubelet

- clusters/publick8s.yaml
- config/get-jenkins-io.yaml
- Closes https://github.com/jenkins-infra/kubernetes-management/pull/6903 (superseds)
- Ref. https://github.com/jenkins-infra/helpdesk/issues/4764#issuecomment-3174675784 and https://github.com/jenkins-infra/helpdesk/issues/4691#issuecomment-3175499497
This change will fix the following behaviors on get.jenkins.io mirrorbits instance:
- Fix the PID file not being created to a filesystem (remove the error log and use a tmpfs dir for it)
- Fix the downloads logs path to ensure stdout gets the logs
NOTE: the pinning to 0.5.1 is there until we fixed the filesystem
> feat(publick8s/get.jenkins.io) bump mirrorbits-parent chart to latest but pin mirrorbits to `v0.5.1`

- config/updates.jenkins.io-content.yaml
- updatecli/updatecli.d/configs/pvc-updates-jenkins-io-content.yaml
- updatecli/updatecli.d/configs/pvc-updates-jenkins-io-redirections.yaml
hotfix of #6942 
- Updatecli did not track all the subdir correctly
- geoipdata does not support (yet) subdir
- The `mirrorbits` helm chart must detect that we provide twice the same PVC and merge the 2 declarations, otherwise pods are not created (kubelet error).
> fix(publick8s/updates.jenkins.io) correct mirrorbits PVC setup (both updatecli and configuration)

- clusters/publick8s.yaml
- config/updates.jenkins.io-content.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/4767#issuecomment-3180139293
Follows up #6942 and #6943 
Requires https://github.com/jenkins-infra/helm-charts/pull/1761
=> this PR changes the `geoipdata` mount to use the sub directory `updates.jenkins.io/geoipdata` from the common NFS volume. This directory has already been populated, but is NOT kept up to date yet (update once a week usually).
> feat(publick8s/updates.jenkins.io) use the same NFS volume in content for both mirrorbits repository and geoipdata

- config/get-jenkins-io.yaml
Follow up #6958 . It's the same but only for the geoipdata persistent volume.
Ref. https://github.com/jenkins-infra/helpdesk/issues/4767
- The Staging service (staging.get.jenkins.io) shows that we have a working data storage with the provided attributes: https://github.com/jenkins-infra/helpdesk/issues/4764#issuecomment-3187400908 (geoip databases included)
> feat(publick8s/get.jenkins.io) switch persistent volume for geoipupdate to the new data-storage common NFS

- config/get-jenkins-io-mirrorbits.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4764#issuecomment-3191693775
> feat(publick8s/get.jenkins.io) bump mirrorbits from 0.5.1 to 0.6.0

- config/jenkins_infra.ci.jenkins.io.yaml
Ref. https://github.com/jenkins-infra/helpdesk/issues/4769
- Controller image has been set up to use the private registry (https://github.com/jenkins-infra/docker-jenkins-infraci/commit/0a9d43b1c4c80d61733a749289a82912a5ba25bc) and released (https://github.com/jenkins-infra/docker-jenkins-infraci/releases/tag/3.9.21-2.523, but we'll use https://github.com/jenkins-infra/docker-jenkins-infraci/releases/tag/3.9.22-2.523 to get latest plugins)
- Verified that agent images are usable in the `infracijenkinsio-agents2` cluster with a dummy pod
> feat(privatek8s/infra.ci.jenkins.io) use private ACR for both controller and agent Docker images

- clusters/publick8s.yaml
- config/cert-manager_publick8s.yaml
- config/private-nginx-ingress_publick8s.yaml
- `cert-manager` to install its CRDs (required for `acme` and `public-ingress`)
- `private-ingress` (to use as default and verify private subnet LB setup)
> feat(publick8s) add cert-manager and private-ingress charts

- clusters/publick8s.yaml
- config/publick8s_wiki.yaml
- Already applied manually which created the namespace `wiki-jenkins-io`
- Removed the former `wiki` namespace
> fix(publick8s) use coherent naming/NS for wiki.jenkins.io

- config/publick8s_private-nginx-ingress.yaml
We want to expose the private accesses (Azure PLS for updates.jenkins.io, and the private ingress) in the same subnet as the cluster itself
> fix(publick8s) expose private ingress to the cluster subnet
